    <link rel="stylesheet" href="<?php echo $this->basePath();?>/css/admin/jedate.css" />
    <script src="<?php echo $this->basePath();?>/js/admin/jedate.min.js"></script>
                <script type="text/javascript">
                $(function(){
                    $('.user_center ul li').click(function(){
                        $(this).addClass('on').siblings().removeClass('on');
                    })
                })
                </script>
                <div class="user_content_right">
                    <h2 class="goods_h2">我的售后</h2>
                    <ul class="my_goods_list">
                        <li class="<?php if($status == 1) echo 'on'?>"><a href="<?php echo $this->url('index',array('controller'=>'service','action'=>'serviceList','status'=>1))?>">待处理</a></li>
                        <li class="<?php if($status == 2) echo 'on'?>"><a href="<?php echo $this->url('index',array('controller'=>'service','action'=>'serviceList','status'=>2))?>">已处理</a></li>
                    </ul>
                    <div class="clear"></div>
                    <div class="my_good_time">
                        <div class="release_time">
                        <form action="<?php $this->url('index' , array('controller'=>'service','action' => 'index')) ?>" method="get" id="byTime">
                          <span class="fl">申请时间：</span>
                          <div class="start_time">
                            <input type="text"  name="start_time" readonly id="start_time" class="datainp time_input" placeholder="请选择" value="<?php echo isset($start_time) ? substr($start_time, 0 , 10) :''?>"/>
                            </div>
                            <div class="to">至</div>
                            <div class="over_time">
                            <input type="text"  name="end_time"  readonly id="end_time"  class="datainp time_input" placeholder="请选择" value="<?php echo isset($end_time) ? substr($end_time, 0 , 10) :''?>"/>
                            </div>
                            <div class="btn_sure" onclick="Search('sure')">确定</div>
                        </form>
                        </div>
                        <form action="<?php $this->url('index' , array('controller'=>'service','action' => 'index')) ?>" method="get" id="byKeyword">
                            <div class="clearfix search_box pr">
                              <div class="fl">
                                <input type="text" class="search_input" placeholder="请输入订单号搜索" value="<?php echo isset($keyword) ? $keyword :''?>" name="keyword" onfocus=";">
                            </div>
                            <div class="fr"><input type="button" class="search_btn" value="搜索" onclick="Search('search')"></div>
                            </div>
                        </form>
                    </div>
                    <div class="aftersell_center">
                      <ul class="aftersell_list">
                        <li class="aftersell_ordernumber">订单编号</li>
                        <li class="aftersell_goodsname">商品名称</li>
                        <li class="aftersell_time">申请时间</li>
                        <li class="aftersell_type">售后类型</li>
                        <li class="aftersell_state">处理状态</li>
                        <li class="aftersell_operation">操作</li>
                    </ul>
                    <ul class="aftersell_content">
                    <?php if(!empty($services)):?>
                    <?php foreach ($services as $v){?>
                        <li>
                          <div class="aftersell_ordernumber"><?php echo $v->order_sn?>
                          </div>
                          <div class="aftersell_goodsname"><?php echo $v->goods_name?>
                          </div>
                          <div class="aftersell_time"><?php echo $v->customer_service_apply_timestamp?>
                          </div>
                          <?php foreach ($serviceType as $n=>$m){?>
                          <?php if($n == $v->customer_service_apply_type){?>
                          <div class="aftersell_type"><?php echo $m?>
                          </div>
                          <?php }?>
                          <?php }?>
                          <?php foreach ($serviceStatus as $n=>$m){?>
                          <?php if($n == $v->status){?>
                          <div class="aftersell_state"><?php echo $m?>
                          </div>
                          <?php }?>
                          <?php }?>
                          <div class="aftersell_operation">
                            <a href="<?php echo $this->url('index',array('controller'=>'service','action'=>'qualityDetail','id'=>$v->id))?>">查看</a>
                        </div>
                    </li>
                    <?php }?>
                    <?php endif;?>
                </ul>
            </div>
            <div class="clear"></div>
            <?php echo $this->paginationControl($paginator, 'Sliding', 'layout_index/page',array('route' =>'index','condition'=>$condition));?>
                </div>
            </div>
        </div>
        <script type="text/javascript">
        var start ={
        		dateCell:"#start_time",
        		format:"YYYY-MM-DD",
        		isinitVal:false,
        		isTime:true, 
        		maxDate: jeDate.now(0),
        		minDate:"1970-01-01",
        		choosefun: function(datas){
        			end.minDate = datas;
        	    }
        	};
        var end ={
        	dateCell:"#end_time",
        	format:"YYYY-MM-DD",
        	isinitVal:false,
        	isTime:true,
        	minDate:"1970-01-01",
        	maxDate: jeDate.now(0),
        	choosefun: function(datas){
                start.maxDate = datas;
            }
        }
        jeDate(start);
        jeDate(end);
        </script>
        <script type="text/javascript">
        function Search(str)
        {
            if(str == 'sure')
            {
                $("#byTime").submit();
                }else if(str == 'search')
                {
                    $("#byKeyword").submit();
                    }else
                    {
                        return false;
                        }
            }
        </script>