<script src="<?php echo $this->basePath();?>/js/admin/jedate.min.js"></script>
<style>
    .tl{text-align: right;}
    .main-nody{padding:5px 20px 0 20px;}
    .main-nody h5{float: left;}
    .tp{margin-top: 30px;}
    .bc-1{display: none;}
    .fl{float: left;}
</style>
<div class="panel panel-default">
   <div class="panel-heading">
       <div calss="row">
           <div class="col-sm-6">
           <a href="<?php echo $this->url('admin-financial' , array('action' => 'index')) ?>">财务管理 / <a href="">商品统计</a> 
           </div>
       </div>
   </div>
    <div class="pannel-body main-nody">
        <div class="fl" >
		    <a class="btn btn-info fl " href="<?php echo $this->url('admin-financial' , array('action' => 'turnoverStatistics')) ?>">营业额统计</a>
    		<a class="btn btn-info fl " href="<?php echo $this->url('admin-financial' , array('action' => 'goodsStatistics' , 'type' => 1)) ?>">商品统计</a>
    		<a class="btn btn-info fl " href="<?php echo $this->url('admin-financial' , array('action' => 'goodsStatistics' , 'type' => 2)) ?>">资材统计</a>
		</div>
    	<div class="" style="float:right;">
            <form class="form-horizontal" action="<?php echo $this->url('admin-financial' , array('action' => 'goodsStatistics' )) ?>" method="get" style="float: left; margin-left: 20px;">
            <span style="font-weight: bold; font-size: 14px;"> 关键词 :</span>
			<input type="text" name="keyword" value="<?php echo isset($keyword) ? $keyword :''?>" placeholder="请输入商品名称搜索" style="line-height: 26px" >
            <span style="font-weight: bold; font-size: 14px;">申请日期：</span>
			<input class="datainp" id="start_time" type="text" placeholder="请选择"  readonly value="<?php echo isset($start_time) ? $start_time :''?>" name="start_time"  style="line-height:22px;width:160px">
            <span style="font-weight: bold; font-size: 14px;">到：</span>
			<input class="datainp" id="end_time" type="text" placeholder="请选择"  readonly value="<?php echo isset($end_time) ? $end_time :''?>" name="end_time"  style="line-height:22px;width:160px">
			<span style="font-weight: bold; font-size: 14px;">商品分类</span>
			<select style="padding: 5px" name="category_id" onchange="selectGoods(this)">
			     <option value="0">全部分类</option>
			     <?php foreach ($category_list as $key => $value): ?>
			     <option value="<?php echo $value->id ;?>" <?php echo isset($category_id) && $category_id == $value->id? 'selected' : ''?>><?php echo $value->name ?></option>
			     <?php endforeach; ?>
			</select>
			<select style="padding: 5px" name="goods_id"  id="goods_id">
			     <option value="0">全部商品</option>
			     <?php foreach ($goods_list as $key => $value): ?>
			     <option value="<?php echo $value->id ;?>" <?php echo isset($goods_id) && $goods_id == $value->id? 'selected' : ''?>><?php echo $value->name ?></option>
			     <?php endforeach; ?>
			</select>
			<input type="submit"  value="搜索" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
		    </form>
    	</div>
    	<div style="clear:both;"></div>
        
        
         <!-- 商品统计 --><!-- 资材统计 -->
        <div class="row tp">
            <div class="col-lg-12">
                <h5></h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4" >
                    <thead>
        				<tr>
        					<th>日期</th>
        					<th> 商品简码 </th>
        					<th>商品分类</th>
        					<th> 商品名称 </th>
        					<th> 销售数量 </th>
        					<th> 销售均价 </th>
        				</tr>
        			</thead>
        			<tbody>
        			    <?php foreach ($goods_statistics as $value): ?>
                        <tr class="tr_list" valign="middle">
        					<td style="padding-top:18px;"><?php echo substr($value->timestamp, 0 ,10); ?></td>
        					<td style="padding-top:18px;"><?php echo $value->code; ?></td>
        					<td style="padding-top:18px;"><?php echo $value->category_name; ?></td>
        					<td style="padding-top:18px;"><?php echo $value->name; ?></td>
        					<td style="padding-top:18px;"><?php echo $value->number; ?></td>
        					<td style="padding-top:18px;"><?php echo $value->average_price; ?></td>
        				</tr>
        				<?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-financial','condition'=>$condition));?>
        
    </div>
</div>

<script type="text/javascript">
var start ={
		dateCell:"#start_time",
		format:"YYYY-MM-DD",
		isinitVal:false,
		isTime:true, 
		maxDate: jeDate.now(0),
		minDate:"1970-01-01",
		choosefun: function(datas){
			end.minDate = datas;
	    }
	};
var end ={
	dateCell:"#end_time",
	format:"YYYY-MM-DD",
	isinitVal:false,
	isTime:true,
	minDate:"1970-01-01",
	maxDate: jeDate.now(0),
	choosefun: function(datas){
        start.maxDate = datas;
    }
}
jeDate(start);
jeDate(end);
</script>

<script>
function selectGoods(evt)
{
	var category = $(evt).val();
	var type = '<?php echo $type ?>';
	$.post('<?php echo $this->url('admin-financial' , array('action' => 'selectGoods'))?>' , {"category":category , "type":type} , function(data){
		 data =  jQuery.parseJSON(data);
		 console.log(data);
    	 var html = '';
    	 html += '<option value="0">全部商品</option>';
    	 for(var i = 0 ; i < data.length ; i++)
    	 {
        	 console.log(11);
    	    html += '<option value="' + data[i].id + '">' +  data[i].name + '</option>';
    	 }
    	 $('#goods_id').html(html);
	})
}
</script>