<style>
	.dataTables_info{
		display:none;
	}
	.dataTables_paginate{
		display: none;
	}
	.bc-1{display: none;}
	.col-sm-5{display: none;}
	.col-sm-7{display:none;}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
        <a href="<?php echo $this->url('admin-financial' , array('action' => 'index')) ?>">财务管理 / <a href="">充值审核</a>
		</h3>
	</div>
	
	<div class="panel-body">
    	<div class="" style="float:right;">
            <form class="form-horizontal" action="<?php $this->url('admin-order' , array('action' => 'index')) ?>" method="get" style="float: left; margin-left: 20px;">
			<span style="font-weight: bold; font-size: 14px;"> 关键词 :</span>
			<input type="text" name="keyword" value="<?php echo isset($keyword)? $keyword : '';?>" placeholder="请输入企业名称搜索" style="line-height: 26px" >
			<select style="padding: 5px" name="type">
			     <option value="0">全部类型</option>
			     <option value="1" <?php echo isset($type)? $type == 1 :''?>>充值</option>
			     <option value="2" <?php echo isset($type)? $type == 2 :''?>>优惠</option>
			     <option value="3" <?php echo isset($type)? $type == 3 :''?>>账户扣款</option>
			     <option value="4" <?php echo isset($type)? $type == 4 :''?>>账户红冲</option>
			</select>
			<select style="padding: 5px" name="status">
			     <option value="0">全部状态</option>
			     <option value="1" <?php echo isset($status)? $status == 1 :''?>>待审核</option>
			     <option value="2" <?php echo isset($status)? $status == 2 :''?>>审核通过</option>
			     <option value="3" <?php echo isset($status)? $status == 3 :''?>>审核不通过</option>
			</select>
			<input type="submit"  value="搜索" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
		    </form>
    	</div>
    	<div style="clear:both;"></div>
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>企业名称</th>
					<th>企业类型</th>
					<th>操作类型</th>
					<th>操作金额</th>
					<th>申请人</th>
					<th>申请时间</th>
					<th>审核状态</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			     <?php foreach ($financial_list as $value): ?>
                <tr class="tr_list" valign="middle">
					<td><?php echo $value->company_name ?></td>
					<td><?php echo $enterpris_type[$value->user_type] ?></td>
					<td><?php echo $financial_type[$value->type]?></td>
					<td><?php echo $value->cash ?></td>
					<td><?php echo $value->company_name ?></td>
					<td><?php echo $value->timestamp ?></td>
					<td>
    					<?php 
    					  switch ($value->status)
    					  {
    					      case 1:
    					          echo '待审核';
    					          break;
    					      case 2:
    					          echo '审核通过';
    					          break;
    					      case 3:
    					          echo '审核不通过';
    					          break;
    					  }
    					 ?>
					</td>
					<td>
					   <a class="btn btn-info"  href="<?php echo $this->url('admin-financial' , array('action' => 'rechargeCheck' , 'id' => $value->id))?>"> 操作</a>
					   <a class="btn btn-info"  href="<?php echo $this->url('admin-financial' , array('action' => 'rechargeCheck' , 'id' => $value->id))?>"> 查看</a>
					</td>
				</tr>
				<?php endforeach;?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-financial','condition'=>$condition));?>       </div>
</div>