<script src="<?php echo $this->basePath();?>/js/admin/jedate.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->basePath();?>/js/admin/highcharts/jsapi.js" ></script>
<script type="text/javascript"  src="<?php echo $this->basePath();?>/js/admin/highcharts/corechart.js" ></script>
<script type="text/javascript"  src="<?php echo $this->basePath();?>/js/admin/highcharts/jquery.gvChart-1.0.1.min.js" ></script>
<script type="text/javascript"  src="<?php echo $this->basePath();?>/js/admin/highcharts/jquery.ba-resize.min.js" ></script>
<style>
    .tl{text-align: right;}
    .main-nody{padding:5px 20px 0 20px;}
    .main-nody h5{float: left;}
    .tp{margin-top: 30px;}
    .bc-1{display: none;}
    .fl{float: left;}
</style>
<div class="panel panel-default">
   <div class="panel-heading">
       <div calss="row">
           <div class="col-sm-6">
           <a href="<?php echo $this->url('admin-financial' , array('action' => 'index')) ?>">财务管理 / <a href="">营业额统计</a> 
           </div>
       </div>
   </div>
    <div class="pannel-body main-nody">
        <div class="fl" >
		    <a class="btn btn-info fl " href="<?php echo $this->url('admin-financial' , array('action' => 'turnoverStatistics')) ?>">营业额统计</a>
    		<a class="btn btn-info fl " href="<?php echo $this->url('admin-financial' , array('action' => 'goodsStatistics' , 'type' => 1)) ?>">商品统计</a>
    		<a class="btn btn-info fl " href="<?php echo $this->url('admin-financial' , array('action' => 'goodsStatistics' , 'type' => 2)) ?>">资材统计</a>
		</div>
    	<div class="" style="float:right;">
            <form class="form-horizontal" action="<?php $this->url('admin-order' , array('action' => 'index')) ?>" method="get" style="float: left; margin-left: 20px;">
            <span style="font-weight: bold; font-size: 14px;">申请日期：</span>
			<input class="datainp" id="start_time" type="text" placeholder="请选择"  readonly value="<?php echo isset($start_time) ? $start_time :''?>" name="start_time"  style="line-height:22px;width:160px">
            <span style="font-weight: bold; font-size: 14px;">到：</span>
			<input class="datainp" id="end_time" type="text" placeholder="请选择"  readonly value="<?php echo isset($end_time) ? $end_time :''?>" name="end_time"  style="line-height:22px;width:160px">
			<input type="submit"  value="搜索" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
		    </form>
    	</div>
    	<div style="clear:both;"></div>
        
        <div class="row">
            <div class="col-lg-12">
                <h5></h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4" >
                    <tbody>
                        <tr>
                            <td width="18%">总营业额</td>
                            <td><?php echo $total_statistics?>元</td>
                        </tr>
                        <tr>
                            <td width="18%">盆栽营业额</td>
                            <td><?php echo $goods_statistics?>元</td>
                        </tr>
                        <tr>
                            <td width="18%">资材营业额</td>
                            <td><?php echo $equipment_statistics?>元</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div class="row">
            <div class="col-lg-12">
                <h5>营业额比例</h5>
            </div>
            <div class="col-lg-12">
                <table id='myTable5'>
        			<caption>营业额比例</caption>
        			<thead>
        				<tr>
        					<th></th>
        					<th>盆栽营业额</th>
        					<th>资材营业额</th>
        				</tr>
        			</thead>
        			<tbody>
        				<tr>
        					<th><?php echo $total_statistics?></th>
        					<td><?php echo $goods_statistics?></td>
        					<td><?php echo $equipment_statistics?></td>
        				</tr>
        			</tbody>
        		</table>
            </div>
        </div>
        
        <iframe src="<?php echo $this->url('admin-financial' , array('action' => 'statisticsList')) ?>?start_time=<?php echo $start_time; ?>&end_time=<?php echo $end_time?>" id="iframepage" width="100%" frameborder="no" border="0" marginwidth="0" marginheight="0" scrolling="yes" allowtransparency="yes" onLoad="iFrameHeight()">

        </iframe>
        
         <!-- 商品统计 --><!-- 资材统计 -->
        <!-- <div class="row tp">
            <div class="col-lg-12">
                <h5></h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4" >
                    <thead>
        				<tr>
        					<th>日期</th>
        					<th> 商品简码 </th>
        					<th>商品分类</th>
        					<th> 商品名称 </th>
        					<th> 销售数量 </th>
        					<th> 销售均价 </th>
        				</tr>
        			</thead>
        			<tbody>
                        <tr class="tr_list" valign="middle">
        					<td style="padding-top:18px;">2016-06-14 </td>
        					<td style="padding-top:18px;">10245.0</td>
        					<td style="padding-top:18px;">10245.0</td>
        					<td style="padding-top:18px;">20490.0</td>
        					<td style="padding-top:18px;">20490.0</td>
        					<td style="padding-top:18px;">20490.0</td>
        				</tr>
                    </tbody>
                </table>
            </div>
        </div> -->
        
        <?php //echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-financial','condition'=>$condition));?>
        
    </div>
</div>
<div id="clearBothDiv" style="clear:both;height:30px;"></div>
<script type="text/javascript">
gvChartInit();
$(document).ready(function(){
		$('#myTable5').gvChart({
			chartType: 'PieChart',
			gvSettings: {
			vAxis: {title: 'No of players'},
			hAxis: {title: 'Month'},
			width: 600,
			height: 350
		}
	});
});
</script>

<script>   
function iFrameHeight() {   
    var ifm= document.getElementById("iframepage");   
    var subWeb = document.frames ? document.frames["iframepage"].document : ifm.contentDocument;   
    if(ifm != null && subWeb != null) {
       ifm.height = subWeb.body.scrollHeight;
       ifm.width = subWeb.body.scrollWidth;
    }   
}   
</script>

<script type="text/javascript">
var start ={
		dateCell:"#start_time",
		format:"YYYY-MM-DD",
		isinitVal:false,
		isTime:true, 
		maxDate: jeDate.now(0),
		minDate:"1970-01-01",
		choosefun: function(datas){
			end.minDate = datas;
	    }
	};
var end ={
	dateCell:"#end_time",
	format:"YYYY-MM-DD",
	isinitVal:false,
	isTime:true,
	minDate:"1970-01-01",
	maxDate: jeDate.now(0),
	choosefun: function(datas){
        start.maxDate = datas;
    }
}
jeDate(start);
jeDate(end);
</script>