			
			<div id="content" class="span10">
			<!-- content starts -->
			

			<div>
				<ul class="breadcrumb">
					<li>
						<a href="<?php echo $this->url('admin-main');?>">主页</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="<?php echo $this->url('admin-config');?>">站点信息管理</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">管理员类型</a>
					</li>
				</ul>
			</div>
			
			<div>
				<a href="<?php echo $this->url('admin-config',array('action'=>'index'));?>"><button class="btn btn-large ">管理员帐号</button></a>
				<a href="<?php echo $this->url('admin-config',array('action'=>'adminsetting'));?>"><button class="btn btn-large btn-primary">管理员类型</button></a>
				<a href="<?php echo $this->url('admin-config',array('action'=>'adssetting'));?>"><button class="btn btn-large">网站广告设置</button></a>
				<a href="<?php echo $this->url('admin-config',array('action'=>'linkssetting'));?>"><button class="btn btn-large">网站友情链接设置</button></a>
			</div>

			
			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-content">
						<table class="table table-striped table-bordered bootstrap-datatable">
						  <thead>
							  <tr>
								  <th>管理员类型名称</th>
								  <th>更新时间</th>
								   <th>操作</th>
							  </tr>
						  </thead>   
						  <tbody>
						  <?php foreach ($admin as $v):?>
							<tr>
								<td class="center"><?php echo $v['name']?></td>
  	                             <td class="center"><?php echo $v['timestamp_update']?></td>
							    <td class="center">								   
    								<a class="btn btn-success"<?php if ($v['id']==1) {
    									echo "style='display:none'";
    								} ?> href="<?php echo $this->url('admin-config',array('action'=>'editAdminType','id'=>$v['id']));?>">编辑权限</a>
								</td>

							</tr>
							<?php endforeach;?>
						  </tbody>
					  </table>
					  
<!-- 					   <div class="pagination pagination-centered">
						  <ul>
							<li><a href="#">上一页</a></li>
							<li class="active">
							  <a href="#">1</a>
							</li>
							<li><a href="#">2</a></li>
							<li><a href="#">3</a></li>
							<li><a href="#">4</a></li>
							<li><a href="#">下一页</a></li>
						  </ul>
						</div>  -->
					              
					</div>
				</div><!--/span-->
			</div><!--/row-->
			
			</div>