<!-- Responsive Table -->
<!-- Table exporting -->
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
		<a
			href="<?php echo $this->url('admin-config',array('action'=>'addadmin'))?>">
			<button class="btn btn-large btn-info">
				<i class="icon-edit icon-white"></i>
				新增管理员
			</button>
		</a>
		</h3>

		<div class="panel-options">

			<a href="#" data-toggle="panel">
				<span class="collapse-icon">&ndash;</span>
				<span class="expand-icon">+</span>
			</a>
			<a href="#" data-toggle="remove"> &times; </a>
		</div>
	</div>
	<div class="panel-body">
		<table class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>管理员类型</th>
							<th>管理员用户名</th>
							<th>状态</th>
							<th>最近登录时间</th>
							<th>操作</th>
						</tr>
					</thead>
					<tbody>
						  <?php foreach ($admin as $v):?>
							<tr>
							<td><?php echo $v['type_name']?></td>
							<td><?php echo $v['name']?></td>
							<td><?php if($v['status']==1){?>
								<span class="label label-success">正常</span>
								<?php }elseif($v['status']==2){?>
								<span class="label label-important">锁定</span>
								<?php }else{?>未知<?php }?>
								</td>
							<td><?php echo $v['last_time']=='0000-00-00 00:00:00' ? '' : date("Y-m-d H:i",strtotime($v['last_time']));?></td>
							<td>
								<a class="btn btn-success"
									href="<?php echo $this->url('admin-config',array('action'=>'admindetails','id'=>$v['id']));?>">查看</a>
									<?php if($v['status']==1){?>
									<a class="btn btn-warning"
									href="<?php echo $this->url('admin-config',array('action'=>'stop','id' => $v['id'])); ?>">锁定</a>
									<?php }elseif($v['status']==2){?>								
									<a class="btn"
									href="<?php echo $this->url('admin-config',array('action'=>'start','id' => $v['id'])); ?>">启用</a>
									<a class="btn btn-danger" href="javascript:void(0);" onclick="deleteAdmin(<?php echo $v['id'];?>)">删除</a>
									<?php }?>
    								<!-- <a class="btn btn-danger" href="#" onclick="show_confirm('<?php echo $this->url('admin-config',array('action'=>'delet','id' => $v['id'])); ?>')">删除</a> -->
							</td>
						</tr>
							<?php endforeach;?>
						  </tbody>
				</table>
			</div>
		</div>
<script type="text/javascript">
		function deleteAdmin(id)
		{
			var id=id;
			$.post('<?php echo $this->url('admin-config',array('action'=>'deleteAdmin'));?>',{id:id},function(data){
				if(data==1)
				{
					alert('删除成功');
					location.reload();
				}
				else
				{
					alert('删除失败');
				}
			});
		}

</script>