<?php echo $this->headScript()->offsetSetFile(10, $this->basePath() . '/js/ajaxfileupload.js') ?>
<script src="<?php echo $this->basePath();?>/kindeditor/kindeditor.js"></script>
<script src="<?php echo $this->basePath();?>/kindeditor/lang/zh_CN.js"></script>
<script src="<?php echo $this->basePath() ?>/js/Uploads.js"></script>
<script src="<?php echo $this->basePath() ?>/adminStyle/js/jquery.uploadify-3.1.min.js"></script>
<?php echo $this->headLink()->offsetSetStylesheet(15,$this->basePath() . '/css/uploadify.css')?>
<script type="text/javascript">
	var swf ='<?php echo $this->basePath() . '/adminStyle/js/uploadify.swf'?>';
    var uploader = '<?php echo $this->url('admin-common',array('action'=>'getAdminFile'));?>';//图片上传地址 
   var url_two = '<?php echo $this->url('admin-common',array('action'=>'getAdminFileTwo'));?>';//图片上传地址
</script>
<style type="text/css">


.controls input {
	height: 25px;
}

.form-horizontal .control-label {
	width: 200px;
}

.form-control{width: 500px;margin-bottom: 5px;}

.search {
    width: 300px;
    height: 40px;
    position: relative;
}

.edit {
    overflow: hidden;
}

.search_input {
    width: 290px;
    height: 34px;
    font-size: 16px;
}

.search_input:focus {
    outline: none;
}

.match_text {
    display: none;
    position: absolute;
    top: 6px;
    width: 290px;
    z-index: 99;
    background-color: white;
    border: 1px solid #ccc;
}

.match_text div:hover {
    background: #f0f0f0;
}

.match_text ul {
    list-style-type: none;
    border: 1px solid #cccccc;
    margin-bottom: 0px;
}

.match_text ul li {
    font-size: 12px;
    color: #333333;
    display: block;
    line-height: 25px;
    padding-left: 10px;
    cursor: pointer;
}
.box { 
		position: relative; 
		left: 0px; 
		margin-top:30px;
		width: 500px; 
		background-color: #d6d3d6; 
		-moz-border-radius: 7px; 
		-webkit-border-radius: 7px; 
		border: 2px solid #d6d3d6; 
		color: #fff; 
	} 
	.list { 
		margin: 0px; 
		padding: 0px; 
	} 
	.list li { 
		margin: 0px 0px 3px 0px; 
		padding: 3px; 
		cursor: pointer; 
		color:white;
	} 
	.list li:hover { 
		background-color: #659CD8; 
	} 
	.mot_tright{
		margin-left: 200px;
		margin-top: 10px;
	}
.controls span{
	color:#3a3a3a;
}
</style>

<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 style="width:200px;float:left;">个性化背景图片</h3>
				<div class="panel-options">
					<a href="#" data-toggle="panel">
						<span class="collapse-icon">&ndash;</span>
						<span class="expand-icon">+</span>
					</a>
					<a href="#" data-toggle="remove"> &times; </a>
				</div>
			</div>
			<div class="panel-body">
                <form role="form" class="form-horizontal" action="<?php echo $this->url("admin-config",array('action'=>'personal'));?>" method="post">
				<div class="form-group">
					<!--多图片上传-->
					<div class="control-group">
						<label class="col-sm-2 control-label" for="field-1">个性化背景图片：</label>
							<div class="controls">
								<div style="line-height:30px;display:block;height:30px;">提示：(图片比例建议4:3，请上传1-5张图片)</div>
							         <div class="mot_tright" id="img_div">									           
                                       <input id="index_img" type="text" name="image_ids[]" />
                                     </div>
							</div>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-10">
                        <input type='submit' value='添加' class='btn btn-info'  style='margin-left:100px;'/>
					</div>
				</div>
				<div class="form-group-separator"></div>
				</form>
			</div>
		</div>
	</div>
</div>
