<!-- Responsive Table -->
<!-- Table exporting -->
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
			<a
				href="<?php echo $this->url('admin-config',array('action'=>'questionDetails'))?>">
				<button class="btn btn-large btn-info">
					<i class="icon-edit icon-white"></i>
					新增问题
				</button>
			</a>
			<form class="form-horizontal"
				action="<?php echo $this->url('admin-config',array('action'=>'questionDetails'))?>"
				method="post" style="float: right; margin-left: 20px;">
				<span style="font-weight: bold; font-size: 16px;"> 搜索全表：</span>
				<input type="text" name="keyword" value="<?php echo $keyword?>"
					placeholder="搜索 ID">
				<input type="submit" name="submit" value="搜索"
					class="btn btn-large btn-info"
					style="height: 25px; width: 60px; line-height: 25px; padding: 0; margin-left: 10px; margin-top: 5px;" />
			</form>
		</h3>

		<div class="panel-options">

			<a href="#" data-toggle="panel">
				<span class="collapse-icon">&ndash;</span>
				<span class="expand-icon">+</span>
			</a>
			<a href="#" data-toggle="remove"> &times; </a>
		</div>
	</div>
	<div class="panel-body">
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>问题</th>
					<th>答应A</th>
					<th>答应b</th>
					<th>答应c</th>
					<th>答应d</th>
					<th>添加时间</th>
					<th style="width: 295px">操作</th>
				</tr>
			</thead>
			<tbody>
						  <?php if($list){?>
						 <?php foreach($list as $v):?>
						 			   
							<tr>
					<td><?php echo $v->title;?></td>
					<td><?php if($v->answer==1){?><i class="icon-ok"></i><?php }else{?><i
							class="icon-remove"></i><?php }?></td>
					<td><?php if($v->answer==2){?><i class="icon-ok"></i><?php }else{?><i
							class="icon-remove"></i><?php }?></td>
					<td><?php if($v->answer==3){?><i class="icon-ok"></i><?php }else{?><i
							class="icon-remove"></i><?php }?></td>
					<td><?php if($v->answer==4){?><i class="icon-ok"></i><?php }else{?><i
							class="icon-remove"></i><?php }?></td>
					<td class="center"><?php echo $v->timestamp == '0000-00-00 00:00:00' ? '' : date("Y-m-d H:i",strtotime($v->timestamp));?></td>
					<td class="center">
						<a class="btn btn-info" <?php if($v->delete==0){?>
							href="<?php echo $this->url('admin-config',array('action'=>'questionDetails','id'=>$v->id))?>"
							<?php }else{?> disabled <?php }?>> 查看 </a>
						<a class="btn btn-danger" <?php if($v->delete==0){?>
							onclick="show_confirm('<?php echo $this->url('admin-config',array('action'=>'questionDelete','id'=>$v->id));?>')"
							href="#" <?php }else{?> disabled <?php }?>>删除</a>
					</td>
				</tr>
							<?php endforeach;?>
							<?php }?>						
						  </tbody>
		</table>

					   
						  <?php    echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-config','condition'=>$condition));?> 
						</div>

</div>


