<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>问题详情</h3>
				<div class="panel-options">
					<a href="#" data-toggle="panel">
						<span class="collapse-icon">&ndash;</span>
						<span class="expand-icon">+</span>
					</a>
					<a href="#" data-toggle="remove"> &times; </a>
				</div>
			</div>
			<form role="form" class="form-horizontal" action="<?php echo $this->url('admin-config',array('action'=>'addQuestion'))?>"
					method="post">
				<div class="panel-body">
						
				  <div class="form-group">
						<label class="col-sm-2 control-label" for="field-1">问题：</label>

						<div class="col-sm-10">
							<input type="text" class="form-control" id="field-1" name="name"
								value="<?php echo isset($info->title) ? $info->title : '';?>">
						</div>
					</div>
					<div class="form-group-separator"></div>
					
					
					 <div class="form-group">
						<label class="col-sm-2 control-label" for="field-1"></label>

						<div class="col-sm-10">
								    答案A： <input class="input-xlarge disabled" id="disabledInput" type="text" value="<?php echo isset($info->option_a) ? $info->option_a : '';?>" name="option_a">
                                    正确答案： <input type="radio" name="answer" id="optionsRadios1" value="1" <?php if(isset($info->answer) && $info->answer==1){?>checked="checked"<?php }?>><br/><br/>
                                     答案B： <input class="input-xlarge disabled" id="disabledInput" type="text" value="<?php echo isset($info->option_b) ? $info->option_b : '';?>" name="option_b">
                                     正确答案： <input type="radio" name="answer" id="optionsRadios1" value="2" <?php if(isset($info->answer) && $info->answer==2){?>checked="checked"<?php }?>><br/><br/>
                                     答案C： <input class="input-xlarge disabled" id="disabledInput" type="text" value="<?php echo isset($info->option_c) ? $info->option_c : '';?>" name="option_c">
                                     正确答案： <input type="radio" name="answer" id="optionsRadios1" value="3" <?php if(isset($info->answer) && $info->answer==3){?>checked="checked"<?php }?>><br/><br/>
                                     答案D： <input class="input-xlarge disabled" id="disabledInput" type="text" value="<?php echo isset($info->option_d) ? $info->option_d : '';?>" name="option_d">
                                     正确答案： <input type="radio" name="answer" id="optionsRadios1" value="4" <?php if(isset($info->answer) && $info->answer==4){?>checked="checked"<?php }?>><br/><br/>
						</div>
					</div>
					<div class="form-group-separator"></div>
					
					<div class="form-group">
						<label class="col-sm-2 control-label" for="field-1">排序：</label>

						<div class="col-sm-10">
							<input type="text" class="form-control" id="field-1" value="<?php echo isset($info->sort) ? $info->sort : '';?>" name="sort">
						</div>
					</div>
					<div class="form-group-separator"></div>
							   
							  
							
					<div class="form-group">
						<label class="col-sm-2 control-label" for="field-1"></label>

						<div class="col-sm-10">
							 <input type="hidden" name="id" value="<?php echo isset($info->id) ? $info->id : '';?>"/>
								 <input type="submit" class="btn btn-info" name="submit" style="margin-left: 100px" value="保存">
						</div>
					</div>
					<div class="form-group-separator"></div>
					</div>
						  </form>					
					</div>
				</div>
			</div>