<?php echo $this->headLink()->appendStylesheet($this->basePath() . '/css/demo.Default.css')?>
<script src="<?php echo $this->basePath();?>/kindeditor/kindeditor.js"></script>
<script src="<?php echo $this->basePath();?>/kindeditor/lang/zh_CN.js"></script>
<?php echo $this->headScript()->offsetSetFile(10, $this->basePath() . '/js/ajaxfileupload.js') ?>
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/jq_area.js') ?>
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/region.js') ?>
<?php $tem = array("zero"=>'一'/*,"first"=>'二',"second"=>'三',"third"=>'四',"fourth"=>'五',"fifth"=>'六',"sixth"=>'七',"seventh"=>'八'*/); ?>
<script language="javascript" src="http://webapi.amap.com/maps?v=1.3&key=d4e906f2d3b338bc0fa31cba41b4c5ca"></script>
<!-- //上传JS -->
<script type="text/javascript">
var url = '<?php echo $this->url('admin-common',array('action'=>'getAdminFile'));?>';//图片上传地址
var url_two = '<?php echo $this->url('admin-common',array('action'=>'getAdminFileTwo'));?>';//图片上传地址
</script>
<style type="text/css">
.match_text div:hover {
	background: #f0f0f0;
}

.add_input {
	border: 1px dashed #cccccc;
	margin-top: 5px;
	color: #cccccc;
}

.close {
	margin-top: 10px;
	margin-left: 10px;
	float: left;
}

.form-control {
	width: 50%;
	float: left;
	margin-bottom: 5px;
	margin-right: 5px;
}

.view_box {
	width: 379px;
	height: 795px;
	background: url("<?php echo ROOT_PATH; ?>images/iphone-frame.png")
		no-repeat;
	position: fixed;
	left: 40%;
	top: 10%;
	z-index: 10;
}

.inner_box {
	margin-top: 116px;
	margin-left: 32px;
	width: 319px;
	height: 568px;
	overflow: hidden;
}

.red_star {
	color: red;
}
</style>
<div class="row">
	<form role="form" class="form-horizontal" action="<?php echo $this->url('admin-ads', array('action' => 'addads')) ?>" method="post">
		<div class="col-sm-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>广告信息</h3>
				</div>
				<div class="panel-body">
					<div class="form-group">
						<label class="col-sm-2 control-label"><i class="red_star">*&nbsp;</i>标题文字：</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" placeholder="请填写广告标题" required name="adName" value="" id="" maxlength="25"/>
						</div>
					</div>

					<div class="form-group-separator"></div>
					
					<div class="form-group">
						<label class="col-sm-2 control-label"><i class="red_star">*&nbsp;</i>广告类型:</label>
						<div class="col-sm-10">
							<select id="type-input" class="form-control input-sm" name="type" onchange="changeType(this.value)"><option value="0">没链接/跳转</option><option value="1">网页</option><option value="2">内部跳转</option></select>
						</div>
					</div>
					
					<div class="form-group" id="target-div" style="display:none;">
						<label class="col-sm-2 control-label" id="link">目标类型:</label>
						<div class="col-sm-10">
							<input id="target-input" name="target" class="form-control" type="text" value="" placeholder="目标类型如web、activity"/>
						</div>
					</div>
					
					<div class="form-group" id="link-div" style="display:none;">
						<label class="col-sm-2 control-label" id="link">广告链接/目标id:</label>
						<div class="col-sm-10">
							<input id="link-input" class="form-control" type="text" name="link" value="" placeholder="广告链接(如http://www.kuaiyao.name)/目标id"/>
						</div>
					</div>
					
					<div class="form-group-separator"></div>
					
					<div class="form-group">
						<label class="col-sm-2 control-label"><i class="red_star">*&nbsp;</i>广告图：</label>

						<div class="col-sm-10">
							<input type="file" id="img0" name="Filedata"
								onchange="return ajaxFileUpload('0');" /> <input type="hidden"
								name="image"
								value="<?php echo isset($info['head_icon']) ? $info['head_icon'] : ''; ?>"
								id="img_id_0" /> <br /> <img
								src="<?php echo isset($info['head_icon']) && isset($images[$info['head_icon']]['path']) ? $images[$info['head_icon']]['path'] : ROOT_PATH . 'adminStyle/img/no_pic.gif'; ?>"
								width="200" height="200" id="img_0" />

						</div>
					</div>	
					
					<div class="form-group-separator"></div>
					
					<div class="form-group">
						<label class="col-sm-2 control-label" for="field-1"></label>
						<div class="col-sm-10">
							<input type="submit" name="submit" value="添加"
								class="btn btn-info" />
						</div>
					</div>
					
					<div class="panel-body" style="background: #f0f0f0;">
					</div>
				</div>
			</div>
		</div>
	
	</form>
</div>
<div class="dialog_bg none template">
	<a href=""></a>
	<div class="view_box">
		<div class="inner_box">
			<iframe id="iframe" height="567px" width="350px"
				src="<?php echo PREVIEW_PATH."zero.html"; ?>" frameborder="0"
				scrolling="yes"></iframe>
		</div>
	</div>
</div>

<div class="dialog_bg none html">
	<a href=""></a>
	<div class="view_box">
		<div class="inner_box">
			<iframe id="iframe" height="567px" width="350px"
				src="<?php echo ROOT_PATH.'static_html/'.$info->html.".html"; ?>"
				frameborder="0" scrolling="yes"></iframe>
		</div>
	</div>
</div>

<script type="text/javascript">
function changeType(type)
{
	if (0 == type) {
		$("#target-div").hide();
		$("#link-div").hide();
		$("#target-input").val("");
		$("#link-input").val("");
	}
	else if (1 == type) {
		$("#target-div").show();
		$("#link-div").show();
		$("#target-input").val("web");
		$("#target-input").attr("readonly","readonly");
		$("#link-input").val("");
	}
	else if (2 == type) {
		$("#target-div").show();
		$("#link-div").show();
		$("#target-input").val("");
		$("#target-input").removeAttr("readonly");
		$("#link-input").val("");
	}
}
</script>
