<!-- Responsive Table -->
<!-- Table exporting -->
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
		<a
				href="<?php echo $this->url('admin-task',array("action"=>"addTask"))?>"
				style="float: right;margin-left: 20px;"">
				<button class="btn btn-large btn-info">添加新标任务/活动</button>
			</a>
			<a
				href="<?php echo $this->url('admin-task',array('action'=>'operateTask','cid'=>'1'))?>">
				<button class="btn btn-large <?php if($cid==1){?>btn-info<?php }?>">任务</button>
			</a>
			<a
				href="<?php echo $this->url('admin-task',array('action'=>'operateTask','cid'=>'2'))?>">
				<button class="btn btn-large <?php if($cid==2){?>btn-info<?php }?>">活动</button>
			</a>
			<form class="form-horizontal"
				action="<?php echo $this->url('admin-task',array('action'=>'operateTask','cid'=>$cid))?>"
				method="post" style="float: right; margin-left: 20px;">
				<span style="font-weight: bold; font-size: 16px;"> 搜索全表</span>
				：
				<input type="text" name="keyword" value="<?php echo $keyword?>"
					placeholder="搜索 ID、任务描述、发布人">
				<input type="submit" name="submit" value="搜索" class="btn btn-info"
					style="height: 25px; width: 60px; line-height: 25px; padding: 0; margin-left: 10px; margin-top: 5px;" />
			</form>
			
		</h3>

		<div class="panel-options">

			<a href="#" data-toggle="panel">
				<span class="collapse-icon">&ndash;</span>
				<span class="expand-icon">+</span>
			</a>
			<a href="#" data-toggle="remove"> &times; </a>
		</div>
	</div>
	<div class="panel-body">
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>ID</th>
					<th>任务描述</th>
					<th>人均悬赏</th>
					<th>人均追加悬赏</th>
					<th><?php if($cid == 1){?>执行人数<?php }else{ ?>活动规模<?php }?></th>
					<th>报名</th>
					<th>评论</th>
					<th>赞</th>
					<th>任务地址</th>
					<th>发布人</th>
					<th>支付状态</th>
					<th>状态</th>
					<th><?php if($cid == 1){?>任务截止时间<?php }else{?>活动开始时间<?php }?></th>
					<th>发表时间</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
						  <?php if($list){?>
						 <?php foreach($list as $v):?>
						 			   
							<tr>
					<td><?php echo $v->id;?></td>
					<td><?php echo emoji_unified_to_html(mb_substr($v->content, 0, 15, 'UTF-8'));?></td>
					<td><?php echo $this->escapehtml($v->reward);?></td>
					<td><?php echo $this->escapehtml($v->reward_plus);?></td>
					<td><?php echo $this->escapehtml($v->limit);?></td>
					<td>
						<a
							href="<?php echo $this->url('admin-task',array('action'=>'signUp','cid'=>$v->id))?>"><?php echo $v->stat_join;?></a>
					</td>
					<td>
						<a
							href="<?php echo $this->url('admin-task',array('action'=>'comment','cid'=>$v->id))?>"><?php echo $v->stat_comment;?></a>
					</td>
					<td><?php echo $v->stat_praise;?></td>
					<td style="text-align: left"><?php echo mb_substr($v->address, 0,10,'utf-8');?></td>
					<td>
						<a
							href="<?php echo $this->url("admin-user",array('action'=>'details','id'=>$v->user_id))?>"><?php echo $v->nickname ? $v->nickname : $v->id_name;?></a>
					</td>
					<td><?php echo isset($pay_status[$v->pay_status]) ? $pay_status[$v->pay_status] : '未知'?></td>
					<td><?php echo isset($task_status[$v->status]) ? $task_status[$v->status] : '未知';?></td>

					<td><?php echo $v->deadline == '0000-00-00 00:00:00' ? '' :date("Y-m-d H:i",strtotime($v->deadline));?></td>
					<td><?php echo $v->timestamp == '0000-00-00 00:00:00' ? '' :date("Y-m-d H:i",strtotime($v->timestamp));?></td>
					<td>
						<a class="btn btn-info"
							href="<?php echo $this->url('admin-task',array('action'=>'operateTaskDetails','id'=>$v->id))?>">
							查看 </a>
									<?php if($v->delete==0){?> 
    									<a class="btn btn-danger"
							href="<?php echo $this->url('admin-task',array('action'=>'delete','id'=>$v->id,'page'=>1));?>">
							隐藏 </a>
									<?php }else{ ?>
									   <a class="btn"
							href="<?php echo $this->url('admin-task',array('action'=>'delete','id'=>$v->id,'page'=>0));?>">
							启用 </a>
									<?php }?>																						
								</td>
				</tr>
							<?php endforeach;?>
							<?php }?>						
						  </tbody>
		</table>
						  <?php    echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-task','condition'=>$condition));?> 
						</div>

</div>
