
			<div id="content" class="span10">
			<!-- content starts -->
			

			<div>
				<ul class="breadcrumb">
					<li>
						<a href="#">运营</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="<?php echo $this->url('admin-user',array('action'=>'operateUser','cid'=>'1'))?>">运营用户管理</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">充值</a>
					</li>
				</ul>
			</div>
			<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-content">
						<form class="form-horizontal" action="<?php echo $this->url('admin-user',array('action'=>'recharge','page'=>$page));?>" method="post" onsubmit="return check()">
							<fieldset>
							<legend class="lg_title">
							<span>充值信息：</span>
						    </legend>
						     <div class="control-group">
							 	 <label class="control-label" for="focusedInput">当前用户信息：</label>
								 	<div class="controls">									
									 <span style="display: inline-block; margin-top: 4px;"><?php echo $info->nickname;?>&nbsp&nbsp快应币：<span style="color:red;"><?php echo $info->stat_money;?></span></span> 
									  
									</div>
							  </div>
							  <div class="control-group">
							 	 <label class="control-label" for="focusedInput">充值金额：</label>
								 	<div class="controls">									
									<input class="input-xlarge disabled" id="stat_money" type="text" name="stat_money" placeholder="请输入要充值的金额">&nbsp&nbsp
									</div>
							  </div>
							 							  
							  <div class="form-actions">
							    <input type="hidden" name="id" value="<?php echo $info->id;?>"/>
								<input  type="submit" class="btn btn-primary" value="充值" name="submit">
								<input type="reset" class="btn">
							  </div>
							</fieldset>
						  </form>					
					</div>
				</div><!--/span-->
			</div><!--/row-->
			
			</div>
			
<script type="text/javascript">
function check()
{	
	var stat_money = $("#stat_money").val();
	var user_stat_money = <?php echo $info->stat_money;?>;
	if(stat_money < 0)
	{
    	if((user_stat_money - Math.abs(stat_money)) < 0)
    	{
    		alert('金额非法!');
    		return false;
    	}
	}
    if(stat_money && (isNaN(stat_money) || stat_money==0)){
          alert('金额非法!');
          return false;
     }
    if(stat_money){
        return true;
    }
    else
    {
        alert('金额不能为空！');
        return false;
    }
    return false;
	
}
</script>			