<?php use Core\System\WxApi\jssdk;?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width,inital-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-status-bar-style" content="block" />
	<meta name="format-detection" content="telephone=no" />
	<title><?php echo isset($company['name']) ? $company['name'] : "";?>-快摇名片</title>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/templet_zero_two.css?v=<?php echo time() ?>" />
	<!--样式图标库-->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/fonts/fontawesome/css/font-awesome.min.css?v=<?php echo time() ?>" />
	<!--只兼容移动端，所以直接使用jQuery 2.1.4-->
	<script type="text/javascript" src="<?php echo $this->basePath();?>/lib/jquery.2.1.4.min.js"></script>
	<!--调用微信js-->
	<script src="<?php echo $this->basePath();?>/lib/jweixin-1.0.0.js"></script>
  <script>
    /*拨打电话*/
    function touchTel(telnum){window.location.href="tel:"+telnum;}
    /*查看位置*/
    function openlocation(){if(isWeixin){wx.openLocation(addressObj);}else{alert("请在微信中打开名片才能定位")}}
  </script>

</head>
<body onload="getJssdk()">
	<!--头像、姓名、英文名-->
	<header class="wrap bg_white nob pb5 pt10">
   <div class="clearfix company_img pt10 pb10 pl10 pr10">
    <img class="w"  style="width:75px; height:60px;" src="<?php echo $companyLogo ? $this->basePath() . '/' . UPLOAD_PATH .$companyLogo : $this->basePath() . '/images/img_logo@3x.png' ?>">
    <span id = "imagePath" style="display:none;"><?php echo $this->basePath() . '/' . UPLOAD_PATH .$companyLogo?></span>
  </div>
  <div class="flex1 company_text ">
    <p class=" txt_overflow none_bold f120pct"><?php echo $this->escapeHtml($company['name'])?></p>
    <p class="line2_overflow f14">
     <span class="f_color_gray border_right"><?php echo $this->escapeHtml($region['name']);?></span>
     <span class="f_color_gray pl5 border_right">
      <?php foreach($category as $k=>$v){
        if($company['category_id']==$k){
         echo $this->escapeHtml($v);
       }
     }
     ?>
   </span>
   <span class="f_color_gray pl5">
    <?php foreach($scale as $k=>$v){
      if($company['scale']==$k){
       echo $this->escapeHtml($v);
     }
   }
   ?>
 </span>
</p>
<p class="f_color_gray f14"><?php echo $this->escapeHtml($company['home'])?></p>
</div>
</header>
<!--联系方式-->

<div class="">

  <p class="none_bold f_color_b mt15 pb10 pl10 pr15 "><span class="f140pct">公司简介</span>
<?php if(trim($company['description'])!==''){?>
   <a href="<?php echo $this->url('index', array('controller' => 'company', 'action' => 'pageContent', 'id' => $company['id'], 'alert' => '1'));?>" class="fr f_color_gray icon_arrowR f14 pr20" style="line-height:21px;">查看详情</a>
<?php }else{}?>
 </p>
 <div class="bg_white clearfix signature border_topdown pt10" style="">
   <p  id="description" class="f120pct mh2l"><?php if(trim($company['description'])!==''){echo mb_substr(htmlspecialchars_decode($this->escapeHtml(trim(strip_tags($company['description'])))),0,40,'utf-8').'...';}else{echo '暂无内容，请联系快摇名片小助手';}?></p>
 </div>
 <p class="none_bold f_color_b mt10 pb10 pl10 pr10 "><span class="f140pct">经营项目</span>
 <?php if(trim($company['project'])!==''){?>
   <a href="<?php echo $this->url('index', array('controller' => 'company', 'action' => 'pageContent', 'id' => $company['id'], 'alert' => '2'));?>" class="fr f_color_gray icon_arrowR f14 pr20" style="line-height:21px;">查看详情</a>
 <?php }else{}?>
	
 </p>

 <div class="bg_white clearfix signature border_topdown pt10" style="">
   <p  style="" id="project" class="f120pct pr20 mh2l"><?php if(trim($company['project'])!==''){echo mb_substr(htmlspecialchars_decode($this->escapeHtml(trim(strip_tags($company['project'])))),0,40,'utf-8');}else{echo '暂无内容，请联系快摇名片小助手';}?></p>

 </div>
 <?php if(trim($company['address']) || trim($company['telephone'])){?>
 <h3 class="none_bold f_color_b mt20 pb15 pl10 pr10 f140pct">公司信息</h3>
 <ul class="bg_white listview0 border_topdown f120pct">
 <?php if(trim($company['telephone'])){?>
   <li class="border_bottom ml20">
    <a id="telephone" class="icon_phone d_ib w54"><?php echo $this->escapeHtml($company['telephone'])?></a>
    <a class="a1and btn_o fr bg_orange f_color_white lh20 mt10 mr10 p3" onclick="window.Interactive.call('<?php echo $this->escapeHtml($company['telephone'])?>')">拨号</a>
    <a class="a1ios btn_o fr bg_orange f_color_white lh20 mt10 mr10 p3" onclick="fn_call()">拨号</a>
    <a class="a1wx btn_o fr bg_orange f_color_white lh20 mt10 mr10 p3" style="display:none;" href="javascript:touchTel('<?php echo $this->escapeHtml($company['telephone'])?>')"> 拨号</a>
  </li>
  <?php }?>
  <?php if(trim($company['address'])){?>
  <li class="ml20" id="">
    <a id="address" class="icon_address d_ib w54 lh30" style="vertical-align: middle;"><?php echo $this->escapeHtml($company['address'])?></a>
    <a class="btn_o fr bg_orange f_color_white lh20 mt10 mr10 p3 companyzhiwei_wzand" onclick="window.Interactive.getLocation('<?php echo $company['address']?>');">位置</a>
    <a  class="companyzhiwei_wzios btn_o fr bg_orange f_color_white lh20 mt10 mr10 p3" onclick="fn_location();">位置</a>
  </li>
  <?php }?>
</ul>
 <?php }?>
</div>


<!--底部浮动的下载APP提醒--><!-- <footer>
<a href="http://a.app.qq.com/o/simple.jsp?pkgname=com.aiitec.shakecard" title="下载快摇名片APP,快速获取您的个性名片">点击这里，下载快摇名片APP！</a>
</footer> -->
<!--
<footer>
    <a onclick="sAlert();" title="点击这里，下载快摇名片APP！" id="phoneclass">点击这里，下载快摇名片APP！</a>
</footer>
-->
</body>
<!-- 判断设备显示不同的调用 -->
<script type="text/javascript">
  /*页面数据和ios交互*/
    // var fn_save = document.getElementById("qrc_save").value; 
    // var _title = document.getElementById("title").value; 
    function fn_save() {

//     //调用OC中openCamera方法
//     // window.location.href = '"test://save"?+fn_save?+_title';
  window.location.href = 'test://save?<?php echo $company['telephone']?>';

}
function fn_location() {
        //var fn_location = document.getElementById("address").value;  
     // 调用OC中openCamera方法
     window.location.href = 'test://location?<?php echo $company['address']?>';
   }
   function fn_call() {
    window.location.href = 'test://call?<?php echo $company['telephone']?>';
  }

  var browser = { versions: function() { 
    var u = navigator.userAgent, app = navigator.appVersion; return {
//移动终端浏览器版本信息  
trident: u.indexOf('Trident') > -1, 
    //IE内核 
    presto: u.indexOf('Presto') > -1,
     //opera内核
     webKit: u.indexOf('AppleWebKit') > -1, 
      //苹果、谷歌内核 
      gecko: u.indexOf('Gecko') > -1 && u.indexOf('KHTML') == -1, 
      //火狐内核 
      mobile: !!u.match(/AppleWebKit.*Mobile.*/) || !!u.match(/AppleWebKit/), 
      //是否为移动终端 
      ios: !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/), 
        //ios终端 
        android: u.indexOf('Android') > -1 || u.indexOf('Linux') > -1, 
        //android终端或者uc浏览器 
        iPhone: u.indexOf('iPhone') > -1 || u.indexOf('Mac') > -1, 
        //是否为iPhone或者QQHD浏览器 
        iPad: u.indexOf('iPad') > -1, 
        //是否iPad 
        webApp: u.indexOf('Safari') == -1 
        //是否web应该程序，没有头部与底部 
      }; }(), 
      language: (navigator.browserLanguage || navigator.language).toLowerCase() 
    }   
    if (browser.versions.ios || browser.versions.iPhone || browser.versions.iPad) {
      $(".companyzhiwei_wzand").css("display","none");
      $(".a1and").css("display","none");
    } 
    else{ 
     $(".companyzhiwei_wzios").css("display","none");
     $(".a1ios").css("display","none");
   } 

 </script>
 <!-- 判断下载软件 -->
 <script type="text/javascript">

  function isMoblie(){
    var browser = { versions: function() { 
      var u = navigator.userAgent, app = navigator.appVersion; return {
    //移动终端浏览器版本信息  
    trident: u.indexOf('Trident') > -1, 
        //IE内核 
        presto: u.indexOf('Presto') > -1,
         //opera内核
         webKit: u.indexOf('AppleWebKit') > -1, 
          //苹果、谷歌内核 
          gecko: u.indexOf('Gecko') > -1 && u.indexOf('KHTML') == -1, 
          //火狐内核 
          mobile: !!u.match(/AppleWebKit.*Mobile.*/) || !!u.match(/AppleWebKit/), 
          //是否为移动终端 
          ios: !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/), 
            //ios终端 
            android: u.indexOf('Android') > -1 || u.indexOf('Linux') > -1, 
            //android终端或者uc浏览器 
            iPhone: u.indexOf('iPhone') > -1 || u.indexOf('Mac') > -1, 
            //是否为iPhone或者QQHD浏览器 
            iPad: u.indexOf('iPad') > -1, 
            //是否iPad 
            webApp: u.indexOf('Safari') == -1 
            //是否web应该程序，没有头部与底部 
          }; }(), 
          language: (navigator.browserLanguage || navigator.language).toLowerCase() 
        }
    //console.log(browser);
    if (browser.versions.ios || browser.versions.iPhone || browser.versions.iPad) { 

      $("#phoneclass").attr("href","https://itunes.apple.com/cn/app/kuai-yao-ming-pian-zui-ju/id1028830091?mt=8");

    } 
    else if (browser.versions.android) { 

      $("#phoneclass").attr("href","http://www.kuaiyao.name/download/ky.apk");
    }  

  }

  var user=(navigator.userAgent).toLocaleLowerCase(),isWeixin=false,ht="",hta="",addressObj,shareData,touchState=true;

  function getJssdk()
  {
    $('.notouchmove').bind({touchstart:function(e){touchState=true;},touchmove:function(e){touchState=false;}});
    isMoblie();
    /*判断是否在微信打开*/
    if(user.indexOf('micromessenger')!==-1)
    {
      isWeixin=true;
      <?php 
      include_once APP_PATH . '/config.php';
      $jssdk = new jssdk(WEIXIN_APP_ID, WEIXIN_APP_SECRET, "http://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
      $signPackage = $jssdk->getSignPackage();
      ?>

      wx.config({
        debug: false,
        appId: '<?php echo WEIXIN_APP_ID;?>',
        timestamp: <?php echo $signPackage['timestamp'];?>,
        nonceStr: '<?php echo $signPackage['nonceStr'];?>',
        signature: '<?php echo $signPackage['signature'];?>',
        jsApiList: [
        'checkJsApi',
        'onMenuShareTimeline',
        'onMenuShareAppMessage',
        'onMenuShareQQ',
        'onMenuShareWeibo',
        'openLocation'
        ]
      });
      wx.ready(function () {
        /*设定微信分享内容*/
                shareData = {title: '<?php echo $card['title'];?>的快摇名片',desc: '公司：<?php echo $card['company'];?>\n职位：<?php echo $card['position'];?>\n点击查看更多信息',imgUrl: '<?php echo 'http://' . $_SERVER['HTTP_HOST'] . $this->basePath() . '/' . UPLOAD_PATH . $head_icon;?>'};
                /*设定微信地址导航*/
                addressObj={latitude: <?php echo $card['latitude'] ? $card['latitude'] : 0.00;?>,longitude: <?php echo $card['longitude'] ? $card['longitude'] : 0.00;?>,name: '<?php echo $card['company'];?>',address: '<?php echo $card['address'];?>',scale: 14,infoUrl: '<?php echo $_SERVER['HTTP_HOST'] . $_SERVER['REDIRECT_URL'];?>'};
                wx.onMenuShareAppMessage(shareData);
                wx.onMenuShareTimeline(shareData);
                wx.onMenuShareQQ(shareData);
                wx.onMenuShareWeibo(shareData);
              }); 

         //$("#qrc_save,#qrc_guanzhu").css("width","48%");

       }
       else{
        isWeixin=false;
        console.log("this isn't weixin");
        $("#qrc_save").css("width","100%");
        $("#qrc_guanzhu").hide();
        $(".a1and").css("display","none");
      }
    }
    
    /*弹出二维码*/
    function qrc_show(qrc){
      if(isWeixin){$("#"+qrc).css('top','0px').show();$("#qrc_bg").show();}
      else{if(qrc=="qrc_card"){window.location.href="<?php echo HTTP;?>/uploadfiles/vcard/" + "<?php echo $vcard['vcard'];?>"/*vcard路径*/;}}
    }
    /*隐藏二维码*/
    function qrc_hide(qrc){$("#"+qrc).css('top','100%').hide();$("#qrc_bg").hide();}

//  $(documnet).ready(function(e) {
//      /*绑定在滑动界面时候不会触发点击事件*/
//      $('.notouchmove').bind({touchstart:function(e){touchState=true;},touchmove:function(e){touchState=false;}});
//  });
/*判断保存到通讯录隐藏和显示*/
function setAttention(attention){
  if (attention==3) {
    $(".cardOperation").css("display","block");
  }else{
    $(".cardOperation").css("display","none");
  };
}

</script>

</html>