<script src="<?php echo $this->basePath();?>/js/admin/jedate.min.js"></script>
<style>
	.dataTables_info{
		display:none;
	}
	.dataTables_paginate{
		display: none;
	}
	.bc-1{display: none;}
	.col-sm-5{display: none;}
	.col-sm-7{display:none;}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
        <a href="<?php echo $this->url('admin-service' , array('action' => 'index'))?>">售后留言管理/ <a href="">售后管理</a>
		</h3>
	</div>
	
	<div class="panel-body">
    	<div class="" style="float:right;">
            <form class="form-horizontal" action="<?php $this->url('admin-service' , array('action' => 'index')) ?>" method="get" style="float: left; margin-left: 20px;">
            <span style="font-weight: bold; font-size: 14px;">提交日期：</span>
            <input type="text"  style="line-height: 22px"  name="start_time" readonly id="start_time" class="datainp" placeholder="请选择" value="<?php echo isset($start_time) ? $start_time :''?>"/>
            <span style="font-weight: bold; font-size: 14px;">到：</span>
			<input type="text"  style="line-height: 22px"  name="end_time"  readonly id="end_time"  class="datainp" placeholder="请选择" value="<?php echo isset($end_time) ? $end_time :''?>"/>
			<span style="font-weight: bold; font-size: 14px;"> 关键词 :</span>
			<input type="text" name="keyword" value="<?php echo isset($keyword) ? $keyword :''?>" placeholder="请输入订单号/企业名称搜索" style="line-height: 26px" >
			<select style="padding: 5px" name="status">
			     <option value='0'>全部状态</option>
			     <?php foreach ($serviceStatus as $k=>$v){?>
			     <option value="<?php echo $k?>" <?php echo isset($status)&&$status == $k ? 'selected' : ''?>><?php echo $v?></option>
			     <?php }?>
			</select>
			<select style="padding: 5px" name="type">
			     <option value='0'>全部类型</option>
			     <?php foreach ($serviceType as $k=>$v){?>
			     <option value="<?php echo $k?>" <?php echo isset($type)&&$type == $k ? 'selected' : ''?>><?php echo $v?></option>
			     <?php }?>
			</select>
			<input type="submit"  value="搜索" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
		    </form>
    	</div>
    	<div style="clear:both;"></div>
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>订单编号</th>
					<th>企业名称</th>
					<th>问题类型</th>
					<th>问题描述</th>
					<th>提交时间</th>
					<th>处理状态</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			<?php if(!empty($services)):?>
			<?php foreach ($services as $v){?>
                <tr class="tr_list" valign="middle">
					<td style="padding-top:18px;"><?php echo $v->order_sn?></td>
					<td style="padding-top:18px;"><?php echo $v->company_name?></td>
					<?php foreach ($serviceType as $m=>$n){?>
					<?php if($m == $v->customer_service_apply_type){?>
					<td style="padding-top:18px;"><?php echo $n?></td>
					<?php }?>
					<?php }?>
					<td style="padding-top:18px;"><?php echo $v->reason?></td>
					<td style="padding-top:18px;"><?php echo $v->customer_service_apply_timestamp?></td>
					<?php foreach ($serviceStatus as $m=>$n){?>
					<?php if($m == $v->status){?>
					<td style="padding-top:18px;"><?php echo $n?></td>
					<?php }?>
					<?php }?>
					<td><a href="<?php echo $this->url('admin-service' , array('action' => 'detail','id'=>$v->id)); ?>" class="btn btn-info">查看</a></td>
				</tr>
			<?php }?>
		    <?php endif;?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-service','condition'=>$condition));?>       </div>
</div>
<script type="text/javascript">
var start ={
		dateCell:"#start_time",
		format:"YYYY-MM-DD hh:mm:ss",
		isinitVal:false,
		isTime:true, 
		maxDate: jeDate.now(0),
		minDate:"1970-01-01 00:00:00",
		choosefun: function(datas){
			end.minDate = datas;
	    }
	};
var end ={
	dateCell:"#end_time",
	format:"YYYY-MM-DD hh:mm:ss",
	isinitVal:false,
	isTime:true,
	minDate:"1970-01-01 00:00:00",
	maxDate: jeDate.now(0),
	choosefun: function(datas){
        start.maxDate = datas;
    }
}
jeDate(start);
jeDate(end);
</script>