<script src="<?php echo $this->basePath();?>/js/admin/jedate.min.js"></script>
<style>
    .fl{
        float:left;
    }
	.dataTables_info{
		display:none;
	}
	.dataTables_paginate{
		display: none;
	}
	.bc-1{display: none;}
	.col-sm-5{display: none;}
	.col-sm-7{display:none;}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
        <a href="<?php echo $this->url('admin-service' , array('action' => 'marketFeedback')); ?>">售后留言管理/ <a href="">市场反馈</a>
		</h3>
	</div>
	
	<div class="panel-body">
	    <div class="fl" >
            <a class="btn btn-info fl " href="<?php echo $this->url('admin-service' , array('action' => 'marketFeedbackAdd'));?>">新增市场反馈</a>
        </div>
    	<div class="" style="float:right;">
            <form class="form-horizontal" action="<?php $this->url('admin-service' , array('action' => 'marketFeedback')) ?>" method="get" style="float: left; margin-left: 20px;">
            <span style="font-weight: bold; font-size: 14px;">提交日期：</span>
            <input type="text"  style="line-height: 22px"  name="start_time" readonly id="start_time" class="datainp" placeholder="请选择" value="<?php echo isset($start_time) ? $start_time :''?>"/>
            <span style="font-weight: bold; font-size: 14px;">到：</span>
			<input type="text"  style="line-height: 22px"  name="end_time"  readonly id="end_time"  class="datainp" placeholder="请选择" value="<?php echo isset($end_time) ? $end_time :''?>"/>
			<span style="font-weight: bold; font-size: 14px;"> 关键词 :</span>
			<input type="text" name="keyword" value="<?php echo isset($keyword) ? $keyword :''?>" placeholder="请输入企业名称搜索" style="line-height: 26px" >
			<select style="padding: 5px" name="status">
			     <option value="0">全部状态</option>
			     <?php foreach ($marketFeedbackStatus as $k=>$v){?>
			     <option value="<?php echo $k?>" <?php echo isset($status)&&$k==$status ? "selected" : ''?>><?php echo $v?></option>
			     <?php }?>
			</select>
			<input type="submit"  value="搜索" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
		    </form>
    	</div>
    	<div style="clear:both;"></div>
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>反馈时间</th>
					<th>企业名称</th>
					<th>市场反馈内容</th>
					<th>供应商回复</th>
					<th>回复状态</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			<?php if(!empty($marketFeedback)){?>
			<?php foreach ($marketFeedback as $k=>$v){?>
                <tr class="tr_list" valign="middle">
					<td style="padding-top:18px;"><?php echo $v->timestamp?></td>
					<td style="padding-top:18px;"><?php echo $v->company_name?></td>
					<td style="padding-top:18px;"><?php echo $v->content?></td>
					<td style="padding-top:18px;"><?php echo $v->response?></td>
					<?php foreach ($marketFeedbackStatus as $m=>$n){?>
					<?php if($m==$v->status){?>
					<td style="padding-top:18px;"><?php echo $n?></td>
					<?php }?>
					<?php }?>
					<?php echo $v->file ? '<td><a href="'.ROOT_PATH . UPLOAD_PATH. $v->file.'" class="btn btn-info">查看附件</a></td>' : '<td>没有附件</td>'?>
				</tr>
			<?php }?>
		    <?php }?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-service','condition'=>$condition));?>       
        </div>
</div>
<script type="text/javascript">
var start ={
		dateCell:"#start_time",
		format:"YYYY-MM-DD hh:mm:ss",
		isinitVal:false,
		isTime:true, 
		maxDate: jeDate.now(0),
		minDate:"1970-01-01 00:00:00",
		choosefun: function(datas){
			end.minDate = datas;
	    }
	};
var end ={
	dateCell:"#end_time",
	format:"YYYY-MM-DD hh:mm:ss",
	isinitVal:false,
	isTime:true,
	minDate:"1970-01-01 00:00:00",
	maxDate: jeDate.now(0),
	choosefun: function(datas){
        start.maxDate = datas;
    }
}
jeDate(start);
jeDate(end);
</script>