<style>
    .tl{text-align: right;}
    .main-nody{padding:5px 20px 0 20px;}
    .main-nody h5{float: left;}
    .tp{margin-top: 30px;}
    .bc-1{display: none;}
    .fl{float: left;}
    .supplier-tr{
             display:block;
        	 width:180px;
             border-bottom:1px solid grey;
             height:25px;
             line-height:25px;        
        }
</style>
<div class="panel panel-default">
   <div class="panel-heading">
       <div calss="row">
           <div class="col-sm-6">
              <a href="<?php echo $this->url('admin-service' , array('action' => 'index')); ?>">售后留言管理 / <a href="<?php echo $this->url('admin-service' , array('action' => 'marketFeedback')); ?>">市场反馈</a> / <a href="">新增市场反馈</a>
           </div>
       </div>
   </div>
    <div class="pannel-body main-nody">
        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-lg-12">
                <h5>新增市场反馈</h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4" >
                    <tbody>
                        <tr>
                            <td width="10%">选择供应商</td>
                            <td>
                                <input type="text" id="user_name" value="<?php echo isset($user->company_name) && $user ? $user->company_name : ''?>"    style="padding:5px;width:183px;" oninput="selectUser(this.value)" autocomplete="off" >
                                <input type="hidden" name="user_id" id="user_id" value="<?php echo isset($user->id) ? $user->id : ''?>"/>
                                <table id="supplier-table" style="border-left:1px solid grey;border-right:1px solid grey;position:absolute;background:white">
                                </table>
                                <span style="color:grey">输入供应商名称</span>
                           </td>
                        </tr>
                        <tr width="10%">
                            <td>市场反馈内容</td>
                            <td>
                                <textarea height="26px" cols="100%" name="content" required></textarea>
                            </td>
                        </tr>
                        <tr width="10%">
                            <td>上传附件</td>
                            <td>
                                <!-- <input type="button" value="选择附件" name="" class="btn btn-info"> -->
                                <input type="file"  name="file">
                                <span>请上传2M内的excel文档</span>
                                <!-- <input type="file"  name="" style="visibility: hidden"> -->
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div class="row tp">
            <div class="col-lg-12">
                <h5></h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4">
                    <tbody>
                        <tr>
                            <td>
                                <input type="submit" name="submit" value="提交" class="btn btn-info" >
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        </form>
    </div>
</div>
<script type="text/javascript">
//选择供应商
function selectUser(t){
	var keyword = t;
	console.log(keyword);
	if(keyword)
	{
		$.ajax({
		    url:'<?php echo $this->url('admin-goods',array('action'=>'selectUser'))?>',
		    type:'post',
		    data:{'keyword':keyword},
		    dataType:'json',
		    success:function(data){
		    	console.log(data);
			    if(data.code == '1'){
				    var html = '';
			    	$.each(data.users,function(i,v){
				    	html += "<tr class='supplier-tr'><td><a class='supplier-tr'  onclick='selectOneUser(this)'  user_id='"+v.id+"'>"+v.company_name+"</a></td></tr>";
					});
			    	$('#supplier-table').empty();
			    	$('#supplier-table').append(html)    
				}
			},
		});
	}
}

function selectOneUser(obj)
{
   var user_id = $(obj).attr('user_id');
   var user_name = $(obj).html();
   $("#user_name").val(user_name);
   $("#user_id").val(user_id);
   $("#supplier-table").empty();
}

$('form').submit(function(){
	var user_id = $('#user_id').val();
	if(!user_id)
	{
		alert('请选择供应商');
		return false;
	}
})
</script>