<script src="<?php echo $this->basePath();?>/js/admin/jedate.min.js"></script>
<style>
	.dataTables_info{
		display:none;
	}
	.dataTables_paginate{
		display: none;
	}
	.bc-1{display: none;}
	.col-sm-5{display: none;}
	.col-sm-7{display:none;}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
        <a href="<?php echo $this->url('admin-service' , array('action' => 'index')); ?>">售后留言管理/ <a href="">售后统计</a>
		</h3>
	</div>
	
	<div class="panel-body">
    	<div class="" style="float:right;">
            <form class="form-horizontal" action="<?php $this->url('admin-service' , array('action' => 'statistic')) ?>" method="get" style="float: left; margin-left: 20px;">
            <span style="font-weight: bold; font-size: 14px;">提交日期：</span>
            <input type="text"  style="line-height: 22px"  name="start_time" readonly id="start_time" class="datainp" placeholder="请选择" value="<?php echo isset($start_time) ? $start_time :''?>"/>
            <span style="font-weight: bold; font-size: 14px;">到：</span>
			<input type="text"  style="line-height: 22px"  name="end_time"  readonly id="end_time"  class="datainp" placeholder="请选择" value="<?php echo isset($end_time) ? $end_time :''?>"/>
			<input type="submit"  name="submit" value="搜索" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
			<input type="submit"  name="prev"  value="上个月" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
			<input type="submit"  name="next" value="下个月" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
		    </form>
    	</div>
    	<div style="clear:both;"></div>
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>问题类型</th>
					<th>总订单数</th>
					<th>问题订单数</th>
					<th>投诉比例（%）</th>
				</tr>
			</thead>
			<tbody>
                <tr class="tr_list" valign="middle">
					<td style="padding-top:18px;">商品质量</td>
					<td style="padding-top:18px;"><?php echo $count_order?></td>
					<td style="padding-top:18px;"><?php echo $count_quality?></td>
					<td style="padding-top:18px;"><?php echo $count_order > 0 ?  number_format($count_quality/$count_order*100,2)."%" : '0.0%'?></td>
				</tr>
				<tr class="tr_list" valign="middle">
					<td style="padding-top:18px;">物流问题</td>
					<td style="padding-top:18px;"><?php echo $count_order?></td>
					<td style="padding-top:18px;"><?php echo $count_logistics?></td>
					<td style="padding-top:18px;"><?php echo $count_order > 0 ? number_format($count_logistics/$count_order*100,2)."%" : '0.0%'?></td>
				</tr>
				<tr class="tr_list" valign="middle">
					<td style="padding-top:18px;">其他问题</td>
					<td style="padding-top:18px;"><?php echo $count_order?></td>
					<td style="padding-top:18px;"><?php echo $count_other?></td>
					<td style="padding-top:18px;"><?php echo $count_order > 0 ? number_format($count_other/$count_order*100,2)."%" : '0.0%'?></td>
				</tr>
                <tr class="tr_list" valign="middle">
					<td style="padding-top:18px;">合计</td>
					<td style="padding-top:18px;"><?php echo $count_order?></td>
					<td style="padding-top:18px;"><?php echo $count_quality+$count_logistics+$count_other?></td>
					<td style="padding-top:18px;"><?php echo $count_order > 0 ? number_format(($count_quality+$count_logistics+$count_other)/$count_order*100,2)."%" : '0.0%'?></td>
				</tr>
            </tbody>
		</table>
    </div>
</div>
<script type="text/javascript">
var start ={
		dateCell:"#start_time",
		format:"YYYY-MM-DD hh:mm:ss",
		isinitVal:false,
		isTime:true, 
		maxDate: jeDate.now(0),
		minDate:"1970-01-01 00:00:00",
		choosefun: function(datas){
			end.minDate = datas;
	    }
	};
var end ={
	dateCell:"#end_time",
	format:"YYYY-MM-DD hh:mm:ss",
	isinitVal:false,
	isTime:true,
	minDate:"1970-01-01 00:00:00",
	maxDate: jeDate.now(0),
	choosefun: function(datas){
        start.maxDate = datas;
    }
}
jeDate(start);
jeDate(end);
</script>