<form action="" method="post" enctype="multipart/form-data">
    <input type="hidden" name="leadExcel" value="true">
    <table align="center" width="90%" border="0">
    <tr>
       <td width='180px'>
        <input type="radio" name="type" value="1" checked>盆栽
        <input type="radio" name="type" value="2">资材
       </td>
       <td>
        <input type="file" name="inputExcel">
       </td>
    </tr>
    <tr>
       <td>
       <input type="submit" value="导入数据">
       </td>
       <td>
       </td>
    </tr>
    </table>
</form>