        <script type="text/javascript">
        $(function(){
            $('.user_center ul li').click(function(){
                $(this).addClass('on').siblings().removeClass('on');
            })
        })
        </script>
                <div class="user_content_right">
                    <h2>修改密码</h2>
                    <div class="user_message micronesia">
                        <from>
                            <ul>
                                <li>
                                    <div class="label">旧密码：</div>
                                    <div>
                                        <input type="password" name="oldpw"  value="">
                                    </div>
                                </li>
                                <li>
                                    <div class="label">新密码：</div>
                                    <div>
                                        <input type="password" name="newpw" value="">
                                    </div>
                                </li>
                                <li>
                                    <div class="label">重新输入密码：</div>
                                    <div>
                                        <input type="password" name="repw" value="">
                                    </div>
                                </li>
                                <li>
                                    <div class="label">&#12288;</div>
                                    <div class="sub">
                                        <a class="btn_sub">提交</a>
                                    </div>
                                </li>
                            </ul>
                        </form>
                        <!-- 遮罩层 -->
                        <div class="page_strong top2"></div>
                        <!-- 弹窗 -->
                        <div class="prompt dialog">
                          <h3 class="pt15"  id="dialogTitle">提交成功</h3>
                          <p class="pt5" id="dialogdesc">您的留言已提交成功，我们将尽快回复</p>  
                          <span class="only_sure">确定</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <script type="text/javascript">
        $(".only_sure").click(function(){
        	$('.page_strong').hide();
            $('.prompt').hide();
//             window.location.reload();
        })
        $(".btn_sub").click(function(){
            var oldpw = $("input[name='oldpw']").val();
            var newpw = $("input[name='newpw']").val();
            if($.isEmptyObject(oldpw)){
            	$('#dialogTitle').html('提交失败');
                $('#dialogdesc').html('旧密码不能为空');
                $('.page_strong').show();
                $('.prompt').show();
                return false;
                }
            if($.isEmptyObject(newpw)){
            	$('#dialogTitle').html('提交失败');
                $('#dialogdesc').html('新密码不能为空');
                $('.page_strong').show();
                $('.prompt').show();
                return false;
                }
            if(newpw != $("input[name='repw']").val()){
            	$('#dialogTitle').html('提交失败');
                $('#dialogdesc').html('两次密码不一致');
                $('.page_strong').show();
                $('.prompt').show();
                return false;
                }

            if(newpw.length < 6 || newpw.length > 20)
            {
            	$('#dialogTitle').html('提交失败');
                $('#dialogdesc').html('请输入6到20位密码');
                $('.page_strong').show();
                $('.prompt').show();
                 return false;
            }
            
            var json = new Object();
            json.n = "UserUpdatePassword";
            json.q = new Object();
            json.q.password = $.md5(oldpw);
            json.q.passwordNew = $.md5(newpw);
            $.post('<?php echo $this->url('index' , array('controller' => 'index' , 'action' => 'getJson'))?>' ,  {request: json} , function(data){
                if(data.q.s=='0')
          	    {
                	$('#dialogTitle').html('修改成功');
                    $('#dialogdesc').html('密码修改成功,重新登录');
                    $('.page_strong').show();
                    $('.prompt').show();
                    $(".only_sure").click(function(){
                    	window.location.href='<?php echo $this->url('index',array('controller'=>'login','action'=>'logout'));?>';
                    })
                    
                }
                else
                {
                	$('#dialogTitle').html('提交失败');
                    $('#dialogdesc').html(data.q.d);
                    $('.page_strong').show();
                    $('.prompt').show();
                }
            },"json");
            });
        </script>