        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/admin/jq_area.js') ?>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/admin/region.js') ?>
        <script type="text/javascript">
        $(function(){
            $('.user_center ul li').click(function(){
                $(this).addClass('on').siblings().removeClass('on');
            })
        })
        </script>
                <div class="user_content_right">
                    <h2>会员信息</h2>
                    <div class="user_message">
                        <form method="post" action="" id="form">
                            <ul>
                                <li>
                                    <div class="label">企业名称：</div>
                                    <div>
                                        <input type="text" name="company_name" class="w270" value="<?php echo isset($user->company_name) ? $user->company_name : ''?>" required>
                                        <input type="hidden" name="id" value="<?php echo isset($user->id) ? $user->id : ''?>"/>
                                    </div>
                                </li>
                                <li>
                                    <div class="label">联系人：</div>
                                    <div>
                                        <input type="text" name="contacts_name" value="<?php echo isset($user->contacts_name) ? $user->contacts_name : ''?>" required>
                                    </div>
                                </li>
                                <li>
                                    <div class="label">联系电话：</div>
                                    <div>
                                        <input type="tel" name="mobile" value="<?php echo isset($user->mobile) ? substr($user->mobile, 0 , 3).'****'.substr($user->mobile, -4) : ''?>" disabled>
                                    </div>
                                </li>
                                <li>
                                    <div class="label">企业传真：</div>
                                    <div>
                                        <input type="text" name="fax"  value="<?php echo isset($user->fax) ? $user->fax : ''?>">
                                    </div>
                                </li>
                                <li>
                                    <div class="label">QQ号码：</div>
                                    <div>
                                        <input type="text" name="qq"  value="<?php echo isset($user->qq) ? $user->qq : ''?>">
                                    </div>
                                </li>
                                <li>
                                    <div class="label">E-mail：</div>
                                    <div>
                                        <input type="email" name="email" value="<?php echo isset($user->email) ? $user->email : ''?>" required>
                                    </div>
                                </li>
                                <li class="clearfix">
                                    <div class="label">所在区域：</div>
                                    <div class="classify">
                                        <span id="area">
                                            <div class="select_out">
                                            <select id="province" name="province" style="width: 100px;"></select>
                                            </div>
                                            <div class="select_out">
                                            <select id="city" name="city" style="width: 100px;"></select>
                                            </div>
                                            <select id="county" name="county" style="display:none;width: 100px;"></select>
        							    </span>
                                    </div>
                                </li>
                                <li>
                                    <div class="label">详细地址：</div>
                                    <div>
                                        <input type="text" name="address" class="address" value="<?php echo isset($user->address) ? $user->address : ''?>" required>
                                    </div>
                                </li>
                                <li>
                                    <div class="label">企业描述：</div>
                                    <div>
                                        <textarea name="description" cols="20" rows="5" placeholder="describe"><?php echo isset($user->description) ? $user->description : ''?></textarea>
                                    </div>
                                </li>
                                <li>
                                    <div class="label">&#12288;</div>
                                    <div class="sub">
                                        <a class="btn_sub">提交</a>
                                    </div>
                                </li>
                            </ul>
                        </form>
                        <!-- 遮罩层 -->
                        <div class="page_strong top2"></div>
                        <!-- 弹窗 -->
                        <div class="prompt dialog">
                          <h3 class="pt15"  id="dialogTitle">提交失败</h3>
                          <p class="pt5" id="dialogdesc">您的留言已提交成功，我们将尽快回复</p>  
                          <span class="only_sure">确定</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <script>
    $("#area").area({
    	provinceId:"#province",cityId:"#city",countyId:"#county",
        cache: region,
        p_id:<?php echo isset($address['province']['id']) ? $address['province']['id'] : 440000;?>,
        ci_id:<?php echo isset($address['city']['id']) ? $address['city']['id'] : 440100;?>,
        co_id: <?php echo isset($address['county']['id']) ? $address['county']['id'] : 440103;?>
    });
    $(".btn_sub").click(function(){
        if(check())
        {
        	$("#form").submit();
        }
    });

    $('.only_sure').click(function(){
        $('.page_strong').hide();
        $('.prompt').hide();
    })
    
    $(document).keydown(function(evt){
    	var evt = event || window.event || arguments.callee.caller.arguments[0];
    	if(evt && evt.keyCode==13){
    		if(check())
    		{
    			$("#form").submit();
            }
        }
    })
    
    function check()
    {
        var error = '';
        if($.trim($("input[name='company_name']").val()).length <= 0)
        {
        	error = "企业名称必填" ;
        }
        if($.trim($("input[name='contacts_name']").val()).length < 3 || $.trim($("input[name='contacts_name']").val()).length > 50)
        {
        	error = "联系人长度为3-50";
        }
        if($.trim($("input[name='address']").val()).length < 3 || $.trim($("input[name='contacts_name']").val()).length > 50)
        {
        	error = "详细地址长度为3-50";
        }
/*         if(!isMobile($.trim($("input[name='mobile']").val())))
        {
        	error = "联系电话错误";
        } */
        if(!isEmail($.trim($("input[name='email']").val())))
        {
        	error = "邮箱错误";
        }
        if($.trim($("input[name='qq']").val()).length != 0 && $.trim($("input[name='qq']").val()).search(/^[1-9]\d{4,8}$/) == -1)
        {
        	error = "qq号错误";
        }
        if($.trim($("input[name='fax']").val()).length != 0 && $.trim($("input[name='fax']").val()).search(/^(([0\+]\d{2,3}-)?(0\d{2,3})-)(\d{7,8})(-(\d{3,}))?$/) == -1)
        {
        	error = "传真格式错误";
        }

        if(error)
        {
            $('.page_strong').show();
            $('.prompt').show();
            $('#dialogdesc').html(error);
            return false;   
        }
        return true;
    }
    </script>