<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,inital-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-status-bar-style" content="block" />
    <meta name="format-detection" content="telephone=no" />
    <title>订单填写</title>
    <!-- 公用样式 -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/kuaiyao/common.css">
    <!-- 购买产品相关页面样式 -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/kuaiyao/commodity.css">
    <!--只兼容移动端，所以直接使用jQuery 2.1.4-->
    <script type="text/javascript" src="<?php echo $this->basePath();?>/lib/jquery.2.1.4.min.js"></script>
    <!--调用微信js-->
    <script type="text/javascript" src="<?php echo $this->basePath();?>/lib/jweixin-1.0.0.js"></script>
	<!-- 地址选择 -->
	<?php echo $this->headScript()->prependFile($this->basePath() . '/js/jq_area.js') ?>
	<?php echo $this->headScript()->prependFile($this->basePath() . '/js/region.js') ?>
</head>
<body>
	<form action="<?php echo $this->url('index',array('controller'=>'commodity','action'=>'orderSubmit'))?>" method="post" onsubmit="return check()">
		<div class="indent bg_white mt10 pl15 pr15 pb15">
		<!--从主名片提取-->
				<div class="pt15">
					<span class="name">
						<input type="text" name="name" value="" maxlength="8" placeholder="请输入收货人姓名">

					</span>
					<span class="phone">
						<input type="text" id="tel" value="" name="mobile" maxlength="11" placeholder="请输入联系电话">
					</span>
				</div>    
				<p class="site pb15 mr20">
					<div class="mb10">
					<label class="">地区选择：</label>
						<span id="area">

	                        <select class="form-control" id="province"
									name="province_id">
							</select>
	                        <select
								class="form-control" id="city" name="city_id"
								></select>
	                        <select class="form-control"
									id="county" name="county"></select>
	                    </span>
                    </div>
					<label>详细地址：</label>
					<span>
						<input type="text" class="street" value="" name="street" placeholder="请输入详细地址">
					</span>
				</p>
		</div>

		<div class="commodity_price bg_white mt10  w pt15 pb15 d_ib">
			<img class="fl mr15 pl15" src="<?php echo $this->basePath();?>/images/product.png" alt="" />
			<div class="fl">
				<h3 class="lh30 f120pct">个人快摇名片</h3>
				<p class="lh30">原价购买：
					<span class="f_color_red">￥198</span>
					<input type="hidden" name="price" value="198" />
				</p>
			</div>
			<div class="compile fr pr15">
				<span class="count">
					<span class="ride">×</span>
					<a href="javascript:;" class="subtract dn"></a>
					<a href="javascript:;" class="number pl5">1</a>
					<input class="num" name="number" type="hidden" value="1"/>
					<a href="javascript:;" class="add dn"></a>
				</span>
				<a href="javascript:;" class="redact ml5">编辑</a>
			</div>
		</div>
		<div class="clear"></div>

		<div class="bg_white mt10  p15">
				使用推荐码:<span class="code_num"><font id="code_num"></font></span>
				<input class="bn" type="text" value="" name="code">
		</div>

		<div class="bg_white mt10 pt15 pb15 w d_ib">
			<span class="fl pl15">支付方式</span>
			<span class="fr ti25 pr15 icon_wx">微信支付</span>
			<input type="hidden" name="type" value="3"/>
		</div>

		
		<div class="bg_white mt10 p15 invoice">
			<p><span></span>开具发票</p>
			<input type="hidden" name="invoice_status" class="invoice_status" value=""/>
			<div class="s_type dn pt10">
				<div class="mb10">
				   <label for="" class="mr10">类型</label> 
				   <input class="individual mr5" name="invoice_type" type="radio" value="1" checked="checked" />个人
				   <input class="ml20 corporate mr5" name="invoice_type" type="radio" value="2" />公司
			   </div>
			   <div>
				   <label for="" class="mr10">抬头</label>
				   <input class="btn_o w8 text  pt5 pb5" name="invoice_name" type="text" placeholder="请输入个人名称"/>
			   </div>
			</div>
		</div>
		<div class="mt50"></div>
		<div class="bottom">
            <div class="fl cost">价格：￥
				<span>198</span>
				<input type="hidden" name="address_id" value="<?php echo $carte['id']?>"/>
				<input type="hidden" name="address_name" value="<?php echo $carte['name']?>"/>
				<input type="hidden" name="address_telephone" value="<?php echo $carte['telephone']?>"/>
				<input type="hidden" name="address_street" value="<?php echo $carte['street']?>"/>
				<input type="hidden" name="region_id" value="<?php echo $carte['region_id']?>"/>
				<input type="hidden" name="user_id" value="<?php echo $user_id;?>"/>
			</div>
            <input class="fl pay bn" type="submit" value="提交订单"/>
        </div>
    </form>
    <script type="text/javascript">
    $(function(){
        // 开发票
        $(".invoice p span").click(function(){
        if($(this).attr('class')=='check'){
                $(this).removeClass('check');
                $(".s_type").addClass('dn');
				$('.invoice_status').val(2);
            }else{
                $(this).addClass('check');
                $(".s_type").removeClass("dn");
				$('.invoice_status').val(1);
            }
        })
        // 选择个人公司
        var val=$('input:radio[name="sex"]:checked').val();
        $(".corporate").click(function(){
            if(val==null){
                $(".text").attr("placeholder","请输入公司名称")
            }        
         });
         $(".individual").click(function(){
            if(val==null){
                $(".text").attr("placeholder","请输入个人名称")
            }        
         });
     });
    // 名称为空阻止提交
    $(".pay").click(function(){
    	if($(".name input").val() == '') {
            alert('请输入姓名');
            return false;
  		}
	 	var re=/^0?1[3|4|5|8][0-9]\d{8}$/;
	 	var tel = $("#tel").val();
	 	if(tel == ''){
	 		alert('请输入手机号码');
            return false;
	 	}else if(!re.test(tel)){
	 	   	alert('请输入正确的手机号码。');      
	 	   	return false;  
	 	}
	 	if($(".street").val() == ''){
	 		alert('请输入详细地址');
	 		return false;  
	 	}
        if ($(".s_type").css('display')=='block' && $(".text").val() == '') {
            alert('名称不能为空');
            return false;
  		}
    });

    // 切换完成编辑
    $(".redact").click(function(){
        if($(this).html()=="编辑"){
            $(this).html("完成");
            $(".ride").addClass("dn");
            $(".subtract,.add").removeClass("dn");
        }else{
            $(this).html("编辑");
            $(".ride").removeClass("dn");
             $(".subtract,.add").addClass("dn");
        }
    })
    $(document).ready(function(){
	    // 数量价格加减
	    $(".add").click(function(){
	        var n=$(".number").html();//数量
	       
	        var c=$(".cost span").html();//价格
	        var number=parseInt(n)+1;
	        var cost=parseInt(c)+198;
	        $(".number").html(number);
	        $(".cost span").html(cost);
	        $(".cost input").val(cost);
	        $(".count input").val(number);
			
	    });
	    $(".subtract").click(function(){
	        var n=$(".number").html();//数量
	        var c=$(".cost span").html();//价格
	        var number=parseInt(n)-1;
	        var cost=parseInt(c)-198;
	        if(number<1){return};
	        if(number<$("#code_num").html()){
	        	alert("推荐码数量过多，请先删减推荐码");
	        	return

	        };
	        $(".number").html(number);
	        $(".cost span").html(cost);
	        $(".count input").val(number);
	    })
	    // 总价减去推荐码
		 $(".cost span").html($(".cost span").html()-$("#code_num").html()*30);
	});
	function num(){
		var num=$('.num').val();
		//alert(num);
		window.location.href="<?php echo $this->url('index',array('action'=>'ReferralCode'))?>?num="+num;
	}

	</script>
	<script>
		// 地址选择
		$(function(){
			$("#area").area({cache:region});
		});


	</script>
</body>