<!-- Responsive Table -->
<!-- Table exporting -->
<script type="text/javascript" src="<?php echo ROOT_PATH;?>lib/jquery-1.8.2.min.js"></script> 
<script type="text/javascript" src="<?php echo $this->basePath();?>/lib/jquery.2.1.4.min.js"></script>
<style type="text/css">
	.left{float:left;}
	.right{float:left;margin-left:100px;}
	.panel{height:200px;}
	.add{display:none;}
	.form-control{width:200px;}
	.col-sm-2{width:100px;}
	.ta_r{
		text-align: right;
	}
	.order a{
		border-radius: 5px;
    	border: 1px solid #c1c1c1;
    	color:#999;
    	padding:2px 5px;
    	margin-top: 10px;
    	display: inline-block;
	}
	.refund a{
		color:red;
	}
	.btn-info{
		margin-top:10px;
	}
	.hide{
		display:none;
	}
	.pane{
		height:50px;
	}
	.pice{
		display:block;
		margin-top:15px;
	}
	.text{
	float:left;
	margin-top:8px;
	margin-left:25px;
	}
	.btn{
	margin-top:2px;
	}
	.finish{
		margin-top:15px;
	}
</style>

<div class="panel panel-default">
	<div class="left">
		<table>
			<tr>
				<td class="ta_r pr5 pb5">订单号:</td>
				<td><?php echo $order['order_sn']?></td>
			</tr>
			<tr>
				<td valign="top" class="ta_r pr5 pb5">收货人:</td>
				<td>
					<?php echo isset($address['name']) ? $address['name'] : '';?><br>
					<?php echo isset($address['telephone']) ? $address['telephone']: '';?><br>
					<?php echo isset($address['address']) ? $address['address'] : '';?>
				</td>
			</tr>
			<tr>
				<td class="ta_r pr5 pb5">单价:</td>
				<td>￥<?php echo $order['price']?>&nbsp;&nbsp;&nbsp;&nbsp;件数：<?php echo $order['number'];?></td>
			</tr>
			<tr>
				<td class="ta_r pr5 pb5">推荐码:</td>
				<td><?php foreach($order['codes'] as $v){echo $v."<br>";}?></td>
			</tr>
			<tr>
				<td class="ta_r pr5 pb5">金额:</td>
				<td>
					￥<?php echo $order['total'];?>
				</td>
			</tr>
		</table>
	</div>
	<div class="right">
		<table>
			<tr>
				<td class="ta_r pr5 pb5">发票：</td>
				<td>
				<?php if(isset($order['invoice_status'])){?>
					<?php
						if($order['invoice_status']==2)
						{
							echo "无需发票";
						}
						else if($order['invoice_status']==1)
						{
							echo $order['invoice_name'];
						}
					?>
				<?php }?>
				</td>
			</tr>
			<tr>
				<td class="ta_r pr5 pb5">支付方式：</td>
				<td>
				<?php if(isset($order['payment'])){?>
					<?php 
						if($order['payment']==1){
							echo "支付宝";
						}else if($order['payment']==2){
							echo "微信支付";
						}else if($order['payment']==3){
							echo "银行卡";
						}
					?>
				<?php }?>
				</td>
			</tr>
			<tr>
				<td class="ta_r pr5 pb5">下单时间：</td>
				<td><?php echo $order['timestamp']?></td>
			</tr>
			<?php if($order['status']==3){?>
			<tr>
				<td class="ta_r pr5 pb5">处理订单时间:</td>
				<td><?php echo $order['shipping_time']?></td>
			</tr>
			<?php }else if($order['status']==4){?>
			<tr>
				<td class="ta_r pr5 pb5">申请退款时间：</td>
				<td><?php echo $order['timestamp_update']?></td>
			</tr>
			
			<?php }else if($order['status']==5){?>
			<tr>
				<td class="ta_r pr5 pb5">申请退款时间：</td>
				<td><?php echo $order['application_time']?></td>
			</tr>
			<tr>
				<td class="ta_r pr5 pb5">完成退款时间：</td>
				<td><?php echo $order['refund_time'];?></td>
			</tr>
			<?php }else if($order['status']==6){?>
			<tr>
				<td class="ta_r pr5 pb5">处理订单时间:</td>
				<td><?php echo $order['shipping_time']?></td>
			</tr>
			<tr>
				<td class="ta_r pr5 pb5">收货时间:</td>
				<td><?php echo $order['delivery_time']?></td>
			</tr>
			<?php }?>
		</table>
	</div>
</div>

<div class="panel panel-default">
	
	<div>
		<?php if($order['status']==1){?>
		<span class="status">订单状态：待付款</span>
		<?php }else if($order['status']==2){?>
		<div class="refund fr" ><span><a href="javascript:void(0);">申请退款</a></span></div>
		<span class="status">订单状态：待处理</span>
		<div class="order"><a href="javascript:void(0);">添加物流订单</a> </div><br>
		
		<!--处理订单-->
		<form action="<?php echo $this->url('admin-order',array('action'=>'update'))?>" method="post" class="add">
			<span style="display:none;" class="do mb10 d_ib">订单状态：处理中</span><br>
			<span class="fl mt5">运单：</span><div>
				<span><input type="text" required class="form-control fl mr10" name="shipping_company" placeholder="请选择快递公司"/></span>
				<span><input type="text" required class="form-control fl mr10" name="shipping_code" placeholder="请填写运单号"/></span>
			</div>
			<input type="hidden" name="order_id" value="<?php echo $order['id'];?>"/>
			<input type="submit" class='btn btn-info' value="确定"/>
		</form>
		<!--退款 -->
		<form action="<?php echo $this->url('admin-order',array('action'=>'details'))?>" style="display:none;" class="fund" name="refund" method="post">
			<span>订单状态：退款中</span><br>
			<span>退款方式：原路返回</span><br>
			<label class="col-sm-2 control-label"  for="field-1">退款原因：</label><span><input type="text" name="reason" required class="form-control fl mr10"/><input type="hidden" name="id" value="<?php echo $order['id']?>"/>
			<input type="submit" value="申请退款" class='btn btn-info'/></span>
		</form>
		<?php }else if($order['status']==3){?>
			<div>
				<span>订单状态：已发货</span>
				</br>
				
				<span class="pice">
					<font class="text">运单：</font>
					<input type="text" class="form-control fl mr10" value="<?php echo $order['shipping_company']?>" disabled>
					<input type="text" class="form-control fl mr10" disabled value="<?php echo $order['shipping_code']?>" />
					<a href="javascript:void(0);"class="btn btn-info" id="modify">编辑</a>
				</span>
				</br>
				
				<form action="<?php echo $this->url('admin-order',array('action'=>'modifyOrder'))?>" class="pane panel-pice hide" method="post">
					<span>
						<font class="text">运单：</font>
						<input type="text" required class="form-control fl mr10" name="company" value="<?php echo $order['shipping_company']?>" > 
						<input type="text" required class="form-control fl mr10" name="shipping_code" value="<?php echo $order['shipping_code']?>" />
					</span>
					<input type="hidden" name="id" value="<?php echo $order['id']?>"/>
					<input type="submit" class="btn btn-info" id="save" value="保存"/>
				</form><br>
				<span class="btn btn-info" onclick="delivery()">确认收货</span>
				<style type="text/css">
					
				</style>
			</div>
		
		<?php }else if($order['status']==4){?>
			<div>
				<span>订单状态：已提交退款</span><br>
				<span>退款原因：<?php echo $order['reason']?></span><br>
				<span>退款方式：原路返回</span><br>
				<span class="btn btn-info" onclick="refund()">已完成退款</span>
			</div>
		<?php }else if($order['status']==5){?>
			<div>
				<span>订单状态：已退款</span><br>
				<span>退款原因：<?php echo $order['reason']?></span><br>
				<span>退款方式：原路返回</span>
				
			</div>
		<?php }else if($order['status']==6){?>
			<div>
				<span>订单状态：已完成</span><br>
				<div class="finish">
					<font class="text">运单：</font>
					<span><input type="text" class="form-control fl mr10" value="<?php echo $order['shipping_company']?>" disabled>  <input type="text" class="form-control fl mr10" disabled value="<?php echo $order['shipping_code']?>" /></span><br>
				</div>
			</div>
		<?php }?>
	</div>
</div>
<script type="text/javascript">
	$('.order').click(function(){
		$(this).hide();
		$('.status').hide();
		$('.refund').hide();
		$('.add').show();
		$('.do').show();
		
	})
	
	$('.refund').click(function(){
		$(this).hide();
		$('.status').hide();
		$('.add').hide();
		$('.order').hide();
		$('.fund').show();
		
	})
	
	$('#modify').click(function(){
		$(this).parent("span").addClass("hide");
		$('#save').parent("form").removeClass("hide");
	});
	
	$('#save').click(function(){
		$(this).parent("span").addClass("hide");
		$('.modify').parent("span").removeClass("hide");
	});
	function delivery(){
		if(confirm("您确定要收货吗")){
			window.location="<?php echo $this->url('admin-order',array('action'=>'details','id'=>$order['id'],'other'=>6))?>";
		}

	}

	function refund(){
		if(confirm("您确定要退款吗")){
			window.location="<?php echo $this->url('admin-order',array('action'=>'details','id'=>$order['id'],'cid'=>5))?>";
		}

	}
	
</script>