
<div class="row">
    <form role="form" class="form-horizontal" action="<?php echo $this->url('admin-order', array('action' => 'shipping')) ?>" onsubmit="return checkSubmit()" method="post">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>发货</h3>
                </div>
                <div class="panel-body">          
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="field-4">货运单号：</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" placeholder="货运单号" value="<?php echo $info->shipping_code; ?>" name="shipping_code" required />
                        </div>
                    </div>
                    <div class="form-group-separator"></div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="field-4">备注：</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" placeholder="备注" value="<?php echo $info->shipping_content;?>" name="shipping_content">
                        </div>
                    </div>
                    <div class="form-group-separator"></div>
                    
                    <div class="form-group">
                        <label class="col-sm-2 control-label"></label>
                        
                        <div class="col-sm-10">
                            <input type="hidden" name="id" value="<?php echo $info->id;?>" />
<?php if ($info->shipping_time == '0000-00-00 00:00:00') {?>
                            <input type="submit" name="submit" value="提交" class="btn btn-success">
<?php }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
