<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>快摇名片，最具价值的商务人脉平台</title>
<meta name="Keywords" content="快摇名片，最具价值的商务人脉平台" />
<meta name="Description" content="快摇名片，最具价值的商务人脉平台" />
<link rel="stylesheet" type="text/css" href="css/style.css" />
<link rel="stylesheet" type="text/css" href="css/home.css" />
<link rel="stylesheet" type="text/css" href="css/animate.min.css" />
<script src="js/jquery.min.js"></script>
<script src="js/jquery.lightbox_me.js"></script>
<!--[if IE 6]>
	<script src="js/pngAlaph.js" ></script> 
	<script> 
		DD_belatedPNG.fix('img');
	</script> 
<![endif]-->
</head>

<body>
<!--  header -->
<div class="header">
  <div class="wrap">
       <p><a href="javascript:void(0);" class="pop-reg">注册</a> / <a class="pop-login" href="javascript:void(0);">登录</a></p>
       <h1><a href="#"><img src="images/logo.jpg" /></a></h1>
  </div>
</div>  
<!--  banner -->

<div class="banner">
  <div class="wrap">
      <dl>
         <dd><a href="#"><img src="images/banner_iphone.png" /></a></dd>
         <dd><a href="#"><img src="images/banner_android.png" /></a></dd>
         <dd><a href="javascript:void(0);" class="pop-reg"><img src="images/banner_reg.png" /></a></dd>
      </dl>
  </div>
</div>

<!--  main -->


<div class="main">
    <div class="wrap">
    <p class="dowebok-explain">您的浏览器不支持 CSS3 animate 属性，所以您看不到任何效果，请使用 Firefox、Chrome 或 IE10</p>
    
       <!--part_1-->
    
       <div class="part_1">
           <div class="part_dowebok part_1_img01">
              <img src="images/part_1_img01.png" />
              <div class="part_1_img01_01"><img src="images/part_1_img01_01.jpg" /></div>
              <div class="part_1_img01_02"><img src="images/part_1_img01_02.jpg" /></div>
           </div>
           <div class="part_dowebok part_1_img02"><img src="images/part_1_img02.png" /></div>
           <div class="part_dowebok part_1_img03"><img src="images/part_1_img03.png" /></div>
           <div class="part_dowebok part_1_img04">
             <dl>
               <dt class="part_dowebok">实用</dt>
               <dd class="dd_1 part_dowebok"><span class="col366afe">高</span>效的派发&nbsp;&nbsp;<span class="colf0b614">全</span>方位展示</dd>
               <dd class="dd_2 part_dowebok"><span class="col66cc99">便</span>捷的保存</dd>
             </dl>
           </div>
           <div class="part_dowebok part_1_img05"><img src="images/part_1_img05.png" /></div>
           <div class="part_dowebok part_1_img06"><img src="images/part_1_img06.png" /></div>
           <div class="part_dowebok part_1_img07">
             <img src="images/part_1_img07.png" />
             <div class="part_dowebok part_1_img07_01"><img src="images/part_1_img07_01.jpg" /></div>
           </div>
           
       </div>
       
       <!--part_2-->

       <div class="part_2">
           <div class="part_dowebok part_2_img01"><img src="images/part_2_img01.png" /></div>
           <div class="part_dowebok part_2_img02"><img src="images/part_2_img02.png" /></div>
           <div class="part_dowebok part_2_img03"><img src="images/part_2_img03.png" /></div>
           <div class="part_dowebok part_2_img04">
             <dl>
               <dt class="part_dowebok">连接</dt>
               <dd class="dd_1 part_dowebok"><span class="col366afe">真</span>实的用户信息&nbsp;&nbsp;<span class="colf0b614">诚</span>信的市场机制</dd>
               <dd class="dd_2 part_dowebok"><span class="col66cc99">安</span>全的交易环境</dd>
             </dl>
           </div>
           <div class="part_dowebok part_2_img05"><img src="images/part_2_img05.png" /></div>
       </div>
         
       <!--part_3-->

       <div class="part_3">
           <div class="part_dowebok part_3_img01"><img src="images/part_3_img01.png" /></div>
           <div class="part_dowebok part_3_img02"><img src="images/part_3_img02.png" /></div>
           <div class="part_dowebok part_3_img03"><img src="images/part_3_img03.png" /></div>
           <div class="part_dowebok part_3_img04">
             <dl>
               <dt class="part_dowebok">连接</dt>
               <dd class="dd_1 part_dowebok"><span class="col366afe">高</span>效的沟通桥梁 &nbsp;&nbsp;<span class="colf0b614">高</span>端的商务人脉</dd>
               <dd class="dd_2 part_dowebok"><span class="col66cc99">高</span>回报投资项目</dd>
             </dl>
           </div>
           <div class="part_dowebok part_3_img05"><img src="images/part_3_img05.png" /></div>
       </div>
         
       <!--part_4-->

       <div class="part_4">
           <div class="part_dowebok part_4_img01"><img src="images/part_4_img01.png" /></div>
           <div class="part_dowebok part_4_img02"><img src="images/part_4_img02.png" /></div>
           <div class="part_dowebok part_4_img03"><img src="images/part_4_img03.png" /></div>
           <div class="part_dowebok part_4_img04">
             <dl>
               <dt class="part_dowebok">商机</dt>
               <dd class="dd_1 part_dowebok">最<span class="col366afe">新</span>的行业动态&nbsp;&nbsp;最<span class="colf0b614">快</span>的商务响应</dd>
               <dd class="dd_2 part_dowebok">最<span class="col66cc99">准</span>的资源对接</dd>
             </dl>
           </div>
           <div class="part_4_img05"><img src="images/part_4_img05.png" /></div>
       </div>

       <!--part_5-->

       <div class="part_5">
           <div class="part_dowebok part_5_img01"><img src="images/part_5_img01.jpg" /></div>
           <div class="part_dowebok part_5_img02">
             <dl>
               <dd class="dd_1 part_dowebok">购买请关注</dd>
               <dd class="dd_2 part_dowebok">快摇名片，最具价值的商务人脉平台</dd>
               <dd class="dd_3 part_dowebok">微信公众号</dd>
             </dl>
           </div>
       </div>

    </div>
</div>

<!--  contact -->

<div class="contact">
   <div class="wrap">
     <dl>
       <dd><img src="images/contact_tel.jpg" />4008383765</dd>
       <dd><img src="images/contact_email.jpg"  /><a href="mailto:kefu@kuaiyao.name">kefu@kuaiyao.name</a></dd>
       <dd><img src="images/contact_qq.jpg"  /><a target="blank" href="http://wpa.qq.com/msgrd?V=3&uin=2334131157&Site=QQ交谈&Menu=yes"><img border="0" SRC="http://wpa.qq.com/pa?p=1:2334131157:7" alt="点击这里给我发消息"></a></dd>
     </dl>
   </div>
</div>

<!--  footer -->

<div class="footer">
   <div class="wrap">
     <p>Copyright © maimai.cn. All rights reserved. 京ICP证120264号 | 京公网安备11010802016426号</p>
   </div>
</div>
<form name="form" method="post" action="<?php echo $this->url('index',array('controller'=>'user','action'=>'resgiterCheck'));?>;">
<div id="sign_login" class="sign_up">
    <h2>用户登录</h2>
    <dl>
      <dt>账号：</dt>
      <dd><input type="text" class="text" placeholder="手机号码" name="mobile"  id="mobiles"/></dd>
      <dt>短信验证码：</dt>
      <dd><input type="button" class="submit hq_code" onclick="Checks()" value="获取验证码" id="values"/><input type="text" class="text code" placeholder="输入验证码" name="code"/></dd>
      <dd><input class="btn_reg pop-reg" type="button" value="注　册" /><input type="submit" class="submit" value="登　录" name="submit_login"/></dd>
    </dl>
    <a id="close_x" class="close" href="#"><img src="images/pop-up1_close.jpg" /></a>
</div>
</form>
<form name="form" method="post" action="<?php echo $this->url('index',array('controller'=>'user','action'=>'resgiterCheck'));?>;">
<div id="sign_reg" class="sign_up">
    <h2>快速注册</h2>
    <dl>
      <dt>账号：</dt>
      <dd><input type="text" class="text" placeholder="手机号码" name="mobile" id ="mobile"/></dd>
      <dt>短信验证码：</dt>
      <dd><input type="button" class="submit hq_code_cur" onclick="Check()" value="60秒" id="value" /><input type="text" class="text code" placeholder="输入验证码" name="code" /></dd>
      <dd><input type="submit" class="btn_reg submit_reg" value="注　册" name="submit_register"/></dd>
    </dl>
    <a id="close_x" class="close" href="#"><img src="images/pop-up1_close.jpg" /></a>
</div>
</form>

</body>
</html>
<script type="text/javascript">   
      var hasShow = false;  
      $(window).bind("scroll",function(){  

          var t = $(document).scrollTop();  
          if(t>120){  
              // 滚动高度超过120时，加载part_1
			  //alert(t)
			 $(".part_1").removeClass().addClass("part_1_animate");
			 
          }  
          if(t>700){  
              // 滚动高度超过700时，加载part_2  
			 $(".part_2").removeClass().addClass("part_2_animate");
			 
          }  
          if(t>1200){  
              // 滚动高度超过1200时，加载part_3 
			 $(".part_3").removeClass().addClass("part_3_animate");
			 
          }  		  
          if(t>1800){  
              // 滚动高度超过1800时，加载part_4
			 $(".part_4").removeClass().addClass("part_4_animate");
			 
          }  
          if(t>2100){  
              // 滚动高度超过2100时，加载part_4
			 $(".part_5").removeClass().addClass("part_5_animate");
			 
          }  

		  
      });  

$(function(){
	if($.browser.msie && $.browser.version < 10){
		//$('.dowebok-explain').show();
		$('.part_dowebok').css("opacity","1");
	}
	
	
	$('.pop-login').click(function(e) {
		$("#sign_login").lightbox_me({centered: true, preventScroll: true, onLoad: function() {
			$("#sign_login").find("input:first").focus();
		}});
		e.preventDefault();
	});
	
	$('.pop-reg').click(function(e) {
		$("#sign_reg").lightbox_me({centered: true, preventScroll: true, onLoad: function() {
			$("#sign_reg").find("input:first").focus();
		}});
		e.preventDefault();
	});
	
});
function Check()
{
	var id = $("#mobile").val();
	if(id=="")
		{
		  alert("手机号码不能为空");
		}
	   
		 
	$.post("<?php echo $this->url("index",array('action'=>'resgiterCheck','controller'=>'user'));?>", {register_code:id},
			function(data){
		 
		
		})
}
function Checks()
{
	
	var id = $("#mobiles").val();
	if(id=="")
		{
		  alert("手机号码不能为空");
		}
	$.post("<?php echo $this->url("index",array('action'=>'resgiterCheck','controller'=>'user'));?>", {login_code:id},
			function(data){
		
		})
}
</script>