<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width,inital-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-status-bar-style" content="block" />
	<meta name="fromat-detecition" content="telephone=no" />
<meta name="Keywords" content="<?php echo $title?>" />
<meta name="Description" content="<?php echo $title?>" />
<title><?php echo $title?></title>
<STYLE type="text/css">
*{
margin: 0px;padding: 0px;font-family: "Microsoft YaHei",微软雅黑,"SimSun","Microsoft JhengHei",华文细黑,STHeiti,MingLiu,tahoma,verdana,arial,sans-serif;-webkit-text-size-adjust: none;text-decoration: none;list-style-type: none;color:#010101;
}
img{
max-width:100%;
width:auto;
height:auto;
}
body{
padding:15px;
}
</STYLE>
</head>
<body>
<?php 

	echo $content;
?>

</body>
</html>