<script src="<?php echo $this->basePath();?>/js/admin/jedate.min.js"></script>
<style>
	.dataTables_info{
		display:none;
	}
	.dataTables_paginate{
		display: none;
	}
	.bc-1{display: none;}
	.col-sm-5{display: none;}
	.col-sm-7{display:none;}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
        <a href="<?php echo $this->url('admin-order' , array('action' => 'index')); ?>">订单管理 / <a href="<?php echo $this->url('admin-order' , array('action' => 'index' , 'type' => $type)); ?>"><?php if( $type == 1 ) { echo '盆栽订单管理';}elseif( $type == 2){ echo '资材订单管理'; }?></a>
		</h3>
	</div>
	
	<div class="panel-body">
    	<div class="" style="float:right;">
            <form class="form-horizontal" action="<?php $this->url('admin-order' , array('action' => 'index')) ?>" method="get" style="float: left; margin-left: 20px;">
            <span style="font-weight: bold; font-size: 14px;">下单日期：</span>
            <input class="datainp" id="start_time" type="text" placeholder="请选择"  readonly value="<?php echo isset($start_time) ? $start_time :''?>" name="start_time"  style="line-height:22px;width:160px">
            <span style="font-weight: bold; font-size: 14px;">到：</span>
			<input class="datainp" id="end_time" type="text" placeholder="请选择"  readonly value="<?php echo isset($end_time) ? $end_time :''?>" name="end_time"  style="line-height:22px;width:160px">
			<span style="font-weight: bold; font-size: 14px;"> 关键词 :</span>
			<input type="text" name="keyword" value="<?php echo isset($keyword) ? $keyword :''?>" placeholder="请输入订单号/企业名称搜索" style="line-height: 26px" >
			<select style="padding: 5px" name="status">
			     <option value="0">全部状态</option>
			     <?php foreach ($order_status as $key => $value): ?>
			     <option value="<?php echo $key; ?>" <?php if($key == $status) echo 'selected'; ?>><?php echo $value; ?></option>
			     <?php endforeach; ?>
			</select>
			<input type="submit"  value="搜索" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
		    </form>
    	</div>
    	<div style="clear:both;"></div>
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>订单编号</th>
					<th>企业名称</th>
					<th>下单时间</th>
					<th>总金额</th>
					<th>购买数量</th>
					<th>订单状态</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			     <?php foreach ($order_list as $value): ?>
                <tr class="tr_list" valign="middle">
					<td style="padding-top:18px;"><?php echo $value->order_sn; ?></td>
					<td style="padding-top:18px;"><?php echo $value->user_name; ?></td>
					<td style="padding-top:18px;"><?php echo $value->timestamp; ?></td>
					<td style="padding-top:18px;"><?php echo $value->total_cash; ?></td>
					<td style="padding-top:18px;"><?php echo $value->total_number; ?></td>
					<td style="padding-top:18px;"><?php echo $order_status[$value->status]; ?></td>
					<td><a href="<?php echo $this->url('admin-order' , array('action' => 'detail' , 'type' => $type ,'id' =>$value->id )); ?>" class="btn btn-info">查看</a></td>
				</tr>
				<?php endforeach; ?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-order','condition'=>$condition));?>       </div>
</div>

<script type="text/javascript">

var start ={
	dateCell:"#start_time",
	format:"YYYY-MM-DD hh:mm:ss",
	isinitVal:false,
	isTime:true, //isClear:false,
	maxDate: jeDate.now(0),
	minDate:"1970-01-01 00:00:00",
	choosefun: function(datas){
		end.minDate = datas;
    }
	//okfun:function(val){ alert(val)}
};
var end ={
	dateCell:"#end_time",
	format:"YYYY-MM-DD hh:mm:ss",
	isinitVal:false,
	isTime:true, //isClear:false,
	minDate:"1970-01-01 00:00:00",
	maxDate: jeDate.now(0),
	choosefun: function(datas){
        start.maxDate = datas;
    }
	
	//okfun:function(val){alert(val)}
}
jeDate(start);
jeDate(end);
</script>