<style type="text/css">
    .form-control{width:110px;}
    #form{float:left;margin-right:5px;}
    #sure{width:55px;float:left;margin-right:3px;background:#ccc;}
    .panel-heading{margin-left:100px;}
    .condition{margin-left:1170px;}
    .is_top{text-align: center;}
    .logo{width:60px;height: 60px;margin:0;float: left;border-radius: 10px;margin-right: 20px;}
    .info{float:left;}
    .coporation_info{width:250px;height:60px;float: left;}
    .condition{margin-left: 1400px;float: left;}
    .employ{display:block;float: left;}
</style>
<div class="panel panel-default">
    <div class="panel-body">
        <div class="" style="margin-bottom:50px;"></div>
        <div style="clear:both;"></div>
        <table class="table table-bordered table-striped" id="example-4">
            <thead>
            <tr>
                <th>ID</th>
                <th>姓名</th>
                <th>个人信息</th>
                <th>申请时间</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <?php if($card){?>
                    <tr>
                        <td><?php echo $card['id']?></td>
                        <td><?php echo $card['name']?></td>
                        <td>
                            <div class="card_info">
                                <img class="logo" src="<?php if(isset($card['head_icon'])){echo ROOT_PATH.UPLOAD_PATH.$card['head_icon'];}else{echo ROOT_PATH.'images/img_logo@2x.png';}?>"/>
                                <div class="coporation_info">
                                    <span>公司：<?php echo $card['company'];?></span><br>
                                    <span>职位：<?php echo $card['position'];?></span><br>
                                    <span>电话：<?php echo $card['mobile'];?></span>
                                </div>
                            </div>
                        </td>
                        <td><?php echo $card['timestamp']?></td>
                        <td>
                            <a href="<?php echo $this->url('admin-company',array('action'=>'pass','cid'=>$card['id']))?>">删除</a>
                        </td>
                    </tr>
            <?php }?>
            <?php foreach($info['list'] as $k=>$v){?>

                    <tr>
                        <td><?php echo $v['id']?></td>
                        <td><?php echo $v['name']?></td>
                        <td>
                            <div class="card_info">
                                <img class="logo" src="<?php if(isset($v['logo'])){echo ROOT_PATH.UPLOAD_PATH.$v['logo'];}else{echo ROOT_PATH.'images/img_logo@2x.png';}?>"/>
                                <div class="coporation_info">
                                    <span>公司：<?php echo $v['company'];?></span><br>
                                    <span>职位：<?php echo $v['position'];?></span><br>
                                    <span>电话：<?php echo $v['mobile'];?></span>
                                </div>
                            </div>
                        </td>
                        <td><?php echo $v['timestamp']?></td>
                        <td>
                           <a href="<?php echo $this->url('admin-company',array('action'=>'pass','cid'=>$v['id'],'other'=>$id))?>">删除</a>
                        </td>
                    </tr>

            <?php }?>
            </tbody>
        </table>
        <?php //echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-company','condition'=>$condition));?>       </div>
</div>
<script>
    function audit(val,id){
        var status=val;
        var id=id;
        $.post('<?php echo $this->url('admin-company',array('action'=>'updateStatu'))?>',{status:status,id:id},function(data){
            if(data==1){
                alert('审核成功');
                location.reload();
            }else{
                alert('审核失败');
            }
        });

    }
</script>
