<script>$(function(){showmenu();});</script>

        <div class="user_content_left">
            <div class="user_center">
                <h2>会员中心</h2>
                <ul>
                    <li class="on">我的商品</li>
                    <li>发布商品</li>
                    <li>资材订单</li>
                    <li>我的售后</li>
                    <li>市场反馈</li>
                    <li>对账单查询</li>
                    <li>会员信息</li>
                    <li>修改密码</li>
                </ul>
            </div>
            <div class="clear"></div>
            <div class="contact_us">
                <h2>联系我们</h2>
                <p>客服：400-0650-750</p>
                <p>传真：020-81413138</p>
                <p>E-mail : xiejing@ji-hong.cn</p>
                <p>http://gd.ji-hong.com.cn</p>
            </div>
        </div>