<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>问题详情</h3>
				<div class="panel-options">
					<a href="#" data-toggle="panel">
						<span class="collapse-icon">&ndash;</span>
						<span class="expand-icon">+</span>
					</a>
					<a href="#" data-toggle="remove"> &times; </a>
				</div>
			</div>
			<div class="panel-body">
				<div class="form-group">
					<label class="col-sm-2 control-label" for="field-1"></label>

					<div class="col-sm-10">
						<table style="border: 1px solid #E5E5E5; width: 470px;">
							<tr style="border-bottom: 1px solid #E5E5E5;">
								<th>用户(<?php echo isset($user_name[$id]['id_name']) ? $user_name[$id]['id_name'] : ''?>)</th>
								<th>管理员(回复)</th>
							</tr>
								<?php if($list){?>
								<?php foreach ($list as $v){?>
								<tr>
								<td><?php if(!$v->admin_id){?><textarea class="autogrow"
										name="content" disabled style="height: auto"><?php echo  $v->content; ?></textarea><?php }?></td>
								<td style="padding-left: 20px;"><?php if($v->admin_id){?><textarea
										class="autogrow" name="content" disabled style="height: auto"><?php echo  $v->content; ?></textarea><?php }?></td>
							</tr>
							    <?php }}?>
								</table>
					</div>
				</div>
				<div class="form-group-separator"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label" for="field-1">回复：</label>

					<div class="col-sm-10">
						<form class="form-horizontal"
							action="<?php echo $this->url('admin-other',array('action'=>'messageDetails'))?>"
							method="post">
							<textarea class="autogrow" style="width: 400px; height: 100px;"
								name="content"></textarea>
							<input type="hidden" name="id"
								value="<?php echo isset($id) ? $id : '';?>" />
							<input type="submit" class="btn btn-info" name="submit"
								style="margin-left: 30px" value="回复">
						</form>
					</div>
				</div>
				<div class="form-group-separator"></div>
			</div>
		</div>
	</div>