<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1,user-scalable=ture">
<script src="<?php echo $this->basePath();?>/pc/js/javascript.fullPage.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/pc/css/indexa.css" />
<!--  main -->
<style>
	.header_box{
		height: 0px;
	}
</style>
<div class="main">
		<!-- 第一个模块 -->
		<div class="section main_one">
			<img class="o_text" src="<?php echo $this->basePath();?>/pc/images/a_text1.png" alt=""/>
			<a href="<?php echo $this->url('index',array('controller'=>'index','action'=>'indexb'))?>" class="indexb">了解快摇名片设备 >></a>
		</div>
		<!-- 第二个模块 -->
		<div class="section main_two">
			<div class="two_bg"></div>
			<img  class="move" src="<?php echo $this->basePath();?>/pc/images/a_img2.gif" alt=""/>
		</div>
		<!-- 第三个模块 -->
		<div class="section main_three">
			<div class="t_content">
				<img class="t_text" src="<?php echo $this->basePath();?>/pc/images/a_text2.png" alt=""/>
				<img class="t_map" src="<?php echo $this->basePath();?>/pc/images/map.jpg" alt=""/>
				<img class="location" src="<?php echo $this->basePath();?>/pc/images/a_img3.png" alt=""/>
				<img class="t_phone" src="<?php echo $this->basePath();?>/pc/images/phone1.png" alt=""/>
			</div>
		</div>
		<!-- 第四个模块 -->
		<div class="section main_four">
		</div>
		<!-- 第五个模块 -->
		<div class="section main_five">
			<div class="f_content">
				<img class="f_phone" src="<?php echo $this->basePath();?>/pc/images/phone2.png" alt=""/>
				<img class="f_text" src="<?php echo $this->basePath();?>/pc/images/a_text3.jpg" alt=""/>
				<div class="f_re">
					<div class="f_map">
						<img class="coord1" src="<?php echo $this->basePath();?>/pc/images/coord1.png" alt=""/>
						<img class="coord2" src="<?php echo $this->basePath();?>/pc/images/coord2.png" alt=""/>
						<img class="coord3" src="<?php echo $this->basePath();?>/pc/images/coord3.png" alt=""/>
						<img class="coord4" src="<?php echo $this->basePath();?>/pc/images/coord4.png" alt=""/>
						<img class="coord5" src="<?php echo $this->basePath();?>/pc/images/coord5.png" alt=""/>
					</div>
				</div>
			</div>
			<p class="footer_text">Copyright © kuaiyao.name. All rights reserved. 广东近场网络科技有限公司. 粤ICP备15066271号-3</p>
		</div>
	</div>

	<script type="text/javascript">
			// 滚动切换
			fullpage.initialize('.main', {
				anchors: ['page1', 'page2', 'page3', 'page4','page5'],
				afterLoad: function(anchorLink, index){
					if(anchorLink == "page1"){ //第一个模块动画
						$(".main_one").animate({backgroundSize:'130%'},10000);
					}
					if(anchorLink == "page3"){//第三个模块动画
						$(".main_three .location").animate({bottom:'30%'},800)
												  .animate({bottom:'25%'},700)
												  .animate({bottom:'28%'},600)
												  .animate({bottom:'25%'},500)
												  .animate({bottom:'26%'},400)
												  .animate({bottom:'25%'},300);
					}

					if(anchorLink == "page5"){//第五个模块动画
						$(".main_five .coord1").animate({top:'19%'},500).animate({top:'25%'}, 500, 
							function(){
							$(".main_five .coord4").animate({top:'5%'},500).animate({top:'10%'},500, 
								function(){
								$(".main_five .coord3").animate({bottom:'45%'},500).animate({bottom:'39%'},500, 
									function(){
									$(".main_five .coord5").animate({bottom:'34%'},500).animate({bottom:'30%'},500,
										function(){
										$(".main_five .coord2").animate({top:'0px'},500).animate({top:'3%'},500);
									});
								});
							});
						});
					}

				},
				menu: '#menu',
				
			});
		
//读取cookies
function getCookie(name)
{
	var arr;
	var reg=new RegExp("(^| )"+name+"=([^;]*)(;|$)");
	
	if(arr=document.cookie.match(reg)){
		return unescape(arr[2]);
	}else{
		
		return null;
	} 
}
</script>