<!--  banner -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1,user-scalable=ture">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/pc/css/index.css" />
<!-- <div class="banner">
	<div class="wrap">
		<dl>
			<dd><a href="https://itunes.apple.com/cn/app/kuai-yao-ming-pian-zui-ju/id1028830091?mt=8"><img src="<?php echo $this->basePath();?>/pc/images/banner_iphone.png" /></a></dd>
			<dd><a href="http://www.kuaiyao.name/download/ky.apk"><img src="<?php echo $this->basePath();?>/pc/images/banner_android.png" /></a></dd>
			<dd class="buy" style="margin-top:7px;"><a href="javascript:void(0);" onclick="check_login();">立即购买</a></dd>
		</dl>
	</div>
</div> -->
<!--  main -->
<style>
	.header_box{
		height: 0px;
	}
</style>
<div class="main">
	<div class="main_bg"></div>
	<div class="content">
		<!-- 联系方式 -->
		<div class="h_contact">
			<ul>
				<li><a target="blank" href="tencent://message/?uin=3209147449&Site=www.luoxiao123.cn&Menu=yes"><img src="<?php echo $this->basePath();?>/pc/images/QQicon.png" alt="" /><span>3209147449</span></a></li>
				<li><a href="javascript:void(0)"><img src="<?php echo $this->basePath();?>/pc/images/E-mailicon.png" alt="" /><span>kefu@kuaiyao.name</span></a></li>
				<li class="contact_last"><a href="javascript:void(0)"><img src="<?php echo $this->basePath();?>/pc/images/phoneicon.png" alt="" /><span>4008383765</span></a></li>
			</ul>
		</div>
		<div class="clear"></div>
		<!-- 中间文字 -->
		<div class="img_text">
			<img src="<?php echo $this->basePath();?>/pc/images/home_text.png" alt="">
			
		</div>
		<div class="play">
			<a href="javascript:;"><img src="<?php echo $this->basePath();?>/pc/images/bofang.png" alt=""></a>
		</div>
		<!-- 两个链接按钮 -->
		<div class="img_input">
			<div>
				<a href="<?php echo $this->url('index',array('controller'=>'index','action'=>'indexb'))?>" class="app"><img src="<?php echo $this->basePath();?>/pc/images/facility.png" alt=""></a>
				<a href="<?php echo $this->url('index',array('controller'=>'index','action'=>'indexa'))?>"><img src="<?php echo $this->basePath();?>/pc/images/home_app.png" alt=""></a>
			</div>
		</div>
		<!-- 二维码 -->
		<div class="code"><img src="<?php echo $this->basePath();?>/pc/images/code.png" alt=""></div>
	</div>
	<p class="footer_text">Copyright © kuaiyao.name. All rights reserved. 广东近场网络科技有限公司. 粤ICP备15066271号-3</p>
</div>
<div class="mp4">
	<div class="video_box">
		<div class="close">×</div>
		<video width="1000" height="560" controls="controls">
		  	<source src="<?php echo $this->basePath();?>/images/small/kuaiyao.ogg" type="video/ogg">
		  	<source src="<?php echo $this->basePath();?>/images/small/kuaiyao.mp4" type="video/mp4">
			Your browser does not support the video tag.
		</video>
	</div>
</div>

	<script type="text/javascript"> 
	function check_login()
		{
			
			if(getCookie('index_user_id'))
			{
				
				window.location.href="<?php echo $this->url('index',array('controller'=>'user','action'=>'buyDetails'));?>";
			}
			else
			{
				$("#sign_login").lightbox_me({centered: true, preventScroll: true, onLoad: function() {
					$("#sign_login").find("input:first").focus();
				}});

			} 
		}
	
	$(function(){
		// 联系方式动画
		$(".h_contact ul li a").hover(
			function(){ 
				$(this).children("span").stop().animate({
					'width':'110px',
				},800);
			},
			function(){
				$(".h_contact ul li a span").stop().animate({
					'width':'0px'
				},1000);
			}
		);
		// 删除底部
		$(".footer").remove();
	})
	// 播放视频
	$(".play").click(function(){
		$(".mp4").show();
		$('video').trigger('play');
	})
	$(".mp4 .close").click(function(){
		$(".mp4").hide();
		$('video').trigger('pause');
	})

	</script>