<style>
    .tl{text-align: right;}
    .main-nody{padding:5px 20px 0 20px;}
    .main-nody h5{float: left;}
    .tp{margin-top: 30px;}
    .bc-1{display: none;}
    .fl{float: left;}
    .pd5{
        padding:5px;	
    }
</style>
<div class="panel panel-default">
   <div class="panel-heading">
       <div calss="row">
           <div class="col-sm-6">
               <a href="<?php echo $this->url('admin-user' , array('action' => 'index'));?>">会员管理 </a> / <a href="<?php echo $this->url('admin-user' , array('action' => 'category'));?>">会员类型</a> / <a href="">新增会员分类</a>    
           </div>
       </div>
   </div>
    <div class="pannel-body main-nody">
        <form class="form-horizontal" action="<?php echo $this->url('admin-user',array('action'=>'addCategory'));?>" method="post" >
            <div class="row">
                <div class="col-lg-12">
                    <h5>会员分类</h5>
                </div>
                <div class="col-lg-12">
                    <table class="table table-striped" id="example-4" >
                        <tbody>
                            <tr>
                                <td>类型名称</td>
                                <td>
                                    <input type="text" name="name" value="<?php echo isset($userLabel) ? $userLabel->name : ''?>" class="pd5" required>
                                    <input type="hidden" name="id" value="<?php echo isset($userLabel) ? $userLabel->id : ''?>"/>
                                    <span style="color:red"> * </span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            
            <div class="row tp">
                <div class="col-lg-12">
                    <h5>
                        <button type="submit" name="submit"  value="保存分类" class="btn btn-info btn-large">保存分类</button>
                     </h5>
                </div>
            </div>
        </form>
    </div>
</div>