<?php echo $this->headScript()->prependFile($this->basePath() . '/js/admin/jq_area.js') ?>
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/admin/region.js') ?>
<style>
    .tl{text-align: right;}
    .main-nody{padding:5px 20px 0 20px;}
    .main-nody h5{float: left;}
    .tp{margin-top: 30px;}
    .bc-1{display: none;}
    .fl{float: left;}
    .pd5{
    	padding:5px;
    }
    .fc{
    	color:red;
    }
</style>
<div class="panel panel-default">
   <div class="panel-heading">
       <div calss="row">
           <div class="col-sm-6">
              <a href="<?php echo $this->url('admin-user' , array('action' => 'index')); ?>">会员管理 / <a href="<?php echo $this->url('admin-user' , array('action' => 'index')); ?>">会员管理</a> / <a href="">会员详情</a>
           </div>
       </div>
   </div>
    <div class="pannel-body main-nody">
        <form class="form-horizontal" action="<?php echo $this->url("admin-user",array('action'=>'addUser'))?>" method="post" id="user_info">
        <div class="row">
            <div class="col-lg-12">
                <h5>账号信息</h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4" >
                    <tbody>
                        <tr>
                            <td>登录账号</td>
                            <td>
                                <input type="text" name="name" value="<?php echo isset($user_info['user_name']) ? $user_info['user_name'] : ''?>" class="pd5" disabled>
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                        <tr>
                            <td>登录密码</td>
                            <td>
                                <input type="password" name="password" value="<?php echo isset($user_info) ? $user_info['password'] : ''?>" class="pd5" disabled>
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                        <tr>
                            <td>会员等级</td>
                            <td>
                                <select name="user_level" class="pd5">
                                    <?php foreach ($user_level as $k=>$v){?>
                                    <option value="<?php echo $k;?>" <?php if(isset($user_info->user_level) && $user_info->user_level == $k){?>selected<?php }?>><?php echo $v;?></option>
                                   <?php }?>
                                </select>
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                        <tr>
                            <td> 会员类型</td>
                            <td>
                                <select name="label_id" class="pd5">
                                 <?php foreach ($user_label as $v){?>
                              <option  value="<?php echo $v->id?>" <?php if(isset($user_info->label_id) && $user_info->label_id == $v->id){?>selected<?php }?>><?php echo $v->name;?></option>
                              <?php }?>
                                </select>
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                        <tr>
                            <td> 绑定业务员</td>
                            <td>
                             <select name="admin_id" class="pd5" onchange="getQQ(this)" id="admin_id">
                             <?php foreach ($admin_list as $v){?>
                              <option admin_qq="<?php echo $v->qq;?>" value="<?php echo $v->id?>" <?php if(isset($user_info->admin_id) && $user_info->admin_id == $v->id){?>selected<?php }?>><?php echo $v->name;?></option>
                              <?php }?>
                              </select>
                               
                            </td>
                        </tr>
                        <tr>
                            <td> 业务员QQ</td>
                            <td>
                                <input type="text"  id="qq" value="<?php echo isset($user_info->admin_qq) ? $user_info->admin_qq : '';?>" class="pd5" disabled>
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row tp">
            <div class="col-lg-12">
                <h5>企业信息</h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4" >
                    <tbody>
                        <tr>
                            <td>企业名称</td>
                            <td>
                                <input type="text" name="company_name" value="<?php echo $user_info['company_name']?>" class="pd5">
                                <input type="hidden" name="id" value="<?php echo $user_info['id']?>"/>
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                        <tr>
                            <td> 企业类型</td>
                            <td>
                                <select name="type" class="pd5">
                                <?php foreach ($enterpris_type as $k=>$v){?>
                                    <option value="<?php echo $k;?>" <?php if(isset($user_info->type) && $user_info->type == $k){?>selected<?php }?>><?php echo $v;?></option>
                                   <?php }?>
                                </select>
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                        <tr>
                            <td>联系人</td>
                            <td>
                                <input type="text" name="contacts_name" value="<?php echo $user_info['contacts_name']?>" class="pd5">
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                        <tr>
                            <td> 联系电话</td>
                            <td>
                                <input type="text" name="mobile" value="<?php echo $user_info['mobile']?>" class="pd5">
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                        <tr>
                            <td> 企业传真</td>
                            <td>
                                <input type="text" name="fax" value="<?php echo $user_info['fax']?>" class="pd5">
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                        <tr>
                            <td> QQ号码</td>
                            <td>
                                <input type="text" name="qq" value="<?php echo $user_info['user_qq']?>" class="pd5">
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                        <tr>
                            <td>  E-mail</td>
                            <td>
                                <input type="text" name="email" value="<?php echo $user_info['email']?>" class="pd5">
                                <span class="fc"> * </span>
                            </td>
                        </tr>
                        <tr>
                            <td> 所在区域</td>
                            <td>
                                <span id="area">
                                    <select id="province" name="province" style="width: 100px;"></select>
                                    <select id="city" name="city" style="width: 100px;"></select>
                                    <select id="county" name="county" style="width: 100px;"></select>
							    </span>
                            </td>
                        </tr>
                        <tr>
                            <td> 详细地址</td>
                            <td>
                                <input type="text" name="address" value="<?php echo $user_info['address']?>" class="pd5">
                            </td>
                        </tr>
                        <tr>
                            <td> 企业描述</td>
                            <td>
                                <input type="text" name="description" value="<?php echo $user_info['description']?>" class="pd5">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <h5></h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4">
                    <tbody>
                        <tr>
                            <td>
                                <input type="submit" name="submit" value="审核修改" class="btn btn-info">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        </form>
    </div>
</div>
<script>

function getQQ(a){
	var qq = $("#admin_id").find("option:selected").attr("admin_qq");
	$("#qq").val(qq);
}
$("#area").area({
    cache: region,
    p_id:<?php echo isset($address[0]['region']['id']) ? $address[0]['region']['id'] : 440000;?>,
    ci_id:<?php echo isset($address[1]['region']['id']) ? $address[1]['region']['id'] : 440100;?>,
    co_id: <?php echo isset($address[2]['region']['id']) ? $address[2]['region']['id'] : 440103;?>
});

</script>