<style>
	.dataTables_info{
		display:none;
	}
	.dataTables_paginate{
		display: none;
	}
	.bc-1{display: none;}
	.col-sm-5{display: none;}
	.col-sm-7{display:none;}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
        <a href=" ">会员管理 / <a href=" "> 会员管理</a>
		</h3>
	</div>
	
	<div class="panel-body">
    	<div class="" style="float:right;">
            <form class="form-horizontal" action="<?php $this->url('admin-user' , array('action' => 'index')) ?>" method="get" style="float: left; margin-left: 20px;">
			<span style="font-weight: bold; font-size: 14px;"> 关键词 :</span>
			<input type="text" name="keyword" value="<?php echo isset($keyword)? $keyword : ''?>" placeholder="请输入企业名称搜索" style="line-height: 26px" >
			<select name="level" style="padding: 5px">
			     <option value="0">全部等级</option>
			     <?php foreach ($user_level as $k=>$v){?>
			     <option value="<?php echo $k;?>" <?php echo isset($level) && $level == $k ? 'selected' : ''?>><?php echo $v;?></option>
			     <?php }?>
			</select>
			<select name="type" style="padding: 5px">
			     <option value="0">全部企业</option>
			     <?php foreach ($enterpris_type as $k=>$v){?>
			     <option value="<?php echo $k;?>" <?php echo isset($type) && $type == $k ? 'selected' : ''?>><?php echo $v;?></option>
			     <?php }?>
			</select>
			<input type="submit"  value="搜索" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
		    </form>
    	</div>
    	<div style="clear:both;"></div>
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>企业名称</th>
					<th>企业类型</th>
					<th>登录账号</th>
					<th>会员等级</th>
					<th>所在区域</th>
					<th>最近登录时间</th>
					<th>账号状态</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			<?php if(!empty($users)):?>
			<?php foreach ($users as $user):?>
                <tr class="tr_list" valign="middle">
					<td style="padding-top:18px;"><?php echo $user['company_name']?></td>
					<?php if($user['type'] == '1'):?>
					<td style="padding-top:18px;">经销商</td>
					<?php else:?>
					<td style="padding-top:18px;">供应商</td>
					<?php endif;?>
					<td style="padding-top:18px;"><?php echo $user['name']?></td>
					<?php if($user['user_level'] == '1'):?>
					<td style="padding-top:18px;">普通会员</td>
					<?php else:?>
					<td style="padding-top:18px;">VIP会员</td>
					<?php endif;?>
					<td style="padding-top:18px;"><?php echo $user['region_info']?></td>
					<td style="padding-top:18px;"><?php echo $user['last_login_time']?></td>
					<?php if($user['status']=='1'):?>
					<td style="padding-top:18px;" class="status<?php echo $user['id']?>">启用</td>
					<?php else:?>
					<td style="padding-top:18px;" class="status<?php echo $user['id']?>">禁用</td>
					<?php endif;?>
					<td>
					   <a href="<?php echo $this->url('admin-user' , array('action' => 'detail','id'=>$user['id'])) ?>" class="btn btn-info">编辑</a>
					   <?php if($user['status'] == '1'):?>
					   <a onclick="stopOrStart(<?php echo $user['id']?>,'stop',this)" class="btn btn-danger">停用</a>
					   <?php else:?>
					   <a onclick="stopOrStart(<?php echo $user['id']?>,'start',this)" class="btn btn-info">启用</a>
					   <?php endif;?>
					</td>
				</tr>
			<?php endforeach;?>
			<?php endif;?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-user','condition'=>$condition));?>       </div>
</div>
<script type="text/javascript">
function stopOrStart(id,op,obj){
	if(op == 'stop'){
    	if(confirm("确定要停用吗？")){
    		$.ajax({
    		    url:'<?php echo $this->url('admin-user',array('action'=>'stopOrStartUser'))?>',
    		    type:'post',
    		    data:{'op':'stop','id':id},
    		    dataType:'json',
    		    success:function(data){
        		    if(data.code=='1'){
     		    	   $(".status"+id).html("禁用");
     		    	   $(obj).removeClass('btn-danger');
     		    	   $(obj).addClass('btn-info');
     		    	   $(obj).attr("onclick","stopOrStart(" + id + ",'start',this)");
      		    	   $(obj).html("启用");
            		}
    			},
    		});
    	}
	}else if(op == 'start'){
		if(confirm("确定要启用吗？")){
    		$.ajax({
    		    url:'<?php echo $this->url('admin-user',array('action'=>'stopOrStartUser'))?>',
    		    type:'post',
    		    data:{'op':'start','id':id},
    		    dataType:'json',
    		    success:function(data){
    		    	if(data.code=='1'){
    		    		$(".status"+id).html("启用");
    		    		$(obj).removeClass('btn-info');
    	  		    	$(obj).addClass('btn-danger');
    	  		    	$(obj).attr("onclick","stopOrStart(" + id + ",'stop',this)");
    		    		$(obj).html("停用");
    		    	}
    			},
    		});
		}
	}
}
</script>