<?php echo $this->headTitle($GoodsDetail['name']. $this->translate(''))->setSeparator(' - ')->setAutoEscape(false);?>
<?php echo $this->headMeta()->setName('description', mb_substr($GoodsDetail['description'],0,300)); ?>
<script>$(function(){showmenu();});</script>
<script type="text/javascript">
    $(function(){
        $('.small_img_box li').click(function(){
            $('.small_img_box li').removeClass('on');
            $(this).addClass('on');
            $('.img_box img').attr('src',$(this).find('img').attr('src')).attr('jqimg',$(this).find('img').attr('src'));
        });
        jQuery('#spec-n5').slide({mainCell:'.small_img_box ul',effect:'left',autoPlay:false,vis:4,pnLoop:false});

    });
</script>
<div class="content w bc">
    <!--web address -->
    <p class="lh25px f14 mt20 ml20">
        <a href="<?php echo $this->url('index',array('controller'=>'index','action'=>'index'))?>" class="f_color_gray">首页&nbsp;&gt;&nbsp;</a>
        <a href="<?php echo $this->url('index',array('controller'=>'seller','action'=>'index'))?>" class="f_color_gray">联盟商家&nbsp;&gt;&nbsp;</a>
        <a href="<?php echo $this->url('index',array('controller'=>'seller','action'=>'sellerDetail','id'=>$GoodsDetail['u_id']))?>" class="f_color_gray"><?php echo $GoodsDetail['company_name']; ?>&nbsp;&gt;&nbsp;</a>
        <a class="f_color_gray"><?php echo $GoodsDetail['name']?></a>
    </p>
    <!-- web address end -->
    <div class="con clearfix bg_white pt20 pb20 pl20 pr20 pr">
        <div class="detail_img fl">
            <div class="img_box" id="spec-n1" >
                <?php foreach($GoodsDetail['gallery'] as $k=>$v){
                    echo '<img src="'.$v[1].'" jqimg="'.$v[0].'" />';
                    break;
                }?>
            </div>
            <div id="spec-n5">
                <div class="control prev" id="spec-left">
                    <img src="<?php echo ROOT_PATH?>images/left.png">
                </div>
                <div class="small_img_box">
                    <ul class="clearfix">
                        <?php foreach($GoodsDetail['gallery'] as $k=>$v){
                            echo '<li class="fl mr5 '.($k==0 ? 'on' : '').'"><img src="'.$v[0].'"></li>';
                        }?>
                    </ul>
                </div>
                <div class="control next" id="spec-right">
                    <img src="<?php echo ROOT_PATH?>images/right.png">
                </div>
            </div>
        </div>
        <script type=text/javascript>
            $(function(){
                $(".img_box").jqueryzoom({
                    xzoom:360,
                    yzoom:270,
                    offset:10,
                    position:"right",
                    preload:1,
                    lens:1
                });
            })
        </script>

        <div class="detail_text fl ml20 mb20">
            <div class="border_b" style="width:100%">
                <h2 class=""><?php echo $GoodsDetail['name']?></h2>
            </div>
            <div class="clear"></div>
            

            <div class="f_color_gray mt10">
                <?php if($status !== '0'){?>
                    <input type="button" value="收藏" class="collect_btn  f_color_white" id="collect" status="1" />
                <?php }else{?>
                    <input type="button" value="取消收藏" class="collect_btn  f_color_white" id="collect" status="2"  />
                <?php }?>

            </div>

            <div class="bdsharebuttonbox mt10"><a href="#" class="bds_more" data-cmd="more">分享到：</a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信">微信</a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间">QQ空间</a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博">新浪微博</a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博">腾讯微博</a></div>
            <script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"6","bdMiniList":["mshare","qzone","tsina","weixin","renren","tqq","kaixin001","tqf","tieba","douban","tsohu","bdhome","sqq","thx","ibaidu","meilishuo","mogujie","diandian","huaban","duitang","hx","fx","youdao","sdo","qingbiji","people","mail","isohu","yaolan","copy","print"],"bdPic":"","bdStyle":"0","bdSize":"16"},"share":{"bdSize":16},"image":{"viewList":["weixin","qzone","tsina","tqq"],"viewText":"分享到：","viewSize":"16"}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
        </div>
    </div>
    <div class="mt20 clearfix">
        <div class="fl w195">
            <div class="border_b">
                <div class="detail_info f_color_red f14">精品热销</div>
            </div>
            <ul class="border_top">
                <?php foreach($this->topSix as $v){?>
                    <li class="pl10 pr10 pb10 mb10 bg_white">
                        <div class="p_img tc pt5 pb5">
                            <a href="<?php echo $this->url('index',array('controller'=>'seller','action' =>'sellerGoodsDetail','id'=>$v['id'])); ?>">
                                <img src="<?php echo $v['image_url']; ?>">
                            </a>
                        </div>
                        <a class="f14" href="<?php echo $this->url('index',array('controller'=>'seller','action' =>'sellerGoodsDetail','id'=>$v['id'])); ?>" class="lh150">
                            <?php echo $v['name']?>
                        </a>
                        <p class="mt5">

                            <a href="<?php echo $this->url('index',array('controller'=>'seller','action' =>'sellerGoodsDetail','id'=>$v['id'])); ?>">

                            </a>
                        </p>
                    </li>
                <?php } ?>
            </ul>

        </div>
        <div class="fr w960 bg_white pb30 border_l border_r border_b">
            <div class="border_b">
                <div class="detail_info f_color_red f14">商品详情</div>
            </div>
            <div class="pt20 pb20 pl20 pr20">
                <?php if(''!=stripslashes($GoodsDetail['description'])){?>
                    <?php echo stripslashes($GoodsDetail['description'])?>
                <?php }else{?>
                    <p class="tc f_color_gray" style="font-size:30px;">该商品暂无详情</p>
                <?php }?>
            </div>
        </div>
    </div>
</div>

<div class="alert other">
    <div class="alert_bg"></div>
    <div class="alert_atricle">
        <h3></h3>
        <div class="btn_alert">我知道了</div>
    </div>
</div>

<script type="text/javascript">
    $('.btn_alert').click(function()
    {
        $('.alert').hide();
    })
</script>

<script type="text/javascript">

    $('#collect').click(function setJson()
    {
        var json = new Object();
        json.n = 'FavoritesSwitch';
        json.q = new Object();
        json.q.a = 1;
        json.q.id = <?php echo $id; ?>;
        json.q.open = $(this).attr('status');

        $.post("<?php echo $this->url('index-lottery',array('action'=>'getJson'));?>", {request: json},
            function(data)
            {

                data = $.parseJSON(data);
                if(data.error == 1000){
                    $('.other').find('h3').text('请在登录后操作！');
                    $('.other').show();
                    window.location.href = "<?php echo $this->url("index",array('controller'=>'user','action'=>'login'));?>";
                }
                if(data.q.s == 0)
                {
                    $('.other').find('h3').text(data.q.d);
                    $('.other').show();
                    window.location.href = "<?php echo $this->url("index",array('controller'=>'seller','action'=>'sellerGoodsDetail','id'=>$id));?>";
                }

            });
        return false;
    });

</script>


