			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-content">
						
						<table class="table table-striped table-bordered bootstrap-datatable">
						  <thead>
							  <tr>	
							      <th>ID</th>						
								  <th>产品名</th>
								  <th>所属分类</th>
								  <th>商家名</th>
								  <th>状态</th>
								  <th>审核状态</th>							  							 
								  <th>添加时间</th>
								 
							  </tr>
						  </thead>   
						  <tbody>
						  <?php if($data['list']){?>
						 <?php foreach($data['list'] as $v):?>						 			   
							<tr>
							    <td><?php echo $v->timestamp;?></td> 						
								<td><?php echo $v->stars;?></td>
								<td><?php echo $v->content;?></td>
								<td><?php echo $v->user_id;?></td>
								<td><?php echo $v->user_name;?></td>
								<td><?php echo $v->path;?></td>
								<td><?php echo $v->user_level;?></td>
							</tr>
							<?php endforeach;?>
							<?php }?>						
						  </tbody>
					  </table>
					  
					   <div class="pagination pagination-centered">
					   
						</div> 
					              
					</div>
				</div><!--/span-->
			</div><!--/row-->
			
		