<?php echo $this->headLink()->appendStylesheet($this->basePath() . '/css/demo.Default.css')?>
<script src="<?php echo $this->basePath();?>/kindeditor/kindeditor.js"></script>
<script src="<?php echo $this->basePath();?>/kindeditor/lang/zh_CN.js"></script>
<?php echo $this->headScript()->offsetSetFile(10, $this->basePath() . '/js/ajaxfileupload.js') ?>
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/jq_area.js') ?>
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/region.js') ?>
<?php $tem = array("zero"=>'一'/*,"first"=>'二',"second"=>'三',"third"=>'四',"fourth"=>'五',"fifth"=>'六',"sixth"=>'七',"seventh"=>'八'*/); ?>
<!--<script language="javascript"
	src="http://webapi.amap.com/maps?v=1.3&key=d4e906f2d3b338bc0fa31cba41b4c5ca"></script>
<!-- //上传JS -->
<!--<script type="text/javascript">
    var url = '<?php echo $this->url('admin-common',array('action'=>'getAdminFile'));?>';//图片上传地址 
    var url_two = '<?php echo $this->url('admin-common',array('action'=>'getAdminFileTwo'));?>';//图片上传地址
</script>
-->
<div class="row">
	<form role="form" class="form-horizontal"
		action="<?php echo $this->url('admin-company', array('action' => 'modify')) ?>"
		onsubmit="return checkSubmit()" method="post">
		<div class="col-sm-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>基本资料(必填)</h3>
					<input type="hidden" name="id" value="<?php echo $company_info['id'];?>"/>
				</div>
				公司名称：<input type="text" name="name" value="<?php echo $company_info['name']?>">
				
				<div class="col-sm-10">
							LOGO：<input type="file" id="img0" name="Filedata"
								onchange="return ajaxFileUpload('0');" /> <input type="hidden"
								name="image"
								value="<?php echo isset($company_info['image']) ? $company_info['image'] : ''; ?>"
								id="img_id_0" /> <br /> <img
								src="<?php echo isset($company_info['image']) && isset($logo) ? $logo : $this->basePath().'adminStyle/img/no_pic.gif'; ?>"
								width="200" height="200" id="img_0" />
			    </div>
			    
			    </br>
			        是否推荐：
			    <select name="is_top">
    			    <option value="1">推荐</option>
    			    <option value="2">不推荐</option>
			    </select>
			    </br>
			        电话：<input type="text" name="telephone" value="<?php echo $company_info['telephone']?>">
			    </br>
			    公司简介：<textarea name="content"><?php echo $company_info['description']?></textarea>
			  </br>
			  经营项目：<textarea name="project"><?php echo $company_info['project']?></textarea>

			  </br>
			  子公司：
			  <?php foreach($filiale as $k => $v){?>
			     <div style="border:1px solid #FF0000;" class="filiale" onclick="getId(<?php echo $v['id']?>)">
			        <img src="<?php echo $v['image']?>">
			        <span><?php echo $v['name']?></span>
			        </br>
			        <span><?php foreach($category as $catk => $catv){if($v['category_id']==$catk){echo $catv;break;}}?></span>
			        </br>
			        <span><?php foreach($scale as $scalek => $scalev){if($v['scale']==$scalek){echo $scalev;break;}}?></span>
			        <span style="display:none" id="parent_id" ><?php echo $v['id']?></span>
			     </div>
			  <?php }?>
			</div>
			</br>
			<input type="submit" name="submit" value="提交更新" />
		</div>	
	</form>
</div>


<script type="text/javascript">
function getId(id) {
	if(!window.confirm("确定删除子公司?")){
		return false;
	}
	$.post("<?php echo $this->url('admin-company',array('action'=>'delfiliale'))?>", {id:id},
		function(data){
	        if(data==1){
	            alert('删除成功!');
	            location.href();
		    }else{
		        alert('删除失败!');
		        location.href()
			}
    },"json");
}
//      $(".filiale").click(function(){
//          alert($(this).attr('attr_id'));
// //    	        parent_id = $("#parent_id").text();
// //    	        alert(parent_id);
//      });
</script>
