<?php echo $this->headScript()->offsetSetFile(10, $this->basePath() . '/js/ajaxfileupload.js') ?>
<script src="<?php echo $this->basePath();?>/kindeditor/kindeditor.js"></script>
<script src="<?php echo $this->basePath();?>/kindeditor/lang/zh_CN.js"></script>
<script src="<?php echo $this->basePath() ?>/js/Uploads.js"></script>
<script src="<?php echo $this->basePath() ?>/adminStyle/js/jquery.uploadify-3.1.min.js"></script>
<?php echo $this->headLink()->offsetSetStylesheet(15,$this->basePath() . '/css/uploadify.css')?>
<script type="text/javascript">
    var swf ='<?php echo $this->basePath() . '/adminStyle/js/uploadify.swf'?>';
    var uploader = '<?php echo $this->url('admin-common',array('action'=>'getAdminFile'));?>';//图片上传地址 
    var url_two = '<?php echo $this->url('admin-common',array('action'=>'getAdminFileTwo'));?>';//图片上传地址
</script>
<style type="text/css">
.form-control{width: 500px;margin-bottom: 5px;margin-right: 5px;}

.search {
    width: 300px;
    height: 40px;
    position: relative;
}

.edit {
    overflow: hidden;
}

.search_input {
    width: 290px;
    height: 34px;
    font-size: 16px;
}

.search_input:focus {
    outline: none;
}

.match_text {
    display: none;
    position: absolute;
    top: 6px;
    width: 290px;
    z-index: 99;
    background-color: white;
    border: 1px solid #ccc;
}

.match_text div:hover {
    background: #f0f0f0;
}

.match_text ul {
    list-style-type: none;
    border: 1px solid #cccccc;
    margin-bottom: 0px;
}

.match_text ul li {
    font-size: 12px;
    color: #333333;
    display: block;
    line-height: 25px;
    padding-left: 10px;
    cursor: pointer;
}
.mot_tright{
	margin-left: 60px;
	margin-top: 20px;
}
</style>
<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 style="width:200px;float:left;">活动详情</h3>
				<div style="width:400px;float:left;margin:20px 0 0 1172px;">
    				<span><a href="<?php echo $this->url('admin-activity',array('action'=>'index'))?>">商业圈</a></span>|
    				<span><a href="">活动详情</a></span>
    			</div>
				<div class="panel-options">
					<a href="#" data-toggle="panel">
						<span class="collapse-icon">&ndash;</span>
						<span class="expand-icon">+</span>
					</a>
					<a href="#" data-toggle="remove"> &times; </a>
				</div>
			</div>
			<div class="panel-body">
                <form role="form" class="form-horizontal" action="<?php echo $this->url("admin-activity",array('action'=>'edit'));?>" method="post" >
				<div class="form-group">
					<label class="col-sm-2 control-label"  for="field-1">发布公司:</label>
					<div class="col-sm-10">
						<input class="form-control"  required name="acName" id="device_id" value="<?php echo isset($data->c_name)?$data->c_name:''; ?>" />
					</div>
				</div>
				<div class="form-group-separator"></div>
				<div class="form-group">
					<label class="col-sm-2 control-label" for="field-1">活动标题:</label>
					<div class="col-sm-10">
						<input class="form-control" required name="acName" id="device_id" value="<?php echo isset($data->name)?$data->name:''; ?>" />
					</div>
				</div>
				<div class="form-group-separator"></div>
				<div class="form-group">
					<label class="col-sm-2 control-label" for="field-1">排序:</label>
					<div class="col-sm-10">
						<input class="form-control" type="number" name="sort" id="sort" value="<?php echo isset($data->sort)?$data->sort:'0'; ?>" />
					</div>
				</div>
				<div class="form-group-separator"></div>
				<div class="form-group">
					<div class="control-group">
					<!--多图片上传-->
						<label class="col-sm-2 control-label" for="field-1">活动图片：</label>
							<div class="controls">
								<div style="line-height:30px;display:block;height:30px;">提示：(图片比例建议4:3，请上传1-5张图片)</div>
							         <div class="mot_tright" id="img_div" >									           
                                       <input id="index_img" type="text" name="image_ids[]" />
									   <?php if(isset($images)){foreach ($images as $k){?>
                                                <div id="img_div<?php echo $k['id']?>" class="outdiv">
                                                    <img src="<?php echo ROOT_PATH.UPLOAD_PATH.$k['path']?>" onmouseover='del1(this)'  width = '100px'>
                                                	<div id='near_img<?php echo $k['id']?>' onmouseout='del3(this)' onclick='del2(<?php echo $k['id']?>)' class='innerdiv'>删除</div>
                                                    <input value="<?php echo $k['id']?>" name='image_ids[]' type='hidden'>
                                                </div>
                                         <?php }}?>
                                     </div>
							</div>
					</div>
					
				</div>
				<div class="form-group-separator"></div>
				
				<div class="form-group">
					<label class="col-sm-2 control-label" for="field-1">活动描述：</label>
					<div class="col-sm-10">
					      <textarea style="height:350px;" rows="" cols="" name="content" id="uuid" ><?php echo isset($data->content)?$data->content:''; ?></textarea>
                        
                        <input type='hidden' name='id' value="<?php echo isset($data->id)?$data->id:''; ?>" />
					</div>
				</div>
				<div class="form-group-separator"></div>
				
				
				
				<div class="form-group">
					<div class="col-sm-10">
					   <input type='reset' value='取消' class='' style='margin-left:200px;' onclick="jump()"/>
                        <input type='submit' value='修改' class='' style='margin-left:50px;'/>
					</div>
				</div>
				<div class="form-group-separator"></div>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
KindEditor.ready(function(K) {
    window.editor = K.create('#uuid');
});


function check()
{
	var device_id  = $("#device_id").val();
	var comment = $("#comment").val();

	if(device_id == '')
	{
		alert('发布公司不能为空');
		return false;
	}

	if(getlength(comment) > 30)
	{
		alert('申请理由不能为空！');
		return false;
	}
	
}

function jump(){
	window.location="<?php echo $this->url('admin-activity',array('action'=>'index'))?>";
}

//字段长度判断
function getlength (str) {
    //<summary>获得字符串实际长度，中文2，英文1</summary>
    //<param name="str">要获得长度的字符串</param>
    var realLength = 0, len = str.length, charCode = -1;
    for (var i = 0; i < len; i++) {
        charCode = str.charCodeAt(i);
        if (charCode >= 0 && charCode <= 128) realLength += 1;
        else realLength += 2;
    }

    return realLength;
}

function json(obj)
{
    if(obj==''){return;}
    var json = new Object;
    json.s = obj;

    $.post("<?php echo $this->url('admin-device',array('action'=>'deviceBindPage'));?>", {request: json},
        function(data)
        {
            data = $.parseJSON(data);
            if(data)
            {
                $("#json_back").show();
                var html = '';
                var list = data;
                for(var i =0;i<list.length;i++){
                    html+='<div style="width:290px;cursor:pointer;">'+list[i].page_id+'#'+list[i].title+'</div>';
                }
                $("#json_back").html(html);
                $("#json_back div").click(function(){
                    $("#search_text").val( $(this).text() );
                    $("#json_back").hide();
                });
            }
        });
}
</script>