<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>吉宏园艺</title>
<link rel="shortcut icon" href="favicon.ico" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/index/base.css">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/index/sylogin.css">
<script type="text/javascript" src="<?php echo $this->basePath();?>/js/jquery-1.7.2.min.js"></script>
</head>
<body>
    <div class="head wrap clearfix">
        <a href="<?php echo $this->url('index' , array('controller' => 'index' , 'action' => 'index'  ))?>" class="sylogo fl"></a>
        <p class="trading_tittle fl font20 corgray6 fontb">全方位中国花卉交易平台</p>
    </div>
    <div class="main">
        <div class="wrap dw">
            <div class="login_box">
                <div class="clearfix login_box_tittle mb30">
                    <h2 class="current border_r" enterpris_type="1">经销商</h2>  
                    <h2 enterpris_type="2">供应商</h2> 
                </div>
                <div class="form pub current">
                    <input type="hidden" id="enterprisType" name="type"  value="1">
                    <div class="txt1">
                        <input class="account" type="text" name="name" id="name" placeholder="请输入账号"  />
                        <i>&#xe714;</i>
                    </div>
                    <div class="txt2">
                        <input class="password" type="mobile" maxLength="11" name="mobile" id="mobile" placeholder="请输入手机号" />
                        <i>&#xe604;</i>
                    </div>
                    <div class="test clearfix">
                        <input class="fl" type="text" name="captcha" id="captcha" placeholder="请输入验证码" />
                        <div class="testpic fr">
                            <img id="Captcha" src="" onclick="onvdcodeFocus()" height="38" width="78" >
                        </div>
                    </div>
                    <input class="login_btn font18 corgrayf" type="button"  value="找回密码" />
                    <p class="help_txt">
                        <span><a class=" corgray3" href="<?php echo $this->url('index' , array('controller' => 'login' , 'action' => 'index'))?>">返回登录</a></span>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- 弹窗 -->
    <div class="pop_resetpa_bj"></div>
    <div class="pop_resetpa">
        <h3>密码已重置</h3>
        <p class="send">登录密码已发送至您的手机，请查看短信</p>
        <p class="ensure">确定</p>
    </div>
</body>
<script type="text/javascript">
$('.login_box h2').click(function(event) {
    $(this).addClass('current').siblings('').removeClass('current');
    
    $('#name').val('');
    $('#mobile').val('');
    $('#captcha').val('');
    $('#enterprisType').val($(this).attr('enterpris_type'));
});

var flag = true;
 // 弹窗
 $('.form .login_btn').click(function(event) {
	 if(flag)
	 {
		 var type     =  $('#enterprisType').val();
         var name   =  $('#name').val();
         var mobile =  $('#mobile').val();
         var code    =  $('#captcha').val();

         var reg = /^1[3|4|5|8][0-9]\d{8}$/;
         if ( !reg.test(mobile)) {
              return false;
         }
         flag = false;
         $.post('<?php echo $this->url('index' , array('controller' => 'login' , 'action' => 'forgetPassword'))?>' , {'name':name , 'mobile' :mobile , 'type' :type  , 'code' : code } , function(data){
        	 $('.pop_resetpa>h3').html(data.title);
        	 $('.pop_resetpa>p.send').html(data.description);
        	 $('.pop_resetpa').show();
             $('.pop_resetpa_bj').show();
             flag = true;
         },"json")
	 }
 });
 
 // 弹窗内容关闭
 $('.pop_resetpa .ensure').click(function(event) {
     $('.pop_resetpa').hide();
     $('.pop_resetpa_bj').hide();
 });

onvdcodeFocus();
function onvdcodeFocus()
{
	$.post("<?php echo $this->url('admin-common',array('action'=>'generateCaptcha'))?>",
		function(data){    		    	     
			$("#Captcha").attr("src",data);
		});
}
</script>
</html>

