<style>
	.dataTables_info{
		display:none;
	}
	.dataTables_paginate{
		display: none;
	}
	.bc-1{display: none;}
	.col-sm-5{display: none;}
	.col-sm-7{display:none;}
	.fl{
		float:left;
	}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
        <a href="<?php echo $this->url('admin-config' , array('action' => 'adminList')) ?>">平台管理 / <a href="">收款账号管理</a>
		</h3>
	</div>
	
	<div class="panel-body">
	    <div class="fl" >
		    <a class="btn btn-info fl " href="<?php echo $this->url('admin-config' , array('action' => 'accountOperate')) ?>" >新增账号</a>
		</div>
    	<div style="clear:both;"></div>
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>银行名称</th>
 					<th>开户行</th>
					<th>账号</th>
					<th>收款人</th>
					<th>排序</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			    <?php foreach ($account_list as $value): ?>
                <tr class="tr_list" valign="middle">
					<td style="padding-top:18px;"><?php echo $bank_list[$value->bank_id]->name; ?></td>
					<td style="padding-top:18px;"><?php echo $value->branch; ?> </td>
					<td style="padding-top:18px;"> <?php echo $value->number; ?> </td>
					<td style="padding-top:18px;"><?php echo $value->name; ?> </td>
					<td style="padding-top:18px;"><?php echo $value->sort; ?></td>
					<td>
					   <a href="<?php echo $this->url('admin-config' , array('action' => 'accountOperate' , 'id' => $value->id)) ?>" class="btn btn-info">查看</a>
					   <a href="#"  onclick="show_confirm('<?php echo $this->url('admin-config' , array('action' => 'deleteAccount' , 'id' => $value->id)); ?>')" class="btn btn-info">删除</a>
					 </td>
				</tr>
				<?php endforeach;?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-config','condition'=>$condition));?>
        </div>
</div>

<script>
function show_confirm(url)
{
	if(confirm('确认删除？'))
	{
		location.href = url;
	}
	else
	{
		return false;
	}
}
</script>