<style>
    .tl{text-align: right;}
    .main-nody{padding:5px 20px 0 20px;}
    .main-nody h5{float: left;}
    .tp{margin-top: 30px;}
    .bc-1{display: none;}
    .fl{float: left;}
    .pd5{
        padding:5px;	
    }
    .w320{
    	width:320px;
    }
</style>
<div class="panel panel-default">
   <div class="panel-heading">
       <div calss="row">
           <div class="col-sm-6">
              <a href="">个人设置
              / 
              <a href="">修改密码</a> 
           </div>
       </div>
   </div>
    <div class="pannel-body main-nody">
    <form class="form-horizontal" action="<?php echo $this->url('admin-config' , array('action' => 'adminPassword')); ?>" method="post" >
        <div class="row">
            <div class="col-lg-12">
                <h5> </h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4" >
                    <tbody>
                        <tr>
                            <td>旧密码</td>
                            <td>
                            <input type="password" name="old_password"  value="" class="pd5 w320"  required>
                            </td>
                        </tr>
                        <tr>
                            <td>新密码</td>
                            <td>
                                <input type="password" name="password"  value="" class="pd5 w320"  required>
                            </td>
                        </tr>
                        <tr>
                            <td>确认新密码</td>
                            <td>
                                <input type="password" name="comfirm_password" value="" class="pd5 w320"  required>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <h5></h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4">
                    <tbody>
                        <tr>
                            <td>
                                <input type="submit" value="提交" class="btn btn-info" name="submit" >
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        </form>
    </div>
</div>