<style>
	.dataTables_info{
		display:none;
	}
	.dataTables_paginate{
		display: none;
	}
	.bc-1{display: none;}
	.col-sm-5{display: none;}
	.col-sm-7{display:none;}
	.fl{
		float:left;
	}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
        <a href="<?php echo $this->url('admin-config' , array('action' => 'adminList')) ?>">管理员管理 / <a href="">管理员类型</a>
		</h3>
	</div>
	
	<div class="panel-body">
	    <div class="fl" >
		    <a class="btn btn-info fl " href="<?php echo $this->url('admin-config' , array('action' => 'categoryOperate' )) ?>" >新增类型</a>
		</div>
    	<div style="clear:both;"></div>
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th> 管理员类型姓名 </th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			     <?php foreach ($admin_category_list as $key => $value): ?>
                <tr class="tr_list" valign="middle">
					<td style="padding-top:18px;"><?php echo $value->name?></td>
					<td>
					   <a href="<?php echo $this->url('admin-config' , array('action' => 'categoryOperate' ,'id' => $value->id)) ?>" class="btn btn-info">查看</a>
					   <?php if($value->id !=1): ?>
					   <a href="#"  onclick="show_confirm('<?php echo $this->url('admin-config' , array('action' => 'deleteCategory' ,'id' => $value->id)) ?>')" class="btn btn-info">删除</a>
					   <?php endif;?>
					 </td>
				</tr>
				<?php endforeach;?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-config', 'condition'=>$condition));?>
        </div>
</div>

<script>
function show_confirm(url)
{
	if(confirm('确认删除？'))
	{
		location.href = url;
	}
	else
	{
		return false;
	}
}
</script>