<style>
    .tl{text-align: right;}
    .main-nody{padding:5px 20px 0 20px;}
    .main-nody h5{float: left;}
    .tp{margin-top: 30px;}
    .bc-1{display: none;}
    .fl{float: left;}
    .pd5{
        padding:5px;	
    }
</style>
<script src="<?php echo $this->basePath();?>/js/admin/jedate.min.js"></script>
<div class="panel panel-default">
   <div class="panel-heading">
       <div calss="row">
           <div class="col-sm-6">
               <a href="<?php echo $this->url('admin-config' , array('action' => 'timeNode'));?>">交易时间设置 </a> / <a href="">编辑时间节点</a>    
           </div>
       </div>
   </div>
    <div class="pannel-body main-nody">
        <form class="form-horizontal" action="<?php echo $this->url('admin-config',array('action'=>'addTimeNode'))?>" method="post" >
            <div class="row">
                <div class="col-lg-12">
                    <h5> </h5>
                </div>
                <div class="col-lg-12">
                    <table class="table table-striped" id="example-4" >
                        <tbody>
                            <tr>
                                <td>开始时间</td>
                                <td>
                                    <input class="datainp" id="start_time" type="text" placeholder="请选择"  readonly value="<?php echo isset($info->start_time) ? substr($info->start_time, 0 ,10) :''?>" name="start_time"  style="line-height:22px;width:160px">
                                </td>
                            </tr>
                            <tr>
                                <td>结束时间</td>
                                <td>
                                    <input class="datainp" id="end_time" type="text" placeholder="请选择"  readonly value="<?php echo isset($info->deadline) ? substr($info->deadline, 0 ,10) :''?>" name="end_time"  style="line-height:22px;width:160px">
                                </td>
                            </tr>
                            <tr>
                                <td>时间节点</td>
                                <td>
                                    <input class="datainp" id="time_node" type="text" placeholder="请选择"  readonly value="<?php echo isset($info->node) ? $info->node :''?>" name="time_node"  style="line-height:22px;width:160px">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
    
            <div class="row tp">
                <div class="col-lg-12">
                    <p>注：
1、交易时间节点用于提示用户购买商品时平台受理订单的时间节点。
2、若未设置交易时间节点的日期，默认时间节点均为16:30分</p>
                    <h5>
                        <input type="hidden" name="id" value="<?php echo isset($id) ? $id : ''?>">
                        <button type="submit" name="submit" value="保存" class="btn btn-info btn-large">保存</button>
                     </h5>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
var start ={
		dateCell:"#start_time",
		format:"YYYY-MM-DD",
		isinitVal:false,
		isTime:true, 
		//maxDate: jeDate.now(0),
		minDate:"1970-01-01",
		choosefun: function(datas){
			end.minDate = datas;
	    }
	};
var end ={
	dateCell:"#end_time",
	format:"YYYY-MM-DD",
	isinitVal:false,
	isTime:true,
	minDate:"1970-01-01",
	//maxDate: jeDate.now(0),
	choosefun: function(datas){
        start.maxDate = datas;
    }
}
var node ={
	dateCell:"#time_node",
	format:"hh:mm",
	isinitVal:false,
	isTime:true,
	//minDate:"00:01",
	//maxDate: jeDate.now(0),
	choosefun: function(datas){
        start.maxDate = datas;
    }
}
jeDate(start);
jeDate(end);
jeDate(node);
</script>