<!--[if IE 6]>
	<script src="js/pngAlaph.js" ></script> 
	<script> 
		DD_belatedPNG.fix('img');
	</script> 
<![endif]-->
<script>window["_GOOG_TRANS_EXT_VER"] = "1";</script><script type="text/javascript" id="b5mmain" src="<?php echo $this->basePath();?>/about/js/b5m.main.js"></script><link rel="stylesheet" href="css/b5m-plugin.css" type="text/css"></head>

<body>
<!--  header -->

		<!--  banner -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1,user-scalable=ture">
<link rel="stylesheet" type="text/css" href="css/style(1).css">
<style type="text/css">
/*addcss20150922开始*/
.about_me{
  font-size: 24px;
  color: black;
  border-bottom: 1px solid #55b2dd;
  padding-bottom: 15px;
}
.about_body{
  background: white;
  height: 615px;
}
.about_body h2{
  font-size: 16px;
  color: #3975fe;
  margin-top: 25px;
  margin-bottom: 18px;
}
.lianxi{
  width: 571px;
  height: 199px;
}
.lianxi p{
  font-size: 14px;
  color: #333333;
  line-height: 2.3;
}
/*addcss20150922结束*/
   .part_5_img01{
    margin-top: 73px;
  }
  .part_5_img01 img{
    width: 243px;
    height: 243px;
      }
    /*右侧css*/
    /* leftsead */
*html #leftsead{margin-top:258px;position:absolute;top:expression(eval(document.documentElement.scrollTop));}
#leftsead li{width:161px;height:78px;}
#leftsead li img{float:right;}
#leftsead li a{height:22px;float:right;display:block;min-width:47px;max-width:161px;}
#leftsead li a .shows{display:block;}
#leftsead li a .hides{cursor:pointer;cursor:hand;}
#leftsead li a.youhui .hides{display:none;position:absolute;right:143px;}
#leftsead li a.youhui .2wm{display:none;position:absolute;right:143px;}
#p2{width:120px;background-color:#f0b614;height:50px;margin-left:47px;line-height:50px;border-top-right-radius:24px;border-bottom-right-radius:24px;}
#p3{width:120px;background-color:#6c9;height:50px;margin-left:47px;line-height:50px;border-top-right-radius: 24px;border-bottom-right-radius: 24px;}
#p1{width:50px;height:50px;float:left}
#leftsead{
  width: 161px;
  height: 290px;
  position: fixed;
  top: 50%;
  right: 30px;
  z-index: 100;
  margin-top: -106px;
}
.tell1{
  background: #f0b614;
  border-top-left-radius:50%;
  border-bottom-left-radius:50%;
}
.mess{
  background: #6c9;
  border-top-left-radius:50%;
  border-bottom-left-radius:50%;
}
/*add关于我们*/
.bglogo{
  width: 100%;
  height: 12px;
  background: url(../images/bglogo.png) repeat-x;
}
.bd{
  height: 1668px;
  width: 1010px;
  margin:0px auto;
  clear: both;
  margin-top: 18px;
}
.bg_left{
  width: 140px;
  height: 160px;
  float: left;
  background: #f5f5f5;
}
.bg_right{
  width: 842px;
  height: 691px;
  float: right;
  position: relative;
}
.bg_left ul{
  font-size: 16px;
  text-align: center;
  margin-top: 10px;
  line-height: 40px;
}
.bg_left ul li a{
  color: black;
  font-weight: bold;
    /*右侧css*/
    /* leftsead */
*html #leftsead{margin-top:258px;position:absolute;top:expression(eval(document.documentElement.scrollTop));}
#leftsead li{width:161px;height:78px;}
#leftsead li img{float:right;}
#leftsead li a{height:49px;float:right;display:block;min-width:47px;max-width:161px;}
#leftsead li a .shows{display:block;}
#leftsead li a .hides{cursor:pointer;cursor:hand;}
#leftsead li a.youhui .hides{display:none;position:absolute;right:143px;}
#leftsead li a.youhui .2wm{display:none;position:absolute;right:143px;}
#p2{width:120px;background-color:#f0b614;height:50px;margin-left:47px;line-height:50px;border-top-right-radius:24px;border-bottom-right-radius:24px;}
#p3{width:120px;background-color:#6c9;height:50px;margin-left:47px;line-height:50px;border-top-right-radius: 24px;border-bottom-right-radius: 24px;}
#p1{width:50px;height:50px;float:left}
#leftsead{
  width:161px;
  height:290px;
  position: absolute;
  top: 1580px;
  right: 344px;
  z-index:100;
}
.tell1{
  background: #f0b614;
  border-top-left-radius:50%;
  border-bottom-left-radius:50%;
}
.mess{
  background: #6c9;
  border-top-left-radius:50%;
  border-bottom-left-radius:50%;
}
</style>
<div class="con">
    <div class="bglogo"></div>
    <div class="bd" style="height:691px;">
      <div class="bg_left">
        <ul>
        <li><a href="<?php echo  $this->url("index",array('action'=>'index','controller'=>'About'));?>">公司介绍</a></li>
        <li><a href="<?php echo  $this->url("index",array('action'=>'account','controller'=>'About'));?>">经营项目</a></li>
        <li><a href="javascript:void(0);" style="color: #3976fd;">联系我们</a></li>
        </ul>
      </div>
      <div class="bg_right">
        <!-- <img src="images/aboutme.png"/> -->
        <p class="about_me">关于我们</p>
        <div class="about_body"> 
          <h2>联系我们</h2> 
          <div class="lianxi">
            <p>地址:广州市荔湾区周门北路38号协晟大厦205室</p>
            <p>电话:400-838-3765</p>
            <p>微信公众号:快摇名片</p>
            <p>邮箱:kefu@kuaiyao.name</p>
          </div>
        </div>
      <!-- 右侧显示区域开始 -->
      <!-- 代码 开始 -->
<div id="leftsead">
  <ul>
    <li>
      <a href="javascript:void(0)" target="_blank">
        <div class="hides" style="width:161px;display:none;" id="qq">
          <div class="tell1 hides" id="p1">
            <img src="<?php echo $this->basePath();?>/images/phone.png">
          </div>
          <div class="hides" id="p2"><span style="color:#FFF;font-size:15px">4008383765</span>
          </div>
        </div>
        <img src="<?php echo $this->basePath();?>/images/phone.png" width="50" height="50" class="shows" />
      </a>
    </li>
        <li id="tel">
        <a href="mailto:kefu@kuaiyao.name">
            <div class="hides" style="width:161px;display:none;" id="tels">
                <div class="mess hides" id="p1">
                    <img src="<?php echo $this->basePath();?>/images/message.png">
                </div>
                <div class="hides" id="p3"><span style="color:#FFF;font-size:11px">kefu@kuaiyao.name</span>
                </div>
            </div>
        <img src="<?php echo $this->basePath();?>/images/message.png" width="50" height="50" class="shows" />
        </a>
        </li>
        <!-- <li id="btn">
        <a id="top_btn">
            <div class="hides" style="width:161px;display:none">
            </div>
            <img src="<?php echo $this->basePath();?>/images/man.png" width="50" height="50" />
        </a>
    </li> -->
    <li id="" style="padding-left:73px; width:100px;">
        <a style="margin-bottom:10px;" target="blank" href="tencent://message/?uin=3209147449&Site=www.luoxiao123.cn&Menu=yes">
            <img src="<?php echo $this->basePath();?>/images/qq.png" width="77" height="22" />
        </a>
        <a target="blank" href="tencent://message/?uin=3191853349&Site=www.luoxiao123.cn&Menu=yes">
            <img src="<?php echo $this->basePath();?>/images/qq.png" width="77" height="22" />
        </a>
    </ul>
</div>
      </div>
    </div>
</div>
<script>
$(document).ready(function(){
    $("#leftsead a").hover(function(){
        if($(this).prop("className")=="youhui"){
            $(this).children("img.hides").show();
        }else{
            $(this).children("div.hides").show();
            $(this).children("img.shows").hide();
            $(this).children("div.hides").animate({marginRight:'0px'},'0'); 
        }
    },function(){ 
        if($(this).prop("className")=="youhui"){
            $(this).children("img.hides").hide();
        }else{
            $(this).children("div.hides").animate({marginRight:'0px'},0,function(){$(this).hide();$(this).next("img.shows").show();});
        }
    });
    // $("#top_btn").click(function(){if(scroll=="off") return;$("html,body").animate({scrollTop: 0}, 600);});
      //右侧导航 - 二维码
        $(".youhui").mouseover(function(){
            $(this).children(".2wm").show();
        })
        $(".youhui").mouseout(function(){
            $(this).children(".2wm").hide();
        });
});
</script>
<!-- 代码 结束 -->
<!-- 右侧显示区域结束 -->
</div>
</body></html>