<!--[if IE 6]>
	<script src="js/pngAlaph.js" ></script> 
	<script> 
		DD_belatedPNG.fix('img');
	</script> 
<![endif]-->
<script>window["_GOOG_TRANS_EXT_VER"] = "1";</script><script type="text/javascript" id="b5mmain" src="<?php echo $this->basePath();?>/about/js/b5m.main.js"></script><link rel="stylesheet" href="<?php echo $this->basePath();?>/about/js/b5m-plugin.css" type="text/css"></head>
<body>
<!--  header -->



		<!--  banner -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1,user-scalable=ture">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/about/css/style(1).css">
<style type="text/css">
 .part_5_img01{
    margin-top: 73px;
  }
  .part_5_img01 img{
    width: 243px;
    height: 243px;
      }
    /*右侧css*/
    /* leftsead */
*html #leftsead{margin-top:258px;position:absolute;top:expression(eval(document.documentElement.scrollTop));}
#leftsead li{width:161px;height:78px;}
#leftsead li img{float:right;}
#leftsead li a{height:22px;float:right;display:block;min-width:47px;max-width:161px;}
#leftsead li a .shows{display:block;}
#leftsead li a .hides{cursor:pointer;cursor:hand;}
#leftsead li a.youhui .hides{display:none;position:absolute;right:143px;}
#leftsead li a.youhui .2wm{display:none;position:absolute;right:143px;}
#p2{width:120px;background-color:#f0b614;height:50px;margin-left:47px;line-height:50px;border-top-right-radius:24px;border-bottom-right-radius:24px;}
#p3{width:120px;background-color:#6c9;height:50px;margin-left:47px;line-height:50px;border-top-right-radius: 24px;border-bottom-right-radius: 24px;}
#p1{width:50px;height:50px;float:left}
#leftsead{
  width: 161px;
  height: 290px;
  position: fixed;
  top: 50%;
  right: 30px;
  z-index: 100;
  margin-top: -106px;
}
.tell1{
  background: #f0b614;
  border-top-left-radius:50%;
  border-bottom-left-radius:50%;
}
.mess{
  background: #6c9;
  border-top-left-radius:50%;
  border-bottom-left-radius:50%;
}
/*add关于我们*/
.bglogo{
  width: 100%;
  height: 12px;
  background: url(images/bglogo.png) repeat-x;
}
.content{
	width: 1200px;
	margin:80px auto;
}
.content h2{
	font-size: 20px;
	margin-bottom: 20px;
}
.content .introduce{
	text-indent: 2em;
	margin-bottom: 110px;
}
.content img{
	margin:0 8px;
}
.content .culture{
	margin:45px 0 95px 0;
}
.content .culture p{
	text-align: center;
}
.content .environment{
	margin:30px 0 90px 0;
	text-indent: 2em;
}
.content ul li{
	height: 25px;
	text-indent: 2em;
}
</style>
<div class="con">
    <div class="bglogo"></div>
    <div class="banner"><img src="<?php echo $this->basePath();?>/pc/images/BG.jpg" alt=""></div>
    <div class="bd">
    	<div class="content">
	        <h2>企业介绍</h2>
	        <p class="introduce">广东近场网络科技有限公司，致力于通过近距离通信技术与移动互联网融合的大数据为传统行业提供最前沿的互联网解决方案,是专注近距离通信产品研发、运营、营销与服务一体化网络科技解决供应商。针对不同行业客户需求进行深入的研究与分析，提供个性化的服务，满足企业客户发展需要，不断优化产品质量，务求让客户享受最高效、优质的服务。
			</p>
			<h2>近场文化</h2>
			<div>
				<img src="<?php echo $this->basePath();?>/pc/images/company1.jpg" alt="">
				<img src="<?php echo $this->basePath();?>/pc/images/company2.jpg" alt="">
				<img src="<?php echo $this->basePath();?>/pc/images/company3.jpg" alt="">
			</div>
			<div class="culture">
				<p>我们倡导快乐工作，每一位同事都是自己的伙伴。</p>
				<p>崇尚创新、诚信，在轻松的伙伴式工作氛围中为客户创造价值。</p>
				<p>我们以用户价值为依归，我们坚持“以人为本、合作共赢”的发展理念。</p>
			</div>
			<h2>公司环境</h2>
			<p class="environment">宽松的环境，轻松的氛围，在这里没有拘束，尽情施展你的才华，发挥创造力。</p>
			<h2>联系我们</h2>
			<ul>
				<li>地址:广州市荔湾区周门北路38号协晟大厦205室</li>
				<li>电话:400-838-3765</li>
				<li>微信公众号:快摇名片</li>
				<li>邮箱:kefu@kuaiyao.name</li>
			</ul>
		</div>

      <!-- 右侧显示区域开始 -->
      <!-- 代码 开始 -->
		<div id="leftsead">
		  <ul>
		    <li>
		      <a href="javascript:void(0)" target="_blank">
		        <div class="hides" style="width:161px;display:none;" id="qq">
		          <div class="tell1 hides" id="p1">
		            <img src="<?php echo $this->basePath();?>/images/phone.png">
		          </div>
		          <div class="hides" id="p2"><span style="color:#FFF;font-size:15px">4008383765</span>
		          </div>
		        </div>
		        <img src="<?php echo $this->basePath();?>/images/phone.png" width="50" height="50" class="shows" />
		      </a>
		    </li>
		        <li id="tel">
		        <a href="mailto:kefu@kuaiyao.name">
		            <div class="hides" style="width:161px;display:none;" id="tels">
		                <div class="mess hides" id="p1">
		                    <img src="<?php echo $this->basePath();?>/images/message.png">
		                </div>
		                <div class="hides" id="p3"><span style="color:#FFF;font-size:11px">kefu@kuaiyao.name</span>
		                </div>
		            </div>
		            <img src="<?php echo $this->basePath();?>/images/message.png" width="50" height="50" class="shows" />
		        </a>
		        </li>
		<!--         <li id="btn">
		        <a id="top_btn">
		            <div class="hides" style="width:161px;display:none">
		            </div>
		            <img src="<?php echo $this->basePath();?>/images/man.png" width="50" height="50" />
		        </a>
		    </li> -->
		    <li id="" style="padding-left:73px; width:100px;">
		        <a style="margin-bottom:10px;" target="blank" href="tencent://message/?uin=3209147449&Site=www.luoxiao123.cn&Menu=yes">
		            <img src="<?php echo $this->basePath();?>/images/qq.png" width="77" height="22" />
		        </a>
		        <a target="blank" href="tencent://message/?uin=3191853349&Site=www.luoxiao123.cn&Menu=yes">
		            <img src="<?php echo $this->basePath();?>/images/qq.png" width="77" height="22" />
		        </a>
		    </ul>
		</div>
    </div>
</div>

<script>
$(document).ready(function(){
    $("#leftsead a").hover(function(){
        if($(this).prop("className")=="youhui"){
            $(this).children("img.hides").show();
        }else{
            $(this).children("div.hides").show();
            $(this).children("img.shows").hide();
            $(this).children("div.hides").animate({marginRight:'0px'},'0'); 
        }
    },function(){ 
        if($(this).prop("className")=="youhui"){
            $(this).children("img.hides").hide();
        }else{
            $(this).children("div.hides").animate({marginRight:'0px'},0,function(){$(this).hide();$(this).next("img.shows").show();});
        }
    });
    // $("#top_btn").click(function(){if(scroll=="off") return;$("html,body").animate({scrollTop: 0}, 600);});
      //右侧导航 - 二维码
        $(".youhui").mouseover(function(){
            $(this).children(".2wm").show();
        })
        $(".youhui").mouseout(function(){
            $(this).children(".2wm").hide();
        });
});
</script>
<!-- 代码 结束 -->
<!-- 右侧显示区域结束 -->
</div>

</body></html>