<?php echo $this->headTitle('招商加盟'. $this->translate(''))->setSeparator(' - ')->setAutoEscape(false);?>
<?php echo $this->headMeta()->setName('description','猫王联盟——以“吃喝玩乐购”生活服务类打造实体店的免费O2O平台。为实体店搭建线上线下一体化平台；为消费者提供全国通积通用通兑积分平台，积分可线上兑换商品，线下抵现消费。服务热线4008-333-133')->setName('keywords','通用积分联盟,通用积分平台,通用积分商城,o2o积分联盟,o2o积分联盟网站,积分联盟商,生活服务'); ?>
<script>showmenu();</script>
<div class="content mt20">
    <div class="w bc clearfix">
        <ul class="join_items clearfix fr">
            <?php foreach($join as $k=>$v){?>
            <li class="fl ml10 <?php echo $k==0?'on':''; ?>"><a href="javascript:void(0);" class="tc f_color_white f15"><?php echo $v['title']?></a></li>
            <?php } ?>
        </ul>
    </div>
    <div class="join_box">

        <ul class="join w bc pt20 pb20">
            <?php foreach($join as $k=>$v){?>
            <li class="<?php echo $k != 0 ? 'none' : ''; ?>"><?php echo $v['content']?></li>
            <?php } ?>
        </ul>
    </div>
    <script type="text/javascript">
        $('.join_items li').click(function()
        {
            $(this).siblings().removeClass('on');
            $(this).addClass('on');
            $('.join_box li').hide();
            $('.join_box li').eq($(this).index()).show();
        })
    </script>
</div>