<!-- Responsive Table -->
<!-- Table exporting -->
<style>
	.row{display:none;}
</style>
<?php //echo '<pre>'; print_r($list);exit; ?>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
			<a href="<?php echo $this->url('admin-card',array('cid'=>0))?>">
				<button class="btn btn-large <?php if($_SESSION['cid']==0){?>btn-info<?php }?>">未绑定</button>
			</a> <a href="<?php echo $this->url('admin-card',array('cid'=>1))?>">
				<button class="btn btn-large <?php if($_SESSION['cid']==1){?>btn-info<?php }?>">已绑定</button>
			</a> <a class="btn btn-info"
				style="color: #ffffff; margin-left: 30px;"
				href="<?php echo $this->url('admin-card',array('action'=>'addUser'));?>">新增名片</a>
		</h3>
		<div style="float:right; width:450px;">
			<form class="form-horizontal"
				  action="<?php echo $this->url('admin-card',array('action'=>'index'))?>"
				  method="post" style="float: left; margin-right: 30px;">
				<!--<input type="radio" name="blind" value="1" checked>已绑定
				<input type="radio" name="blind" value="0">未绑定-->
				<span style="font-weight: bold; font-size: 14px;"> 搜索全表</span>
				：
				<input type="text" name="keyword" value="<?php echo $keyword?>"
					   placeholder="姓名,公司，手机，ID">
				<input type="hidden" name="cid" value="<?php echo $_SESSION['cid'];?>">
				<input type="submit" name="submit" value="搜索" class="btn btn-info"
					   style="height: 25px; width: 60px; line-height: 25px; padding: 0; margin-left: 10px; margin-top: 5px;" />
			</form>

			<div class="panel-options">

				<a href="#" data-toggle="panel"> <span class="collapse-icon">&ndash;</span>
					<span class="expand-icon">+</span>
				</a> <a href="#" data-toggle="remove"> &times; </a>
			</div>
		</div>
	</div>
	<div class="panel-body">
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>ID</th>
					<th>姓名</th>
					<th>个人信息</th>
					<th>更新时间</th>
					<th>绑定设备</th>
					<th>操作</th>
					<!--<th>设置公司管理人</th>-->
				</tr>
			</thead>
			<tbody>
			<?php //print_r($carte_info);?>
            <?php if(isset($carte_info)){?>
            <?php foreach($carte_info as $v){?>
                <tr>
					<td><?php echo $v->id; ?></td>
					<td><?php echo $v->name; ?></td>
					<td>
						<div
							style="width: 60px; height: 60px; float: left; margin-right: 10px;">
							<img width="60" height="60"
								src="<?php echo isset($carte_head_icon[$v->head_icon])?$carte_head_icon[$v->head_icon]['path']:''; ?>"
								alt="" />
						</div> <span>公司：</span> <span><?php echo $v->company; ?></span><br />
						<span>职位：</span> <span><?php $pos = explode(',',$v->position); echo $pos[0]; ?></span><br />
						<span>联系电话：</span> <span><?php $mob = explode(',',$v->mobile); echo $mob[0]; ?></span><br />
					</td>
					<td><?php echo $v->timestamp_update; ?></td>
					<td>
                        <?php if($v->status == 0){?>
                        <form
							action="<?php echo $this->url('admin-card',array('action'=>'carteListBindDevice')); ?>"
							method="post">
							<label><input type="text" name="id" placeholder="请输入设备ID"/></label> <label><input
								type="hidden" name="carte_id" value="<?php echo $v->id; ?>" /></label>
							<label><input type="hidden" name="bind" value="1" /></label> <label><input
								class="btn btn-info" type="submit" name="submit" value="绑定设备" /></label>
						</form>
                        <?php }else{ ?>
                        
                        <form
							action="<?php echo $this->url('admin-card',array('action'=>'carteListBindDevice')); ?>"
							method="post">
							<label><input type="text" value="<?php echo isset($device_arr[$v->status]) ? $device_arr[$v->status] : '' ; ?>"
								disabled /></label> <label><input type="hidden" name="id"
								value="<?php echo isset($device_arr[$v->status]) ? $device_arr[$v->status] : '' ;?>" /></label> <label><input
								type="hidden" name="carte_id" value="<?php echo $v->id; ?>" /></label>
							<label><input type="hidden" name="bind" value="0" /></label>
							<label><input class="btn btn-danger" type="submit" name="submit" value="解除绑定" onclick="return cfm()" /></label>
						</form>
                        <?php } ?>
                    </td>
					<td><a class="btn btn-info"
						href="<?php echo $this->url('admin-card',array('action' =>'addUser','id'=>$v->id)); ?>">编辑</a>
						<a class="btn btn-danger" href="javascript:void(0)"
						onclick="show_confirm_message('<?php echo $this->url('admin-card',array('action' =>'delUser','id'=>$v->id)); ?>','确定删除此用户资料吗？')">删除</a>
					</td>
					<!--<td>
							<div class="ww">

								<input type="text" class="setup-company" style="width:250px;" name="company" value="<?php /*echo isset($v['company1']) ? $v['company1'] : '';*/?>" placeholder="请输入公司">
								<input class="idss" type="hidden" value="<?php /*echo $v['id'];*/?>" name="cardId" id="cardId">
								<button onclick="blind(this)">设置为公司管理人</button>
								<?php /*if(isset($v['company1'])){*/?>
								<button class="click1" onclick="cancel(this)">撤销</button>
								<?php /*}*/?>

							</div>
					</td>-->

				</tr>
            <?php }}?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-card','condition'=>$condition));?>       </div>
</div>
<script type="text/javascript">

    function cfm()
    {
        return confirm('确认解除绑定？');
    }

	/*function cancel(obj){
		var company= $(obj).siblings('.setup-company').val();
		var cId= $(obj).siblings('.idss').val();
		$.post('<?php echo $this->url('admin-card',array('action'=>'cancel'))?>',{id:cId , company: company},function(data){
			if(data==1)
			{
				alert('撤销成功');
				location.reload();
			}else
			{
				alert('撤销失败');
			}
		});
	}

	function blind(obj){
		var company=$(obj).siblings('.setup-company').eq(0).val();
		var id=$(obj).siblings('.idss').eq(0).val();
		$.post('<?php echo $this->url('admin-card',array('action'=>'setup'));?>',{id: id, company: company},function(data){
			if(data==1)
			{
				alert('设置成功');
				location.reload();
			}else
			{
				alert('设置失败');
			}
		});
	}*/


</script>