    <div class="banner">
        <?php if(!$special_page): ?>
        <img style="width:100%; height:400px;" src="<?php echo $ads_info ? ROOT_PATH.UPLOAD_PATH.$ads_info->path.$ads_info->filename : ''?>" alt="" />
        <?php else: ?>
        <div class="tra-btn clearfix">
            <a href="<?php echo $this->url('index' , array('controller' => 'user' , 'action' => 'index'))?>" class="platform fl">
                进入交易平台
            </a>
            <div class="download fr">下载app</div>
        </div>
        <?php endif; ?>
    </div>
    <?php echo $information->content;?>
