<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width,inital-scale=1.0,minimum-scale=1.0,maximum-scale=1.0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-status-bar-style" content="black" />
		<meta name="format-detection" content="telephone=no" />
		<title><?php echo WEB_TITLE?></title>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/platform/base.css">
		<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/css/platform/index.css">
	</head>
	<body class="bg_gray mwhome">
<!--		<header class="app_head">
			<div class="app_head_content app_wrap">
				<div class="go_back" onclick="window.history.go(-1)">
					<div class="icon_goback"></div>
				</div>
 				<div class="title">
					<p>资讯详情</p>
				</div>
				<div class="share">
					<div class="btn_share" onclick="">
					</div>
				</div>
			</div> 
		</header>-->
		<section class="app_section">
		      <?php echo $detail; ?>
			<!-- <div class="app_article_title">
				吉宏本周商品强烈推荐，超多选择，超多优惠，欢迎大家选购！
			</div>
			<div class="app_article_theme clearfix">
				<span class="article_time">2016.07.19</span>
				<span class="article_readnum">546464464</span>
				<span class="article_source">平台新闻</span>
			</div>
			<div class="article_content clearfix">
				<div class="article__text">
					<img src="../images/article_img.png">
					<img src="../images/article_img.png">
					<img src="../images/article_img.png">
					<img src="../images/article_img.png">
					<p>宏平台有多种鲜活植物上架热销，各种观花、各种观叶植物，选择多多，品质优良，任君选择！欢迎各位会员前来选购！</p>
					<p>吉宏平台有多种鲜活植物上架热销，各种观花、各种观叶植物，选择多多，品质优良，任君选择！欢迎各位会员前来选购！</p>
				</div>
			</div> -->
		</section>
	</body>
</html>