        <div class="user_content_right">
            <!-- 商品对账单详情 -->
            <section class="none">
                <div class="clear"></div>
                <div class="release_message" style="margin-top:0;">
                    <h2>发布信息</h2>
                    <ul>
                        <li>
                            <div class="message_label">发布编号</div>
                            <div class="message_text">352565458565</div>
                        </li>
                        <li>
                            <div class="message_label">发布时间</div>
                            <div class="message_text">2016-06-13 12：12：50</div>
                        </li>
                        <li class="leave_message">
                            <div class="message_label">发布留言</div>
                            <div class="message_text">最好一周内联系我最好一周内联系我最好一周内联系我最好一周内联系我最好一周内联系我最好一周内联系我</div>
                        </li>
                    </ul>
                </div>
                <div class="clear"></div>
                <div class="goods_message">
                    <h2>商品信息</h2>
                    <ul>
                        <li>
                            <div class="message_label">商品名称</div>
                            <div class="message_text message_name">发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树</div>
                        </li>
                        <li>
                            <div class="message_label">盆径规划</div>
                            <div class="message_text">115mm</div>
                        </li>
                        <li>
                            <div class="message_label">商品分类</div>
                            <div class="message_text">发财树-小森林系列</div>
                        </li>
                        <li>
                            <div class="message_label">质量等级</div>
                            <div class="message_text">A级</div>
                        </li>
                        <li>
                            <div class="message_label">植株高度</div>
                            <div class="message_text">260mm</div>
                        </li>
                        <li>
                            <div class="message_label">植株冠幅</div>
                            <div class="message_text">5</div>
                        </li>
                        <li>
                            <div class="message_label">供应数量</div>
                            <div class="message_text">256盆</div>
                        </li>
                        <li>
                            <div class="message_label">上架方式</div>
                            <div class="message_text">预售<i>  (可出货时间:2016-10-23)</i></div>
                        </li>
                        <li>
                            <div class="message_label">商品总价</div>
                            <div class="message_text">￥720.0</div>
                        </li>
                        <li>
                            <div class="message_label">装箱数</div>
                            <div class="message_text">10盆/箱</div>
                        </li>
                        <li class="leave_message">
                            <div class="message_label">商品介绍</div>
                            <div class="message_text">在感情面前，谈什么自我在感情面前，谈什么自我在感情面前，谈什么自我在感情面前，谈什么自我在感情面前，谈什么自我在感情面前，谈什么自我在感情面前，谈什么自我在感情面前，谈什么自我在感情面前，谈什么自我</div>
                        </li>
                    </ul>
                </div>
            </section>
            <!-- 商品对账单详情 -->
            <!-- 资材对账单详情 -->
            <section class="materials">
            <div class="order_message" style="margin-top:0;">
                <h2>订单信息</h2>
                <ul>
                    <li>
                        <div class="message_label">订单号</div>
                        <div class="message_text">352565458565</div>
                    </li>
                    <li>
                        <div class="message_label">订货时间</div>
                        <div class="message_text">2016-12-23 12：22：30</div>
                    </li>
                    <li>
                        <div class="message_label">订单金额</div>
                        <div class="message_text">￥22.0</div>
                    </li>
                    <li>
                        <div class="message_label">商品数量</div>
                        <div class="message_text">220</div>
                    </li>
                    <li>
                        <div class="message_label">收货人</div>
                        <div class="message_text">张三</div>
                    </li>
                    <li>
                        <div class="message_label">联系电话</div>
                        <div class="message_text">18816782913</div>
                    </li>
                    <li class="address"> 
                        <div class="message_label">送货地址</div>
                        <div class="message_text">广东省广州市荔湾区周门北路38号协晟大厦208室</div>
                    </li>
                    <li>
                        <div class="message_label">订单状态</div>
                        <div class="message_text">已完成</div>
                    </li>
                </ul>
            </div>
            <div class="clear"></div>
            <div class="goods_mess mt40">
            <h2>商品信息</h2>
            <div class="my_goods_content fl">
              <ul class="goods_label">
                <li class="name">商品</li>
                <li class="price">单价</li>
                <li class="amount">数量</li>
                <li class="money">金额</li>
              </ul>
              <ul class="goods_details">
                <li>
                  <div class="name">
                    <div class="img">
                      <a><img src="../images/goods_img.png"></a>
                    </div>
                    <div class="goods_name">
                      <h3>发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树</h3>
                      <p>规格:90#A级</p>
                      <p>型号</p>
                    </div>
                  </div>
                  <div class="price">7.4</div>
                  <div class="amount">10</div>
                  <div class="money"><i>￥79.0</i></div>
                </li>
                <li>
                  <div class="name">
                    <div class="img">
                      <a><img src="../images/goods_img.png"></a>
                    </div>
                    <div class="goods_name">
                      <h3>发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树发财树</h3>
                      <p>规格:90#A级</p>
                      <p>型号</p>
                    </div>
                  </div>
                  <div class="price">7.4</div>
                  <div class="amount">10</div>
                  <div class="money"><i>￥79.0</i></div>
                </li>
              </ul>
            </div>
            <div class="clear"></div>
            </section>
            <!-- 资材对账单详情 -->
        </div>
    </div>
</div>
<div class="clear"></div>
<div class="wrap">
   <div class="order_all_money">
     <p class="goods_all_num">商品总数：25</p>
     <p>订单总额：<i>750.0</i>元</p>
     </div>
 </div>

<script type="text/javascript">
$(function(){
    $('.user_center ul li').click(function(){
        $(this).addClass('on').siblings().removeClass('on');
    })
})
</script>