<style>
    .tl{text-align: right;}
    .main-nody{padding:5px 20px 0 20px;}
    .main-nody h5{float: left;}
    .tp{margin-top: 30px;}
    .bc-1{display: none;}
    .fl{float: left;}
</style>
<div class="panel panel-default">
   <div class="panel-heading">
       <div calss="row">
           <div class="col-sm-6">
               <span> 商品详情：</span>
           </div>
       </div>
   </div>
    <div class="pannel-body main-nody">
        <div class="row">
            <div class="col-lg-12">
                <h5>基本信息</h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4" >
                    <tbody>
                        <tr>
                            <td>商品名称</td>
                            <td>
                                <input type="text" name="goodsName" value=" 文心兰-光华">
                            </td>
                        </tr>
                        <tr>
                            <td>下单时间</td>
                            <td>2016-06-14 12:05:34</td>
                        </tr>
                        <tr>
                            <td>支付方式</td>
                            <td>余款支付<span style="color:red">（余款不足，请修改订单）</span></td>
                        </tr>
                        <tr>
                            <td> 企业名称</td>
                            <td>爱特安为网络技术有限公司</td>
                        </tr>
                        <tr>
                            <td> 联系人</td>
                            <td>李四</td>
                        </tr>
                        <tr>
                            <td>联系电话</td>
                            <td>1388888888</td>
                        </tr>
                        <tr>
                            <td> 收货地址</td>
                            <td>广州市荔湾区协晟大厦208室</td>
                        </tr>
                        <tr>
                            <td>订单留言</td>
                            <td>希望尽快发货，最好发申通</td>
                        </tr>
                        <tr>
                            <td>订单状态</td>
                            <td> <span style="color:red">待审核</span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row tp">
            <div class="col-lg-12">
                <h5>商品信息</h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4" >
                    <thead>
                        <tr>
                            <th>商品名称</th>
                            <th>规格等级</th>
                            <th>型号</th>
                            <th>购买数量</th>
                            <th>修改数量</th>
                            <th>单价</th>
                            <th>修改单价</th>
                            <th>装箱数</th>
                            <th>件数</th>
                            <th>金额</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>红掌-阿拉巴马</td>
                            <td>140#/A级</td>
                            <td>bymp</td>
                            <td>300</td>
                            <td><input type="" name="" value=""><input type="button" value="修改" class="btn btn-info"" ></td>
                            <td>300</td>
                            <td><input type="" name="" value=""><input type="button" value="修改" class="btn btn-info""></td>
                            <td>20</td>
                            <td>15</td>
                            <td>3600.0</td>
                        </tr>
                        <tr>
                            <td>红掌-阿拉巴马</td>
                            <td>140#/A级</td>
                            <td>bymp</td>
                            <td>300</td>
                            <td><input type="" name="" value=""><input type="button" value="修改" class="btn btn-info""></td>
                            <td>300</td>
                            <td><input type="" name="" value=""><input type="button" value="修改" class="btn btn-info""></td>
                            <td>20</td>
                            <td>15</td>
                            <td>3600.0</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>


        <div class="row tp">
            <div class="col-lg-12">
                <h5>订单操作</h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4">
                    <tbody>
                        <tr>
                            <td width="10%;">管理员备注</td>
                            <td>
                                <textarea height="26px" cols="100%"></textarea>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
        
        <div class="row">
            <div class="col-lg-12">
                <h5></h5>
            </div>
            <div class="col-lg-12">
                <table class="table table-striped" id="example-4">
                    <tbody>
                        <tr>
                            <td>
                                <input type="button" value="审核不通过" class="btn btn-info" >
                                <input type="button" value="审核通过" class="btn btn-info" >
                                <input type="button" value="修改订单" class="btn btn-info" >
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>