<script src="<?php echo $this->basePath();?>/js/admin/jedate.min.js"></script>
<style>
    .fl{
    	float: left;
    }
	.dataTables_info{
		display:none;
	}
	.dataTables_paginate{
		display: none;
	}
	.bc-1{display: none;}
	.col-sm-5{display: none;}
	.col-sm-7{display:none;}
	.pl10{
		padding-left:10px;
	}
	.lh60{
		line-height:60px;
	}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
		<a href="<?php echo $this->url('admin-goods' , array('action' => 'index'));?>">商品管理 </a> / <a href="">可上架商品管理</a>        
		</h3>
	</div>

	<div class="panel-body">
	    <div class="" style="float:right;">
            <form class="form-horizontal" action="<?php $this->url('admin-goods' , array('action' => 'shelvesManage')) ?>" method="get" style="float: left; margin-left: 20px;">
            <span style="font-weight: bold; font-size: 14px;">发布日期：</span>
            <input type="text"  style="line-height: 22px"  name="start_time" readonly id="start_time" class="datainp" placeholder="请选择" value="<?php echo isset($start_time) ? $start_time :''?>"/>
            <span style="font-weight: bold; font-size: 14px;">到：</span>
			<input type="text"  style="line-height: 22px"  name="end_time"  readonly id="end_time"  class="datainp" placeholder="请选择" value="<?php echo isset($end_time) ? $end_time :''?>"/>
			<span style="font-weight: bold; font-size: 14px;"> 关键词 :</span>
			<input type="text" name="keyword" value="<?php echo isset($keyword) ? $keyword :''?>" placeholder="请输入商品名称/商品编号搜索" style="line-height: 26px" >
			<select style="padding: 5px" name="status">
			     <option value="0">全部状态</option>
			     <?php foreach ($goodsStatus as $m=>$n){?>
				 <option value="<?php echo $m?>" <?php echo isset($status) && $status == $m ? 'selected' : ''?>><?php echo ($m == 3) ? '已上架' : $n?></option>
				 <?php }?>
			</select>
			<input type="submit"  value="搜索" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
		    </form>
    	</div>
    	<div style="clear:both;"></div>
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>商品编号</th>
					<th>商品名称</th>
					<th>盆径规格(mm)</th>
					<th>商品单价</th>
					<th>供应数量</th>
					<th>销售数量</th>
					<th>上架方式</th>
					<th>商品状态</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			<?php if(!empty($goods)):?>
			<?php foreach ($goods as $v){?>
                <tr class="tr_list">
                    <td style="padding-top:31px;"><?php echo $v->goods_sn?></td>
					<td >
    					<a href="">
                            <img class="fl" src="<?php echo !empty($v->oneImage_path) ? ROOT_PATH . UPLOAD_PATH.$v->oneImage_path : ROOT_PATH . UPLOAD_PATH.'images/no_pic.gif'; ?>">
                            <span class="pl10 lh60"><?php echo $v->name?></span>
                        </a>
					</td>
					<td style="padding-top:31px;"><?php echo $v->spec_size?></td>
					<td style="padding-top:31px;"><?php echo $v->min_cash .'-' .$v->max_cash ?></td>
					<td style="padding-top:31px;"><?php echo $v->number?></td>
					<td style="padding-top:31px;"><?php echo $v->sale_number?></td>
					<td style="padding-top:31px;">
					<?php foreach ($salse_type as $m => $n){?>
					<?php if($m == $v->salse_type):?>
					<?php echo $n;?>
					<?php endif;?>
					<?php }?>
					</td>
					<td style="padding-top:31px;">
					<?php foreach ($goodsStatus as $m=>$n){?>
					<?php if($m == $v->status):?>
					<?php echo ($v->status == 3) ? '已上架' : $n;?>
					<?php endif;?>
					<?php }?>
					</td>
					<td style="padding-top:24px;">
					   <a href="<?php echo $this->url('admin-goods' , array('action' => 'shelvesDetail','id'=>$v->id)); ?>" class="btn btn-info">查看</a>
					 </td>
				</tr>
			<?php }?>
			<?php endif;?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-goods','condition'=>$condition));?>       </div>
</div>
<script type="text/javascript">
    jeDate({
		dateCell:"#start_time",
		format:"YYYY-MM-DD hh:mm:ss",
		isinitVal:false,
		isTime:true, //isClear:false,
		minDate:"1970-01-01 00:00:00",
		//okfun:function(val){ alert(val)}
	});
    jeDate({
		dateCell:"#end_time",
		format:"YYYY-MM-DD hh:mm:ss",
		isinitVal:false,
		isTime:true, //isClear:false,
		minDate:"1970-01-01 00:00:00",
		//okfun:function(val){alert(val)}
	})
</script>