<style>
    .tl{text-align: right;}
    .main-nody{padding:5px 20px 0 20px;}
    .main-nody h5{float: left;}
    .tp{margin-top: 30px;}
    .bc-1{display: none;}
    .fl{float: left;}
    .pd5{
        padding:5px;	
    }
    .w450{
	   width:450px;
    }
</style>
<script src="<?php echo $this->basePath();?>/kindeditor/kindeditor.js"></script>
<div class="panel panel-default">
   <div class="panel-heading">
       <div calss="row">
           <div class="col-sm-6">
               <a href="<?php echo $this->url('admin-information' , array('action' => 'platformInformation'));?>">信息管理 </a> 
               / <a href="<?php echo $this->url('admin-information' , array('action' => 'platformInformation'));?>">平台信息</a>
               /
               <?php if(isset($id) && $id): ?> 
               <a href="">编辑消息</a>    
               <?php else: ?>
               <a href="">新增消息</a>    
               <?php endif;?>
           </div>
       </div>
   </div>
    <div class="pannel-body main-nody">
            <?php if($id){ ?>
            <form class="form-horizontal" action="<?php echo $this->url('admin-information' , array('action' =>'editPlatformInformation')); ?>" method="post" >
            <?php }else{ ?>
            <form class="form-horizontal" action="<?php echo $this->url('admin-information' , array('action' =>'addPlatformInformation')); ?>" method="post" >
            <?php } ?>
            <div class="row">
                <div class="col-lg-12">
                   <?php if(isset($id) && $id): ?> 
                   <h5>编辑消息</h5>
                   <?php else: ?>
                   <h5>新增消息</h5>
                   <?php endif;?>
                </div>
                <div class="col-lg-12">
                
                    <table class="table table-striped" id="example-4" >
                        <tbody>
                            <tr>
                                <td>消息标题</td>
                                <td>
                                    <input type="text" name="title" value="<?php echo isset($information_info->title)? $information_info->title :'' ?>" class="pd5 w450"  required>
                                </td>
                            </tr>
                            <tr>
                                <td>消息简介(不大于255字数)</td>
                                <td>
                                    <textarea id="" maxlength="255" name="description" style="width:500px;height:150px;"><?php echo isset($information_info->description)? $information_info->description :''; ?></textarea>
                                </td>
                            </tr>
                            <tr>
                                <td>消息内容</td>
                                <td>
                                    <textarea id="editor_id" name="content" style="width:1000px;height:600px;"><?php echo isset($information_info->content)? $information_info->content :''; ?></textarea>
                                </td>
                            </tr>
                            <tr>
                                <td>APP端消息内容</td>
                                <td>
                                    <textarea id="app_editor_id" name="app_content" style="width:1000px;height:600px;"><?php echo isset($information_info->app_content)? $information_info->app_content :''; ?></textarea>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            
            <div class="row tp">
                <div class="col-lg-12">
                    <h5>
                        <input type="hidden" value="<?php echo isset($id)? $id : ''; ?>" name="id" >
                        <button type="submit" name="submit" value="提交"  class="btn btn-info btn-large">提交</button>
                     </h5>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    KindEditor.ready(function(K) {
        window.editor = K.create('#editor_id', {
            filterMode: false,//是否开启过滤模式
        });
    });
    KindEditor.ready(function(K) {
        window.editor = K.create('#app_editor_id', {
            filterMode: false,//是否开启过滤模式
        });
    });
</script>