<style>
	.dataTables_info{
		display:none;
	}
	.dataTables_paginate{
		display: none;
	}
	.bc-1{display: none;}
	.col-sm-5{display: none;}
	.col-sm-7{display:none;}
	.fl{
		float:left;
	}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
        <a href="">信息管理 / <a href="">平台消息</a>
		</h3>
	</div>
	
	<div class="panel-body">
	    <div class="fl" >
		    <a class="btn btn-info fl " href="<?php echo $this->url('admin-information' , array('action' => 'platformInformationOperate')) ?>" >添加消息</a>
		</div>
    	<div class="" style="float:right;">
            <form class="form-horizontal" action="<?php $this->url('admin-information' , array('action' => 'platformInformation')) ?>" method="get" style="float: left; margin-left: 20px;">
			<span style="font-weight: bold; font-size: 14px;"> 关键词 :</span>
			<input type="text" name="keyword" value="<?php echo isset($keyword) ? $keyword :''?>" placeholder="请输入标题搜索" style="line-height: 26px" >
			<input type="submit"  value="搜索" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
		    </form>
    	</div>
    	<div style="clear:both;"></div>
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>编号</th>
					<th>消息标题</th>
					<th>创建时间</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			    <?php foreach ($information_list as $value): ?>
                <tr class="tr_list" valign="middle">
					<td style="padding-top:18px;"><?php echo $value->id ; ?></td>
					<td style="padding-top:18px;"><?php echo $value->title ; ?></td>
					<td style="padding-top:18px;"><?php echo $value->timestamp ; ?></td>
					<td>
					   <a href="<?php echo $this->url('admin-information' , array('action' => 'platformInformationOperate' , 'id' => $value->id)) ?>" class="btn btn-info">编辑</a>
					   <a href="#" onclick="show_confirm('<?php echo $this->url('admin-information' , array('action' => 'deletePlatformInformation' , 'id' => $value->id)); ?>')" class="btn btn-info">删除</a>
					 </td>
				</tr>
				<?php endforeach;?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-information','condition'=>$condition));?>       </div>
</div>

<script>
function show_confirm(url)
{
	if(confirm('确认删除？'))
	{
		location.href = url;
	}
	else
	{
		return false;
	}
}
</script>