<?php //echo $this->headLink()->appendStylesheet($this->basePath() . '/css/admin/uploadify.css');?>
<!-- <script src="<?php //echo $this->basePath();?>/js/admin/jquery.uploadify-3.1.min.js"></script>
<script src="<?php //echo $this->basePath();?>/js/admin/Uploads.js"></script> -->
<script src="<?php echo $this->basePath();?>/js/admin/ajaxfileupload.js"></script><!-- //上传JS -->
<script src="<?php echo $this->basePath();?>/js/admin/jedate.min.js"></script>
<script type="text/javascript">
//var swf ='<?php //echo $this->basePath() . '/js/admin/uploadify.swf'?>';
var url = '<?php echo $this->url('admin-common',array('action'=>'getAdminFile')) ;?>';
</script>
<!-- 图片上传样式 -->
<style>
<style>
    .tl{text-align: right;}
    .main-nody{padding:5px 20px 0 20px;}
    .main-nody h5{float: left;}
    .tp{margin-top: 30px;}
    .bc-1{display: none;}
    .fl{float: left;}
    .pd5{
        padding:5px;	
    }
</style>
<script src="<?php echo $this->basePath();?>/kindeditor/kindeditor.js"></script>
<div class="panel panel-default">
   <div class="panel-heading">
       <div calss="row">
           <div class="col-sm-6">
               <a href="<?php echo $this->url('admin-information' , array('action' => 'platformInformation'));?>">信息管理 </a> 
               / <a href="<?php echo $this->url('admin-information' , array('action' => 'CoProducer'));?>">生产商管理</a> 
               / 
               <?php if(isset($id) && $id): ?> 
               <a href="">编辑生产商</a>    
               <?php else: ?>
               <a href="">新增生产商</a>    
               <?php endif;?>
           </div>
       </div>
   </div>
    <div class="pannel-body main-nody">
        <?php if($id){ ?>
        <form class="form-horizontal" action="<?php echo $this->url('admin-information' , array('action' =>'editProducer')); ?>" method="post"  enctype="multipart/form-data">
        <?php }else{ ?>
        <form class="form-horizontal" action="<?php echo $this->url('admin-information' , array('action' =>'addProducer')); ?>" method="post"  enctype="multipart/form-data">
        <?php } ?>
            <div class="row">
                <div class="col-lg-12">
                    <h5>生产商信息</h5>
                </div>
                <div class="col-lg-12">
                    <table class="table table-striped" id="example-4" >
                        <tbody>
                            <tr>
                                <td>生产商名称</td>
                                <td>
                                    <input type="text" name="name" value="<?php echo isset($producer_info->name) ? $producer_info->name :'' ?>"  class="pd5" >
                                </td>
                            </tr>
                            <tr>
                                <td>排序编号</td>
                                <td>
                                    <input type="number" min="0" name="sort" value="<?php echo isset($producer_info->sort) ? $producer_info->sort :''?>" class="pd5" >
                                    <span> 编号越小，顺序越靠前</span>
                                </td>
                            </tr>
                            <tr>
                                <td>生产商图片</td>
                                <td>
                                    <input type="file" id="img0" name="Filedata" onchange="return ajaxFileUpload('0');"  value="选择图片" />
                                    <input type="hidden" name="image" value="<?php echo isset($image) ? $image['id'] : ''?>" id="img_id_0" /> <br />
                                    <span style="clear: both;">
        							     <img src="<?php if($image){echo ROOT_PATH.UPLOAD_PATH.$image['path'].$image['filename'];}else{echo ROOT_PATH . 'images/no_pic.gif';}?>" width="200" height="200" id="img_0" />
        							</span>
                                    <!-- </div> -->
                                </td>
                            </tr>
                            <tr>
                                <td>生产商简介</td>
                                <td>
                                    <textarea name="description" style="width:700px;height:300px;"><?php echo isset($producer_info->description)? $producer_info->description :''; ?></textarea>
                                </td>
                            </tr>
                            <tr>
                                <td>生产商介绍</td>
                                <td>
                                    <textarea id="editor_id" name="content" style="width:700px;height:300px;"><?php echo isset($producer_info->content)? $producer_info->content :''; ?></textarea>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            
            <div class="row tp">
                <div class="col-lg-12">
                    <h5>
                        <input type="hidden" value="<?php echo isset($id) ? $id :'';?>" name="id">
                        <button type="submit" name="submit"  value="提交" class="btn btn-info btn-large">提交</button>
                     </h5>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
    KindEditor.ready(function(K) {
        window.editor = K.create('#editor_id', {
            filterMode: false,//是否开启过滤模式
        });
    });
</script>

<script type="text/javascript">
    jeDate({
		dateCell:"#start_time",
		format:"YYYY-MM-DD hh:mm:ss",
		isinitVal:true,
		isTime:true, //isClear:false,
		minDate:"1970-01-01 00:00:00",
		//okfun:function(val){ alert(val)}
	});
    jeDate({
		dateCell:"#end_time",
		format:"YYYY-MM-DD hh:mm:ss",
		isinitVal:true,
		isTime:true, //isClear:false,
		minDate:"1970-01-01 00:00:00",
		//okfun:function(val){alert(val)}
	})
</script>