<style>
	.dataTables_info{
		display:none;
	}
	.dataTables_paginate{
		display: none;
	}
	.bc-1{display: none;}
	.col-sm-5{display: none;}
	.col-sm-7{display:none;}
	.fl{
		float:left;
	}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
        <a href="">信息管理 / <a href="">招聘管理</a>
		</h3>
	</div>
	
	<div class="panel-body">
	    <div class="fl" >
		    <a class="btn btn-info fl " href="<?php echo $this->url('admin-information' , array('action' => 'recruitOperate')) ?>" >添加职位</a>
		</div>
		<div class="" style="float:right;">
            <form class="form-horizontal" action="<?php $this->url('admin-information' , array('action' => 'recruit')) ?>" method="get" style="float: left; margin-left: 20px;">
			<span style="font-weight: bold; font-size: 14px;"> 关键词 :</span>
			<input type="text" name="keyword" value="<?php echo isset($keyword)?$keyword:''?>" placeholder="请输入职位名称搜索" style="line-height: 26px" >
			<select style="padding: 5px" name="status">
			     <option value="0">全部职位</option>
			     <option value="1" <?php echo isset($status) && $status == 1?'selected':''?>>招聘中</option>
			     <option value="2" <?php echo isset($status) && $status == 2?'selected':''?>>不显示</option>
			</select>
			<input type="submit"  value="搜索" class="btn btn-info" style="height: 26px; width: 60px; line-height: 26px; padding: 0; margin-left: 10px; margin-top: 5px;" />
		    </form>
    	</div>
    	<div style="clear:both;"></div>
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>职位名称</th>
					<th>最低学历</th>
					<th>工作年限</th>
					<th>工作地点</th>
					<th>排序</th>
					<th>发布时间</th>
					<th>状态</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			     <?php foreach ($recruit_list as $value): ?>
                <tr class="tr_list" valign="middle">
					<td style="padding-top:18px;"><?php echo $value->name?></td>
					<td style="padding-top:18px;"><?php echo $education[$value->education]?></td>
					<td style="padding-top:18px;"><?php echo $yearsOfWorking[$value->work_limit]?></td>
					<td style="padding-top:18px;"><?php echo $value->address;?></td>
					<td style="padding-top:18px;"><?php echo $value->sort?></td>
					<td style="padding-top:18px;"><?php echo $value->timestamp?></td>
					<td style="padding-top:18px;"><?php echo $value->status == 1 ? '显示' : '不显示'?></td>
					<td>
					   <a href="<?php echo $this->url('admin-information' , array('action' => 'recruitOperate' , 'id' => $value->id)) ?>" class="btn btn-info">编辑</a>
					   <?php if($value->status == 1): ?>
					   <a href="<?php echo $this->url('admin-information' , array('action' => 'updateRecruitStatus' , 'id' => $value->id ,'status'=>'2')) ?>" class="btn btn-info">不显示</a>
					   <?php else: ?>
					   <a href="<?php echo $this->url('admin-information' , array('action' => 'updateRecruitStatus' , 'id' => $value->id ,'status'=>'1')) ?>" class="btn btn-info">显示</a>
					   <?php endif; ?>
					    <a href="#" onclick="show_confirm('<?php echo $this->url('admin-information' , array('action' => 'deleteRecruit' , 'id' => $value->id)); ?>')" class="btn btn-info">删除</a>
					 </td>
				</tr>
				<?php endforeach;?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-order','condition'=>$condition));?>       </div>
</div>

<script>
function show_confirm(url)
{
	if(confirm('确认删除？'))
	{
		location.href = url;
	}
	else
	{
		return false;
	}
}
</script>