<!-- Responsive Table -->
<!-- Table exporting -->
<style>
	.row{
		display:none;
	}
</style>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
			<a href="<?php echo $this->url('admin-invitation',array('cid'=>0))?>">
				<button class="btn btn-large <?php if($cid==0){?>btn-info<?php }?>">未使用</button>
			</a>
			<a href="<?php echo $this->url('admin-invitation',array('cid'=>1))?>">
				<button class="btn btn-large <?php if($cid==1){?>btn-info<?php }?>">已使用</button>
			</a>
			<button class="btn btn-setting btn-warning" " style="color:#ffffff;margin-left:100px;" data-target="#myModal" data-toggle="modal">新增优惠码</button>
			<form class="form-horizontal"
				action="<?php echo $this->url('admin-invitation',array('action'=>'index','cid'=>$cid,'page'=>1))?>"
				method="post" style="float: right; margin-left: 20px;">
				<span style="font-weight: bold; font-size: 14px;"> 搜索全表</span>
				：
				<input type="text" name="keyword" value="<?php echo $keyword?>"
					placeholder="搜索 ID、手机、昵称">
				<input type="submit" name="submit" value="搜索" class="btn btn-info"
					style="height: 25px; width: 60px; line-height: 25px; padding: 0; margin-left: 10px; margin-top: 5px;" />
			</form>
			<!--
			<button id="mmmm">发短信</button>
			<input type="text" name="mobile" class="mobiles">
			-->
		</h3>

		<div class="panel-options">

			<a href="#" data-toggle="panel">
				<span class="collapse-icon">&ndash;</span>
				<span class="expand-icon">+</span>
			</a>
			<a href="#" data-toggle="remove"> &times; </a>
		</div>
	</div>
	<div class="panel-body">
		<table class="table table-bordered table-striped" id="example-4">
			<thead>
				<tr>
					<th>ID</th>
					<!-- <th>设备ID(编号)</th> -->
					<th>所属用户</th>
					<th>使用用户</th>
					<th>优惠码</th>
					<th>使用时间</th>
					<th>生成时间</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
            <?php if($list){?>
            <?php foreach($list as $v){?>
                <tr>
					<td><?php echo $v->id; ?></td>
					<!-- <td><?php echo $v->device_id; ?>（<?php echo $v->d_device_id?>）</td> -->
					<td> <?php echo $v->mobile ? $v->mobile : '暂未绑定用户'; ?></td>
					<td> <?php echo $v->r_mobile ? $v->r_mobile : '未使用'; ?></td>
					<td> <?php echo $v->code; ?></td>
					<td><?php echo $v->timestamp_update == '0000-00-00 00:00:00' ? ' ' : date("Y-m-d H:i",strtotime($v->timestamp_update));?></td>
					<td><?php echo $v->timestamp == '0000-00-00 00:00:00' ? ' ' : date("Y-m-d H:i",strtotime($v->timestamp));?></td>
					<td>
                        <?php $status = $this->escapehtml($v->status)?>
						<?php if($status==0){?>
						 <a class="btn btn-warning" href="javascript:;" onclick="show_confirm_message('<?php  echo $this->url('admin-invitation',array('action'=>'status','cid'=>1,'id'=>$v->id));?>','确认设为已使用吗？')">
							设为已使用 </a>  
						<?php }?>
                    </td>
				</tr>
            <?php }}?>
            </tbody>
		</table>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-invitation','condition'=>$condition));?>
        </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="false" style='z-index:8888;'>
	<div class="modal-dialog" >
		<div class="modal-content" >
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>新增优惠码</h3>
			</div>
			<div class="modal-body">
				<input type="text" name="mobile" placeholder="请输入用户手机号" id="mobile"/><span id="err" style="color: red"></span>
			</div>
			<div class="modal-body">
				<input type="text" name="number" placeholder="生成个数" id="number"/>
			</div>
    		<div class="modal-footer">
    		<a href="#" class="btn" data-dismiss="modal">取消</a>
    		<a href="javascript:returns()" class="btn btn-primary">确定</a>
    	   </div> 
		</div>
		</div>
</div>
<script type="text/javascript">
$("#mobile").blur(function(){
	if($(this).val())
	{
		$.post("<?php echo $this->url('admin-invitation',array('action'=>'getUser'));?>", { mobile: $(this).val()},
		function(data)
		{
		    $("#err").text(data);
		 });
	}
});

function returns()
{
	if(!$("#mobile").val())
	{
		alert('用户手机号不能为空！');
	}
	$.post("<?php echo $this->url('admin-invitation',array('action'=>'add'));?>", { mobile: $("#mobile").val(),number:$("#number").val()},
			function(data)
			{
			   if(data=='1')
			   {
				   alert('添加成功!');
				   location.reload(true);	
			   }
			   else
			  {
				   alert('添加失败!');
			  }
	});
}

// $("#mmmm").click(function(){
// 	if(!$(".mobiles").val())
// 	{
// 		alert('用户手机号不能为空！');
// 		return false;
// 	}
//	$.post("<?php //echo $this->url('admin-invitation',array('action'=>'message'));?>", { mobile: $(".mobiles").val()},function(data){
// 		if(data=='1')
// 		  {
// 			  alert('发送成功');
// 			  location.reload(true);	
// 		  }
// 		  else
// 		  {
// 			  alert('发送失败!');
// 		  }
// 	});
// });
</script>
