
<div class="row">
    <form role="form" class="form-horizontal" action="<?php echo $this->url('admin-user', array('action' => 'addUser')) ?>" onsubmit="return checkSubmit()" method="post">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>基本资料</h3>
                </div>
                <div class="panel-body">          
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="field-4">用户名：</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" maxlength="6"  placeholder="<?php echo isset($info->name) ? $info->name : ''; ?>" 
                                   value="<?php echo isset($info->name) ? $info->name : ''; ?>" name="name" required />
                        </div>
                    </div>
                    <div class="form-group-separator"></div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="field-4">移动电话：</label>
                        <div class="col-sm-10">
                          
                                <input type="text" class="form-control" required pattern="1[0-9]{10}"  placeholder="<?php echo isset($info->mobile) ? $info->mobile : ''; ?>" 
                                       value="<?php echo isset($info->mobile) ? $info->mobile : ''; ?>" name="mobile" disebed >
                            
                        </div>
                    </div>
                    <div class="form-group-separator"></div>

                    
                    <div class="form-group">
                        <label class="col-sm-2 control-label"></label>

                        <div class="col-sm-10">                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
