<!-- Responsive Table -->
<!-- Table exporting -->
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
			<form class="form-horizontal"
				action="<?php echo $this->url('admin-microblog',array('action'=>'comment'))?>" method="post"
				style="float: right; margin-left: 20px;">
				<span style="font-weight: bold; font-size: 16px;"> 搜索全表</span>
				：
				<input type="text" name="keyword" value="<?php echo $keyword?>"
					placeholder="搜索 ID、评论人ID、内容">
				<input type="submit" name="submit" value="搜索" class="btn btn-info"
					style="height: 25px; width: 60px; line-height: 25px; padding: 0; margin-left: 10px; margin-top: 5px;" />
			</form>
		</h3>

		<div class="panel-options">

			<a href="#" data-toggle="panel">
				<span class="collapse-icon">&ndash;</span>
				<span class="expand-icon">+</span>
			</a>
			<a href="#" data-toggle="remove"> &times; </a>
		</div>
	</div>
	<div class="panel-body">
		<table class="table table-bordered table-striped" id="example-4">						
						  <thead>
							  <tr>
							      <th>ID</th>
							       <th>评论内容</th>
								  <th>评论人</th>							 
								  <th>评论时间</th>								  								  
							  </tr>
						  </thead>   
						  <tbody>
						  <?php foreach ($list as $v){?>

							<tr>
							    <td><?php echo $v->id?></td>
							    <td><?php echo mb_substr($v->content, 0, 25, 'UTF-8');?></td>
							    <td><a href="<?php echo $this->url("admin-user",array('action'=>'details','id'=>$v->user_id))?>"><?php echo $v->name;?></a></td>
								<td><?php echo date("Y-m-d H:i",strtotime($v['timestamp']));?></td>
							</tr>

							<?PHP }?>
							
						  </tbody>
					  </table>
 					  
					   <div class="pagination pagination-centered">
						<?php    echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'admin-microblog','condition'=>$condition));?> 
						</div>  
					              
					</div>
				</div><!--/span-->