<style type="text/css">
.dataTables_paginate ul {
	display: none
}
</style>
<div id="content" class="span10">

	<!-- content starts -->
	<div>
		<ul class="breadcrumb">
			<li>
				<a href="">其它</a>
				<span class="divider">/</span>
			</li>
			<li>
				<a href="#">愿望管理</a>
			</li>
		</ul>
	</div>
	<div>
		
		<form class="form-horizontal"
			action="<?php echo $this->url('admin-other',array('action'=>'tucao'))?>"
			method="post" style="float: right;">
			搜索全表：
			<input type="text" name="keyword" value="<?php echo $keyword?>" placeholder="搜索 吐槽">
			<input type="submit" name="submit" value="搜索"
				class="btn btn-large btn-primary"
				style="height: 30px; width: 60px; line-height: 30px; padding: 0; margin-left: 10px;" />
		</form>
      
	</div>



	<div class="row-fluid sortable">
		<div class="box span12">
			<div class="box-content">

				<table
					class="table table-striped table-bordered bootstrap-datatable">
					<thead>
						<tr>
							<th>用户名</th>
							<th>吐槽</th>
							<th>吐槽时间</th>
						</tr>
					</thead>
					<tbody>
						  <?php if($list){?>
						 <?php foreach($list as $v):?>
						 			   
							<tr>
							<td><a href="<?php echo $this->url("admin-user",array('action'=>'details','id'=>$v->user_id))?>"><?php echo isset($user_name[$v->user_id]['nickname']) ? ($user_name[$v->user_id]['id_name'] ? $user_name[$v->user_id]['id_name'] : $user_name[$v->user_id]['nickname']) : '';?></a></td>
							<td><?php echo emoji_unified_to_html($v->content);?></td>
							<td class="center"><?php echo $v->timestamp == '0000-00-00 00:00:00' ? '' :date("Y-m-d H:i",strtotime($v->timestamp));?></td>
							
						</tr>
							<?php endforeach;?>
							<?php }?>						
						  </tbody>
				</table>

				<div class="pagination pagination-centered">
					   
						  <?php    echo $this->paginationControl($paginator, 'Sliding', 'page',array('route' =>'new-admin-other','condition'=>$condition));?> 
						</div>

			</div>
		</div>
		<!--/span-->
	</div>
	<!--/row-->

</div>


